### ISSUE TITLE
How to call multi-thread

### ISSUE THREAD

**Issue by ucassee** [ebi-pf-team/interproscan#100]
I use `interproscan.sh -appl Pfam,TIGRFAM -i bin2.fa -cpu 20` to annotate my sequences. But I find in the `hmmsearch` step only one thread was used.  What should I do to call multi-thread.
Thanks in advance!

**Comment by gsn7** [comment]
the default setting in interproscan  is that each analysis uses 1 core for a batch of sequences. for example, pfam and tigrfam each use 1 core for every 4000 sequences.   
to change this setting, for pfam and tigrfam, you have to update interproscan.properties and change the cpu setting to 4:
hmmer3.hmmsearch.cpu.switch.pfama=--cpu 1
hmmer3.hmmsearch.cpu.switch.tigrfam=--cpu 1

see https://github.com/ebi-pf-team/interproscan/wiki/ImprovingPerformance
