### ISSUE TITLE
requirement to install libdw

### ISSUE THREAD

**Issue by flass** [ebi-pf-team/interproscan#101]
Hi,

having installed the last version (interproscan-5.36-75.0), I got an error thrown at some point of the execution. It mentioned not being able to find shared library object libdw.so.1:
```
error while loading shared libraries: libdw.so.1
```
Unfortunately I erased the error logs by mistake.
I installed the following packages:
```sh
sudo apt install libdw1 libdw-dev
```
which fixed the issue.
I mention it as I don't think this is specified as a system requirement on your installation page.

My system is a Ubuntu 18.04.1 LTS (`Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`).

best wishes,

Florent

**Comment by gsn7** [comment]
it would have been nice if you had the error logs, as that would have allowed us to note which analysis is throwing the error. unfortunately i have not encountered this error before and am using Ubuntu 18.04.

**Comment by flass** [comment]
Hi,
I uninstalled libdw1 and libdw:
```
sudo apt remove libdw*
...
Removing libdw-dev:amd64 (0.170-0.4ubuntu0.1) ...
Removing libdw1:amd64 (0.170-0.4ubuntu0.1) ...
```
and re-ran interproscan, and thus could replicate the bug.
please find attached the log:

[all_proteomes.nr.faa.0_interpro.log.nolibdw.txt](https://github.com/ebi-pf-team/interproscan/files/3461069/all_proteomes.nr.faa.0_interpro.log.nolibdw.txt)

best regards,
Florent

**Comment by timkahlke** [comment]
Hi,
I ran into the same and in case it's still of interest installing "elfutils" will solve the problem

`sudo apt-get install elfutils`

Cheers,
Tim

**Comment by ampinzonv** [comment]
Same problem still here. Solved the same way as @flass suggested.
