### ISSUE TITLE
Could not load properties from URL

### ISSUE THREAD

**Issue by KunathBJ** [ebi-pf-team/interproscan#104]
Hello,

I saw that there was a previous similar issues open but no answer from the guy that started it so I try again.
I try to run interproscan on a slurm HPC cluster and I'm using Java/1.8.0_162 

Here is my script:
```
module load lang/Java/1.8.0_162

input=/Path/CdHit_All_Prot_Clust
out=/Path/interpro_out
interpro=/Path/interproscan/interproscan-5.36-75.0/interproscan-5.jar
Temp=/Path/Temp

java -XX:+UseParallelGC -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Xms2048M -Xmx20480M -jar $interpro -appl TIGRFAM,SFLD,Pfam -cpu 20 -goterms -i $input -iprlookup -o $out -T $Temp
```

And here is the log file with the error:
[slurm-1161675.txt](https://github.com/ebi-pf-team/interproscan/files/3608887/slurm-1161675.txt)
The interproscan properties file is in the same folder that the interproscan.sh file.

Any idea of what happened??
Thanks a lot for your help,

Ben

**Comment by KunathBJ** [comment]
Any input on that?
Thank you very much

**Comment by gsn7** [comment]
interproscan uses relative paths for all resources in interproscan-5.jar, so your script would indeed fail. Ideally use the interproscan.sh script and make changes there if required.

have you tried the following or something similar?

module load lang/Java/1.8.0_162

input=/Path/CdHit_All_Prot_Clust
out=/Path/interpro_out
Temp=/Path/Temp

/Path/interproscan/interproscan-5.36-75.0/interproscan.sh -appl TIGRFAM,SFLD,Pfam -cpu 20 -goterms -i $input -iprlookup -o $out -T $Temp
