### ISSUE TITLE
Ignored options `--iprlookup`, `--goterms` and `--pathways` 

### ISSUE THREAD

**Issue by flass** [ebi-pf-team/interproscan#105]
Hi,

I just finished running InterProscan on a dataset, and I was surprised to see that the additional columns I normally get by using the `--iprlookup`, `--goterms` and `--pathways` options were absent.

I know I should be getting a IPR id and associated GO terms as I got a hit for Pfam domain [PF01555](https://www.ebi.ac.uk/interpro/entry/pfam/PF01555/), which is linked to entry [IPR002941](https://www.ebi.ac.uk/interpro/entry/InterPro/IPR002941/), itself linked to to [GO:0006306](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006306).

I ran the new release InterProScan-5.37-76.0 with the following command:
```sh
$ interproscan.sh -T tmp/interpro -i all_proteomes.nr.faa.54.test -b all_proteomes.nr.faa.54.test --formats TSV --cpu 15 --iprlookup --goterms --pathways
```
I tried different variations of options, including using the short version `-iprlookup`, `-goterms` and `-pa` but did not get any more results. Changing the order of option with `--cpu 15` at the end or not all did not help either.

I also have the following issue (I don't think it is connected, but you never know): at the end of the help message, I get the following warning:
```
$ interproscan.sh --help
...
Deactivated analyses:
                      PANTHER (14.1) : Analysis Panther is deactivated, because the resources expected at the following paths do not exist: data/panther/14.1/panther.hmm, data/panther/14.1/names.tab
                  SignalP_EUK (4.1) : Analysis SignalP_EUK is deactivated, because the resources expected at the following paths do not exist: bin/signalp/4.1/signalp
        SignalP_GRAM_POSITIVE (4.1) : Analysis SignalP_GRAM_POSITIVE is deactivated, because the resources expected at the following paths do not exist: bin/signalp/4.1/signalp
                      Phobius (1.01) : Analysis Phobius is deactivated, because the resources expected at the following paths do not exist: bin/phobius/1.01/phobius.pl
        SignalP_GRAM_NEGATIVE (4.1) : Analysis SignalP_GRAM_NEGATIVE is deactivated, because the resources expected at the following paths do not exist: bin/signalp/4.1/signalp
                        TMHMM (2.0c) : Analysis TMHMM is deactivated, because the resources expected at the following paths do not exist: bin/tmhmm/2.0c/decodeanhmm, data/tmhmm/2.0c/TMHMM2.0c.mod
```

and indeed the files are missing from the respective folders. is this normal? when downloading the archive of the last release, the md5sum check was fine, so I suppose it was not corrupted.

Any idea of what is going on, and how I could recover the IPR accession, GO term and pathway annotations?

many thanks

Florent

**Comment by gsn7** [comment]
this is a bug. only for the tsv output, the current version ignores the --iprlookup flag and hence you don't get the go-terms and pathway information. the json, xml output formats do behave as expected and will give you the IPR accessions, go-terms and pathway annotations. 

we will fix the bug and make a bug-fix release in two days or so. unfortunately, you will have to rerun your analyses when the bug fix is done. 

the information you get under 'Deactivated analyses:' is expected. The Panther data has to be downloaded separately as it is a huge file. see the instructions https://github.com/ebi-pf-team/interproscan/wiki/HowToDownload#2-installing-panther-models. The other analyses listed - signalp,tmhmm,phobius have licensed components and you have to arrange that yourself if interested in transmembrane and signal peptide predictions. see in https://github.com/ebi-pf-team/interproscan/wiki/ActivatingLicensedAnalyses

**Comment by flass** [comment]
Hi,
thank you for the clarification and identifying the bug. I look forward to see the fix and use it Fortunately with the lookup service should I should be able to re-run all this within not so much time.
Best wishes,
Florent

**Comment by gsn7** [comment]
this bug is now fixed in interproscan-5.38-76.0

**Comment by flass** [comment]
Thnaks for letting me know! I ll try the new release asap!

**Comment by Agihawi** [comment]
Hi,

I'm creating a singularity for InterProScan. I am currently using InterProScan version 5.39-77.0 and I also run into this error. 


doesn't give me GO term categories:

```
interproscan.sh -f tsv --goterms --iprlookup --pathways -T temp_bp -i proteins/PROKKA_12062019.faa -o temp_go_terms2.tsv
```

does give me GO term categories (ie 'BIOLOGICAL_PROCESS'):

```
interproscan.sh -f json --goterms --iprlookup --pathways -T temp_bp -i proteins/PROKKA_12062019.faa -o temp_go_terms2.json
```

I will try to convert results from JSON to TSV for the time being.

Kind Regards,
Abe

**Comment by gsn7** [comment]
@Agihawi  TSV is a summary output format, so it will not give you all the details of the go-term, but only the identifier. see https://github.com/ebi-pf-team/interproscan/wiki/OutputFormats#tab-separated-values-format-tsv
JSON and XML formats present the complete set of details for the matches
