### ISSUE TITLE
Can't run on some species

### ISSUE THREAD

**Issue by marcoooo** [ebi-pf-team/interproscan#109]
Got an error exit code 130 for some Interproscan run:

Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
ERROR: uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep - Command line failed with exit code: 130
Command: bin/hmmer/hmmer3/3.1b1/hmmscan -E 10 -Z 15438 --cpu 1 -o /scratch/z8tTOe2gU9/hx-noah-69-06.ebi.ac.uk_20191014_135353038_b7xp//jobSuperFamily-1.75/000000000001_000000000100.raw.out data/superfamily/1.75/hm
mlib_1.75 /scratch/z8tTOe2gU9/hx-noah-69-06.ebi.ac.uk_20191014_135353038_b7xp//jobSuperFamily-1.75/000000000001_000000000100.fasta 
Error output from binary:
ERROR: uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep - Command line failed with exit code: 130
Command: bin/hmmer/hmmer3/3.1b1/hmmsearch -Z 65245 -E 0.001 --cpu 1 -o /scratch/z8tTOe2gU9/hx-noah-69-06.ebi.ac.uk_20191014_135353038_b7xp//jobGene3d/000000000001_000000000100.raw.out --domtblout /scratch/z8tTOe2g
U9/hx-noah-69-06.ebi.ac.uk_20191014_135353038_b7xp//jobGene3d/000000000001_000000000100.raw.domtblout.out data/gene3d/4.2.0/gene3d_main.hmm /scratch/z8tTOe2gU9/hx-noah-69-06.ebi.ac.uk_20191014_135353038_b7xp//jobG
ene3d/000000000001_000000000100.fasta

**Comment by gsn7** [comment]
you need to provide a more complete error log as this snippet doesn't have all the information that would help find the problem

**Comment by gsn7** [comment]
you should update your interproscan to InterProScan-5.38-76.0 as InterProScan-5.37-76.0 had a bug not related to your problem (see https://github.com/ebi-pf-team/interproscan/wiki/Interproscan5_38_76_ReleaseNotes)

the error log doesn't specify the error, unfortunately. this is strange.  what do you get when you run the following command?
interproscan.sh -i </path/to/interproscan/>test_all_appl.fasta -f tsv -dp

**Comment by gsn7** [comment]
and how much memory are you giving your job? Since the binaries interproscan is running are not giving any specific error output, it can be that the processes are stopped externally  due to resource problems

**Comment by marcoooo** [comment]
> and how much memory are you giving your job? Since the binaries interproscan is running are not giving any specific error output, it can be that the processes are stopped externally due to resource problems

We are giving 16Gb for these jobs to run.

**Comment by marcoooo** [comment]
> you should update your interproscan to InterProScan-5.38-76.0 as InterProScan-5.37-76.0 had a bug not related to your problem (see https://github.com/ebi-pf-team/interproscan/wiki/Interproscan5_38_76_ReleaseNotes)
> 
> the error log doesn't specify the error, unfortunately. this is strange. what do you get when you run the following command?
> interproscan.sh -i </path/to/interproscan/>test_all_appl.fasta -f tsv -dp

Was not an option to run it with previous version (prior to 2nd of October) to keep our deadlines for ensembl release. We'll use 77 for next run.

**Comment by marcoooo** [comment]
We just received a notification of a newer version availability, should we close this one then ?

**Comment by gsn7** [comment]
yes you can close this
