### ISSUE TITLE
Interproscan license

### ISSUE THREAD

**Issue by Imoteph** [ebi-pf-team/interproscan#11]
Hi,

I was wondering under what licence agreement is interproscan published and as well if users where able to deactivate parts of the software where getting a license would be difficult?

**Comment by mifraser** [comment]
Hi,

If you have installed InterProScan as normal then you shouldn't need to deactivate anything. InterProScan is distributed under the open source Apache license http://www.apache.org/licenses/LICENSE-2.0

There are some member database analyses (SignalP, Phobius and TMHMM) that do have licensed components, however these binaries are not included by default. So those analyses are deactivated unless you take steps to activate them (you'd need to get the necessary license and files from the member database websites and ensure your interproscan.properties file is configured to use them).

Thanks,

Matt

**Comment by Imoteph** [comment]
Thanks a lot for this clarifications
