### ISSUE TITLE
Conda Install

### ISSUE THREAD

**Issue by JChristopherEllis** [ebi-pf-team/interproscan#112]
Any thoughts on making a conda package for this? It would greatly increase the number of researchers using this great software package.

**Comment by gsn7** [comment]
others have looked at making a conda build. see https://github.com/ebi-pf-team/interproscan/issues/95

**Comment by gsn7** [comment]
we haven't had time to consider a conda build ourselves.

**Comment by JChristopherEllis** [comment]
Yea, it is actually pretty easy. You should be able to do it in about a day and the number of users would likely increase significantly.

**Comment by Juke34** [comment]
@JChristopherEllis I think you are fairly optimistic. You don't realize that there is 7 other dependencies without conda recipe neither. I'm working on it. We must first create recipe for all dependencies before to do the interproscan one...
