### ISSUE TITLE
compatibility with SignalP 5.0

### ISSUE THREAD

**Issue by dmvvliet** [ebi-pf-team/interproscan#113]
Hi,

Currently interproscan supports SignalP 4.1. The newer version SignalP 5.0 has been out for half a year and has significant improvements such as predicting Tat signal peptides and being applicable to Archaea too. However, it seems to me this new version is not compatible with interproscan currently, as the files included in v5.0 look quite different from 4.1 (no perl script in lib, no bin/signalp/4.1/bin/nnhowplayer.Linux_*** files). Will interproscan support SignalP 5.0 in the future?

kind regards, Daan

**Comment by gsn7** [comment]
thanks for the info. we will start updating to Signalp 5.0 early next year

**Comment by dmvvliet** [comment]
thanks!

**Comment by m3hdad** [comment]
Hi, I'm assuming Signalp 5.0 is not yet compatible, looking forward to any update. Thank you

**Comment by gsn7** [comment]
we have started to look at updating to SignalP 5.0, but there is a bug in the way  SignalP 5.0 is implemented. it doesn't run successfully if you call it using an absolute path to the binary say /home/user/bin/signalp. So we will wait until the SignalP developers fix the bug before updating

**Comment by JamesWZM** [comment]
SignalP 6.0 has been out...... I'd really appreciate it if you could tell us any information about the plan for updating

**Comment by matthiasblum** [comment]
@JamesWZM we will be looking into updating InterProScan to support SignalP 6.0. However, we have to update several member databases (e.g. Pfam 34.0, PANTHER 16.0, CDD 3.19) and this will take priority over SignalP.

**Comment by matthiasblum** [comment]
We have looked into updating SignalP from 4.1 to 6.0. 

Although SignalP 6.0 is more accurate than 4.1, it is unfortunately much slower. We have then decided not to update SignalP.
