### ISSUE TITLE
Error: bad file format in HMM file data/panther/14.1/panther.hmm

### ISSUE THREAD

**Issue by niconm89** [ebi-pf-team/interproscan#115]
Hi, I'm trying to run interproscan v5.38-76 but it fails when I add panther to the data folder (where databases are in). The error is the same as the title:

> Error: bad file format in HMM file data/panther/14.1/panther.hmm

I downloaded the panther files and I did check the MD5 checksum and was ok.

My run command is something like:

`./interproscan.sh -f TSV,XML,GFF3,HTML,SVG --cpu 8 --applications panther -i Dko11_AbIni-rnd3.all.maker.proteins.fasta --goterms --pathways -b Dko11_rnd3_test`

Even if I used the --disable-precalc, it fails. I can't connect to the server from my place of work (two firewalls) so I have to use the -dp option.

Some advice?

Thanks!

**Comment by gsn7** [comment]
are you able to run the other analyses like Gene3D with the -dp option?
i would to see the complete error log to see where this error is being generated

**Comment by niconm89** [comment]
Yes, I could correctly run Gene3D with -dp . However, when I run the panther analysis, It failed. The command was:

`./interproscan.sh -f TSV,XML,GFF3,HTML,SVG --cpu 8 --applications PANTHER -dp -i /home/nmoreyra/Data/annotation_maker/Dko11/01_maker/02_MAKER_with_Ab-Initio_Gene_Predictors/rnd3/Dko11_AbIni-rnd3.maker.output/Dko11_AbIni-rnd3.all.maker.proteins.fasta --goterms --pathways -b Dko11_rnd3_test >& out.log`

Attached you can find the standard output of the program. The temp folder was empty after the failure so I did not have any log file to check the error.

[out-panther.log](https://github.com/ebi-pf-team/interproscan/files/3849711/out-panther.log)

**Comment by gsn7** [comment]
the panther hmm file seems to have been corrupted. if the md5sum checked ok, it might mean errors came from the unzipping. then you might just do the 'tar -pxzf panther-data-14.1.tar.gz'  step again
