### ISSUE TITLE
issue : data/freemarker/WEB-INF/freemarker does not exist

### ISSUE THREAD

**Issue by jervermex** [ebi-pf-team/interproscan#116]
Dear all,
I'm in charge of a cluster , and some user ask me to install Interproscan. I have to put all the "data" directory in another place from Interproscan, and change all of the value inside the interproscan.properties file.

A user is facing an isswue when is running :+1: 
$ interproscan.sh -appl HAMAP,PANTHER,Pfam,PROSITEPATTERNS,PROSITEPROFILES,SUPERFAMILY,TIGRFAM -i hypothetical.faa

11/11/2019 10:45:50:666 Welcome to InterProScan-5.38-76.0
11/11/2019 10:45:50:670 Running InterProScan v5 in STANDALONE mode... on Linux

../..

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'templateLoaderHtmlWriter' defined in class path resource [spring/jobs/outputWriter/html/htmlWriter-context.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [freemarker.cache.FileTemplateLoader]: Constructor threw exception; nested exception is java.io.FileNotFoundException: data/freemarker/WEB-INF/freemarker does not exist.
at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378)
at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)

I can realize how to indicate to Interproscan that this file "data/freemarker/WEB-INF/freemarker", exist, and it's located inside the "data" from interproscan..

Hope that someone can help us!

Regards

**Comment by gsn7** [comment]
the current setup is such that interproscan will still looks for freemarker in the data directory relative to the install directory.
you should still put free marker in the expected directory and the other data directories where ever you want.
we will work to refactor the config to best deal with this

**Comment by jervermex** [comment]
Dear gsn7.

Ok, thank's for your answer. Sorry to read it late. We will try with this correction.
Thank's!

**Comment by gsn7** [comment]
this is now fixed
