### ISSUE TITLE
Interproscan really big

### ISSUE THREAD

**Issue by aberaslop** [ebi-pf-team/interproscan#117]
Hi all,
I am trying to install interproscan on a virtual machine. InterproScan installs with no problem, but when I try to untar panther, I get this:

tar -pxvzf panther-data-14.1.tar.gz 
panther/
panther/14.1/
panther/14.1/panther.hmm.h3f
panther/14.1/panther.hmm.h3i
panther/14.1/panther.hmm.h3m
tar: panther/14.1/panther.hmm.h3m: Wrote only 8704 of 10240 bytes
panther/14.1/panther.hmm.h3p
tar: panther/14.1/panther.hmm.h3p: Wrote only 7168 of 10240 bytes
panther/14.1/names.tab
panther/14.1/panther.hmm
tar: panther/14.1/panther.hmm: Wrote only 6656 of 10240 bytes
tar: Exiting with failure status due to previous errors

I have checked, and I have run out of space (I had more than 50GB free). Is this normal? I am not sure I can allocate more space to my VM. Is there anyway to go around it? Is there anyway to run Interproscan online?

Thank you!

L.

**Comment by gsn7** [comment]
Panther is a big database. So you need to have space for it. You can run interproscan using the REST API https://www.ebi.ac.uk/seqdb/confluence/display/JDSAT/InterProScan+5+Help+and+Documentation#InterProScan5HelpandDocumentation-RESTAPI

**Comment by aberaslop** [comment]
Thank you, gsn7. I will explore this possibility.
