### ISSUE TITLE
Download profile HMM for specific Interpro entry

### ISSUE THREAD

**Issue by janstrauss1** [ebi-pf-team/interproscan#118]
Dear ebi-pf-team,

I'm very interested in downloading specific HMM profiles (or the complete HMM library searchable with `hmmfetch`) used in Interpro searches. Can I download the HMM profiles anywhere?

I would like to use `hmmsearch` of specific HMM profiles on some custom seqence databases.

Many thanks in advance for your help!

**Comment by gsn7** [comment]
There is no actual profile HMM for a a specific InterPro entry. We don't produce any HMMs.  We don't  produce any signatures directly, but base everything around the libraries of signatures
(profiles, profile HMMs and regular expressions) provided by our member
databases.  check https://www.ebi.ac.uk/training/online/course/interpro-quick-tour
