### ISSUE TITLE
"66% completed" continuously show up hourly

### ISSUE THREAD

**Issue by DOieGYuan** [ebi-pf-team/interproscan#119]
Hi! everyone
I use interproscan-5.39-77.0 to annotate my amino acid sequence (n = 7,000) retrieved from NCBI. However, the process is keeping on "66% completed" and never forward on. The "66% completed" shows up hourly. The whole output is like this
<./interproscan.sh -i metaproteome_clean.fasta -d test/ -cpu 30 -goterms -pa -iprlookup>
"21/11/2019 18:37:18:818 Welcome to InterProScan-5.39-77.0
21/11/2019 18:37:18:820 Running InterProScan v5 in STANDALONE mode... on Linux
21/11/2019 18:37:35:061 Loading file /home/nature/App/interproscan-5.39-77.0/metaproteome_clean.fasta
21/11/2019 18:37:35:063 Running the following analyses:
[CDD-3.17,Coils-2.2.1,Gene3D-4.2.0,Hamap-2019_01,MobiDBLite-2.0,PANTHER-14.1,Pfam-32.0,PIRSF-3.02,PRINTS-42.0,ProSitePatterns-2019_01,ProSiteProfiles-2019_01,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
20/11/2019 19:47:08:888 33% completed
20/11/2019 19:48:25:655 66% completed
20/11/2019 20:48:25:667 66% completed
20/11/2019 21:48:25:734 66% completed
20/11/2019 22:48:25:798 66% completed
20/11/2019 23:48:25:804 66% completed
21/11/2019 00:48:25:888 66% completed
21/11/2019 01:48:25:920 66% completed
21/11/2019 02:48:26:019 66% completed
21/11/2019 03:48:26:095 66% completed
21/11/2019 04:48:26:106 66% completed
21/11/2019 05:48:26:194 66% completed
21/11/2019 06:48:26:201 66% completed
21/11/2019 07:48:26:288 66% completed
21/11/2019 08:48:26:339 66% completed
21/11/2019 09:48:26:381 66% completed
21/11/2019 10:48:26:449 66% completed
21/11/2019 11:48:26:483 66% completed
21/11/2019 12:48:26:503 66% completed
21/11/2019 13:48:26:573 66% completed
21/11/2019 14:48:26:575 66% completed
21/11/2019 15:48:26:638 66% completed
21/11/2019 16:48:26:657 66% completed
21/11/2019 17:48:26:738 66% completed
..........
.........."

what's wrong?

**Comment by gsn7** [comment]
this might have to do with memory allocated to the interproscan job but 7000 is not a large set of input. Did you run run this again and got the same error?

**Comment by vrou1995** [comment]
Hi,

I'm getting the same sort of issue but my analysis (of a metagenome bin) gets stuck at 70% every time. I've run it a few times now.

**Comment by gsn7** [comment]
@vrou1995 what version of interproscan are you running and how many sequences are in your input file?

**Comment by vrou1995** [comment]
version 5.36-75.0

I am searching with a Metagenome bin (nucleotide). The file size is 3.7MB.

Thanks in advance for your help!
![Screenshot 2020-01-23 at 10 23 02](https://user-images.githubusercontent.com/48283664/72976649-e8676600-3dca-11ea-9dfb-fd4410b269c0.png)

**Comment by gsn7** [comment]
version version 5.36-75.0 was inefficient with memory usage, but I was expecting a small size of 3.7MB should run without problems. 
the latest version is much more efficient and I would advise you switch to the latest version.  if the problem continues, then i would like to see the input and try reproduce the problem

**Comment by gsn7** [comment]
the latest version 5.41-78.0 has much better performance
