### ISSUE TITLE
ERROR  when running PANTHER analysis

### ISSUE THREAD

**Issue by yoyohashao** [ebi-pf-team/interproscan#12]
Hello, I am new to interproscan and want to perform PANTHER analysis. At first, I got the error message that PANTHER didn't exist or deactivated. I then edited the properties file and PANTHER seemed to be able to run. However, after several minutes the program failed. 
The PANTHER database I used was 11.0, which was just released on July 15th
Frankly, I don't really understand the error messages. I attached the output log here for your inspection. Many thanks
[nohup.txt](https://github.com/ebi-pf-team/interproscan/files/393195/nohup.txt)

**Comment by mifraser** [comment]
Hi,

InterProScan 5.19-58.0 is based on InterPro 58.0 data which requires PANTHER 10.0. The errors are because the software doesn't know how to handle PANTHER 11.

Did you follow step 2 of the download process as described in https://github.com/ebi-pf-team/interproscan/wiki/HowToDownload ? If you follow that process then the interproscan.properties file wouldn't need changing because the data should be in the default place...

panther.signature.library.release=10.0
panther.models.dir=data/panther/10.0/model

Hope that helps!

Thanks,

Matt

**Comment by yoyohashao** [comment]
Thank you Matthew. I got the results I need. 
Nonetheless, as I ran interproscan on SLURM clusters (my administrator has modefied the properties file for me), there were some error messages like : 

> 02/08/2016 11:56:26:660 Welcome to InterProScan-5.19-58.0
> The Project/Cluster Run ID for this run is: cpu
> 02/08/2016 11:57:13:580 Running InterProScan v5 in CLUSTER mode... on Linux
> 02/08/2016 11:57:13:580 Interproscan 5 Master process running on: tcp://node129:44565
> 02/08/2016 11:57:25:321 Loading file /lustre/home/clslzy/usr/interproscan/de-contigs-pep-100.fa
> 02/08/2016 11:57:25:327 Running the following analyses:
> [PANTHER-10.0]
> Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
> 02/08/2016 11:57:36:812 Uploaded/Stored 17616 sequences for analysis
> 2016-08-02 11:57:40,733 [pool-1-thread-1] [uk.ac.ebi.interpro.scan.jms.master.queuejumper.platforms.SubmissionWorkerRunner:340] WARN - Non-zero exit status from attempting to run a worker: 
> Command:sbatch -p cpu -o logs/cpu/cpu_-958063561_nw_00.out.0 -e logs/cpu/cpu_-958063561_nw_00.err.0 java -Xms32m -Xmx2048m -jar interproscan-5.jar --mode=distributed_worker --priority=4 --masteruri=tcp://node129:44565 --tempdirname=node129_20160802_115713577_fhjo --userdir=/lustre/home/clslzy/usr/interproscan --tier1=1 --clusterrunid=cpu --mastermaxlife=1470110260580:21572756
> Exit status: 1
> Error output: sbatch: error: This does not look like a batch script.  The first
> sbatch: error: line must start with #! followed by the path to an interpreter.
> sbatch: error: For instance: #!/bin/sh
> 
>
