### ISSUE TITLE
Merging results from Interproscan and eggnog

### ISSUE THREAD

**Issue by aberaslop** [ebi-pf-team/interproscan#121]
Dear all,
I am annotating a genome using the Maker2 pipeline. In order to add functional annotations, I have used Blast and Interproscan. Maker2 provides a script to merge the results of those two methods. I was wondering if there is a way to merge the results of eggnog to those of blast and Interproscan. Any help is greatly appreciated.

Thanks!

L.

**Comment by gsn7** [comment]
i have never used eggnog and cannot help in this case, sorry

**Comment by aberaslop** [comment]
Thank you anyway, gsn7. Hopefully someone has played around with it and can share some tips.
