### ISSUE TITLE
Java issue

### ISSUE THREAD

**Issue by wuxiaopei0509** [ebi-pf-team/interproscan#123]
Hi ，
I install the latest interproscan ,but the java on my system is 1.8.0_121, actually the newest version requires java 11 . Then ,I install JDK version 11 without uninstalling the old java. And I put JDK version 11 into PATH, and source it like following.However ,interproscan.sh still could not find the JDK version 11. what's the problem? Thanks!
vim /etc/profile 
export JAVA_HOME=/home/wuxiaopei/miniconda2/envs/python=3.4/java/jdk-11.0.5
export PATH=$PATH:/home/wuxiaopei/miniconda2/envs/python=3.4/java/jdk-11.0.5/bin
source  /etc/profile

**Comment by gsn7** [comment]
the path /home/wuxiaopei/miniconda2/envs/**python=3.4**/java/jdk-11.0.5 does not look right. Can you check that
what is the output of the command?
type -p java

**Comment by wuxiaopei0509** [comment]
I install java in the python3.4 envs under conda.
the output of the command is /usr/bin/java

**Comment by gsn7** [comment]
> I install java in the python3.4 envs under conda.
but is your path /home/wuxiaopei/miniconda2/envs/python=3.4/java/jdk-11.0.5/bin?  the presence of "=" in the path string "python=3.4" doesn't look right.

> the output of the command is /usr/bin/java
if the path for java above is correct, then you can update interproscan.sh file to point directly to your java 11 install. change the line
JAVA=$(type -p java)
to the absolute path of your java 11   like
JAVA=/path/to/java/jdk-11.0.5/bin/java

**Comment by wuxiaopei0509** [comment]
Thank you,gsn7. I use another version interproscan at last and works smmothly
