### ISSUE TITLE
fixed tcp port

### ISSUE THREAD

**Issue by clsgithubusr** [ebi-pf-team/interproscan#128]
Hi

Due to firewall restrictions in our company. I need to define a fixed TCP port, or a fixed  TCP port range for messaging in the interproscan.properties

I know there is tcp.port.exclusion.list definition, but I cannot list all excluded tcp ports that are seperated by a comma from range 1025 until 65534

is there any other solution ?

**Comment by gsn7** [comment]
if you running the cluster mode ( -mode cluster), there is no solution to using a fixed port. we will put this on the todo list so a user can either configure a preferred range of ports or a range to exclude.

however, you don't need to use tcp ports for the default mode (standalone mode) of running InterProScan. In any case, we recommend users to use the standalone mode as the cluster mode is currently not fault tolerant.  What is the number of  input sequences you are planning to handle?

I would advice you just use the default mode and just change the degree of parallelism (--cpu) to the number of processors you want to use.

**Comment by clsgithubusr** [comment]
Yes, thay would be a nice-to-have for having an option to configure a preferred range of ports.
