### ISSUE TITLE
Error with SignalP and merging signalP results with Interproscan's

### ISSUE THREAD

**Issue by aberaslop** [ebi-pf-team/interproscan#130]
Dear all,

After installing Interproscan and trying to run it, I realize everything works fine except for signalP. I  am not able to make it work. The problem seems to be that I cannot edit the binary file to change the location of the program, like so:

BEGIN {
    $ENV{SIGNALP} = 'bin/signalp/4.1';
}

If anyone has any idea of how I could change this, I would be super grateful. 
An alternative would be to run signalP on the web, and then add the results to the rest of Interproscan's results. Does anyone know how I could do this?

Thank you so much for your time and help in advance!

L.

**Comment by gsn7** [comment]
interproscan uses signalp 4.1. if you have the higher version v5.0, it will not work

**Comment by aberaslop** [comment]
Thank you gsn7! That was it!
