### ISSUE TITLE
Lookup service don't make InterProScan run faster

### ISSUE THREAD

**Issue by RenanaEvogene** [ebi-pf-team/interproscan#131]
Hi,

We are using InterProScan 5.32-71.0.
In order to make it faster we decided to try using the lookup service.
We installed lookup_service_5.32-71.0 on our system – but we didn't see any improvement in the running time.
(There is an indication in the log that InterProScan is using the the lookup service:
"Available matches will be retrieved from the pre-calculated match lookup service.")

Is there a way to see which of the proteins were found in the lookup service, and which were not?
If there are many proteins that are not in the database of the lookup service – is there a way to update our database?

Thanks,
Renana

**Comment by gsn7** [comment]
Hi,
The lookup match service is calculated against the UniprotKB protein database. So it will improve performance if most of your input sequences can be found in Uniprot.
We will add a feature to show how many proteins have a hit in the lookup service, currently it is not possible. However, the overhead of using the lookup service is small. In the current version InterProScan 5.39-77.0, the overhead is non-significant.

You are using an InterProScan version that is more than a year old. check https://www.ebi.ac.uk/interpro/about/interproscan/   ( or https://github.com/ebi-pf-team/interproscan/wiki) to get the latest version.
