### ISSUE TITLE
no functional annotations in TSV output

### ISSUE THREAD

**Issue by zachrodriguez** [ebi-pf-team/interproscan#133]
I am using interproscan-5.37-76.0. I cannot get the InterPro annotations, GO annotations, or pathway annotations in the TSV output. The last column available is date. These annotations appear in the gff3 files and the xml files, just not in the TSV. 

`interproscan.sh -i test_all_appl.fasta -d ips -goterms -pa -cpu 12 -dp`

I then tried converting after, but got the same result
`interproscan.sh -i ips/test_all_appl.fasta.xml -mode convert -f TSV -d ips`

Any ideas? 
Thank you,
Zach

**Comment by gsn7** [comment]
interproscan-5.37-76.0 had a bug. see https://github.com/ebi-pf-team/interproscan/issues/105.

use the latest version

**Comment by zachrodriguez** [comment]
Thank you!
