### ISSUE TITLE
superfamily ID problem in InterPro

### ISSUE THREAD

**Issue by ValWood** [ebi-pf-team/interproscan#136]
details here:
https://github.com/pombase/website/issues/1472
Can you let us know when the IDs match SUPERFAMILY 2
so we can fix linking?

thanks

Val

**Comment by gsn7** [comment]
The Superfamily team is working on updating the hmm library based on the recent release of SCOP version 2 classification. This is expected to be completed in the next two months. When we get the data, it might take us two to three months to make the update in InterPro.
We use a link like:
     _http://supfam.org/SUPERFAMILY/cgi-bin/scop.cgi?ipid=SSF100879_
 to Superfamily and it works ok for us

**Comment by ValWood** [comment]
thanks!
