### ISSUE TITLE
Lookup for version 5.40-77?

### ISSUE THREAD

**Issue by timkahlke** [ebi-pf-team/interproscan#137]
Hi,
Which lookup server version should I use for interproscan 5.40-77? There is only a 5.39-77 at ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/lookup_service/?
Cheers,
Tim

**Comment by gsn7** [comment]
version 5.39-77.0 of the lookup will be ok for interproscan 5.40-77.0 as they both use InterPro 77 data
