### ISSUE TITLE
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster

### ISSUE THREAD

**Issue by Huangyizhong** [ebi-pf-team/interproscan#141]
Hi
   InterProScan is a good bioinformatics software. I have installed it and tried to run the test data. But errors reported. I have checked the version of the softwares and the integrity of the database. Everything seems OK.  Need help!
![image](https://user-images.githubusercontent.com/31943359/76961791-f7950b00-6958-11ea-9254-a9e275922caf.png)
![image](https://user-images.githubusercontent.com/31943359/76961836-0c719e80-6959-11ea-94a6-07301cccdd02.png)

**Comment by gsn7** [comment]
interproscan is having problems locking files. this might be as a result of the java version you are using or the filesystem or something else. can you give more details of your environment: linux distribution, filesystem, java version, etc
on some network filesystems locking errors are frequently observed

**Comment by Huangyizhong** [comment]
Thanks so much! The following are the details about my softwares. Does the python version have problems?












At 2020-03-20 19:58:32, "gsn7" <notifications@github.com> wrote:

interproscan is having problems locking files. this might be as a result of the java version you are using or the filesystem or something else. can you give more details of your environment: linux distribution, filesystem, java version, etc
on some network filesystems locking errors are frequently observed

**Comment by gsn7** [comment]
you forgot to write the  details of your environment.

**Comment by Arzhura** [comment]
Hello, 
I got a similar error when trying to use the option ' -t n  ', actually the test run well for the protein sequence but not nucleotide one ( ./interproscan.sh -t n -I test_nt_seqs.fasta ). 
I am working on a cluster so I can not install everything I want, so stuff locally only or ask the cluster people to install it with the right.. 
```
uname -a
Linux caucluster2.adm.cluster.rz.uni-kiel.de 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
````
perl -version
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 40 registered patches, see perl -V for more detail)
```
```
python3 --version
Python 3.7.4
```
```
java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
Can you help me ? Here is the error: 

![Capture d’écran 2020-07-14 à 17 05 54](https://user-images.githubusercontent.com/35779216/87442203-48113200-c5f4-11ea-9c96-60aec56b15e7.png)

I think as it doesn't found the Digest/MD5.pm it leads to a fail.... 
Thank you in advance :)

**Comment by gsn7** [comment]
your error is different. what is the linux distribution ad version running on your cluster?

Your system is missing the perl module Digest::MD5 as you have rightly guessed. You can install it by using the command
cpan Digest::MD5
You should ask your system administrator to install it.  You can also install this yourself in your home area by calling the command as above.
If the install is successful, then run the following command to test 
./interproscan.sh -i test_all_appl.fasta -f tsv -dp

**Comment by Arzhura** [comment]
The linux version: 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

I will ask for administrator to install because I try and I can't. 
Thank you, I will come back to you as soon as I get the module..
