### ISSUE TITLE
Is there a defined way to install Java 11 so that InterProScan will work?

### ISSUE THREAD

**Issue by SchwarzEM** [ebi-pf-team/interproscan#142]
I previously installed and ran InterProScan version 5.35-74.0 with success.  However, this week, when I tried to install and run InterProScan version 5.42-78.0 in the same manner but on a new cluster, I found first that version 5.42-78.0 needed Java 11 (not available as an option or module on my new cluster), and then found that 5.42-78.0 would not work when I tried to supply Java 11 as a local, non-root installation.  I assume that this is because I did not set up *exactly* the right version of Java 11 from exactly the right source, or with exactly the right system variables.

I would very much appreciate it if somebody could tell me the precise method for a non-root installation of Java 11 that will work with InterProScan version 5.42-78.0.  In particular, I'd appreciate knowing the *exact* source from which I should be downloading Java 11, and any specific system variables that I should be setting to make InterProScan 5.42-78.0 work with my local installation of Java 11.

Below, I will list details of my failed installation, which may help people point out what I need to do in order to get it right.

Thank you!

**Comment by SchwarzEM** [comment]
Details of my (failed) installation of InterProScan 5.42-78.0:

cd $HOME/InterPro ;

# Most recent release, dated: 3/20/20, 7:41:00 AM
wget -q ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.42-78.0/interproscan-5.42-78.0-64-bit.tar.gz ;
wget -q ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.42-78.0/interproscan-5.42-78.0-64-bit.tar.gz.md5 ;
md5sum -c interproscan-5.42-78.0-64-bit.tar.gz.md5 1>interproscan-5.42-78.0-64-bit.tar.gz.md5.check.txt 2>test1.err ;

tar -pxvzf interproscan-5.42-78.0-64-bit.tar.gz ;

# This remains the most recent accompanying release, as of 3/26/2020 (it is web-dated 3/22/19, 8:00:00 PM).
wget -q ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/data/panther-data-14.1.tar.gz ;
wget -q ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/data/panther-data-14.1.tar.gz.md5 ;
md5sum -c panther-data-14.1.tar.gz.md5 1>panther-data-14.1.tar.gz.md5.check.txt 2>test2.err ;

mv -i panther-data-14.1.tar.gz $HOME/InterPro/interproscan-5.42-78.0/data ;

cd $HOME/InterPro/interproscan-5.42-78.0/data ;

tar -pxvzf panther-data-14.1.tar.gz ;

# Get Java 11 from download.java.net:
cd $HOME/TGZ ;
wget -q https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz ;

cd $HOME/src/unpack ;
zcat $HOME/TGZ/openjdk-11+28_linux-x64_bin.tar.gz | tar xf - ;
mv -i jdk-11 $HOME/src ;

cd $HOME/analysis ;
# Set up what I hope will be usable Java 11 environment for InterProScan:
JAVA_VERSION="11" ;
export JAVA_VERSION ;

JAVA_HOME="$HOME/src/jdk-11" ;
export JAVA_HOME ;

LD_LIBRARY_PATH="$HOME/src/jdk-11/lib:$LD_LIBRARY_PATH" ;
export LD_LIBRARY_PATH ;

PATH="$HOME/src/jdk-11/bin:$PATH" ;
export PATH ;

# Finally, try to *run* InterProScan.  Note that essentially this command worked perfectly for me back in 2019 with a slightly older version of InterProScan (5.35-74.0) on a different cluster (NSF XSEDE Bridges).
$HOME/InterPro/interproscan-5.42-78.0/interproscan.sh -cpu 7 -dp -iprlookup -goterms -i input.fa -b output.01 -T temp.01 ;

# this fails catastrophically with many Java exceptions

**Comment by SchwarzEM** [comment]
I have found a method for providing Java 11 that seems to work for InterProScan 5.42-78.0, and which I'll therefore provide here as a specified method that other people who are having this problem can also use.

**Before running batch jobs:**
`conda create -n openjdk_11.0.1 openjdk=11.0.1 ;`

**As part of an InterProScan batch job:**
.```
 $HOME/anaconda2/etc/profile.d/conda.sh ;
conda activate openjdk_11.0.1 ;
$HOME/InterPro/interproscan-5.42-78.0/interproscan.sh [etc. etc. etc.] ;
conda deactivate ;
```

This is working about 35% of the time.  About 65% of the time, I still get a spectacular crash, but I believe these crashes are being produced by flakey disk management of the computing cluster that I'm having to use.

In particular, for a lucky and random 35% of cases, when I start the batch job, it will actually 'catch', run without a loud crash, and complete a job apparently successfully.  Before a friend of mine suggested this conda-based strategy for providing Java 11, my success rate had been 0%.

**Comment by vragh** [comment]
@SchwarzEM thank you for documenting this.
