### ISSUE TITLE
Unable to find original database file: work/template/interpro.zip

### ISSUE THREAD

**Issue by esud1** [ebi-pf-team/interproscan#145]
Hi, 

I am trying to run `interproscan` example, but was given this error notice: 

```
08/05/2020 11:26:46:441 Welcome to InterProScan-5.41-78.0
08/05/2020 11:26:46:442 Running InterProScan v5 in STANDALONE mode... on Linux
FATAL: uk.ac.ebi.interpro.scan.jms.activemq.CleanRunDatabase - Unable to find original database file: work/template/interpro.zip
Exception in thread "Thread-4" java.lang.IllegalStateException: Unable to find original database file
        at uk.ac.ebi.interpro.scan.jms.activemq.CleanRunDatabase.cleanInstalledDatabase(CleanRunDatabase.java:101)
        at uk.ac.ebi.interpro.scan.jms.activemq.CleanRunDatabase.run(CleanRunDatabase.java:76)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

I had a look at the work folder, but could not find the interpro.zip 
The md5sum check showed that the download was OK, so I am not sure what was the problem. 

I am running the program on Ubuntu 20.04 in the WSL

**Comment by gsn7** [comment]
We test InterProScan on all the recent ubuntu releases including 20.04 and everything works fine. we have not tested InterProScan on WSL, previously users have reported errors. It appears there is a path problem with your setup. 

what is you command  you use to run interproscan?
what is the output when you issue the command?
ls -l work/template/

You should also use the latest InterProScan release InterProScan-5.44-79.0.
