### ISSUE TITLE
Refuses to run if home directory not accessible

### ISSUE THREAD

**Issue by wmnwmn** [ebi-pf-team/interproscan#15]
We're trying to set up interproscan to run as a web service, under the www user, which has no home directory. Unfortunately the program throws and exception and exits immediately when it is not able to create the hidden .interproscan-5 directory...even though only an empty file is put into it in our usage. So my question: is this directory really so essential that the program has to have a hard block on it?

**Comment by gsn7** [comment]
we will review that behaviour in the next release.
to get around the problem you can provide -Duser.home=</wwwuser/writable/directory/>  in the java command in interproscan.sh file
