### ISSUE TITLE
 libdw.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kentnf** [ebi-pf-team/interproscan#156]
Hi, 

I use the latest version of InterProscan, it has error info:
Error output from binary:
bin/blast/ncbi-blast-2.9.0+/rpsbproc: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory
It seems that the error is due to the missing library libdw.so.1, but I can not find the method to install this library.  

the command is : interproscan.sh -goterms -dp -i test.fa -f XML
the system is: ubuntu 18.04 LTS

**Comment by tgrego** [comment]
Hello @kentnf 
In ubuntu/debian this library is provided by the package libdw1.
You can install it running: apt-get install libdw1
