### ISSUE TITLE
issue with the latest version 5.20

### ISSUE THREAD

**Issue by scienceforever** [ebi-pf-team/interproscan#16]
Hello, 

while 5.19 works fine, 5.20 throws the following error on 2 different 64bit Linux systems:

bin/sfld/sfld_postprocess: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/sfld/sfld_postprocess)

At the same time, libc6 is updated to the latest on both of the 2 machines. 

Thanks

**Comment by scienceforever** [comment]
P.S. On the system:

3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux
java version "1.8.0_91"
This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
Python 2.7.10 :: Anaconda 2.3.0 (64-bit)

**Comment by scienceforever** [comment]
P.P.S. The second system:

2.6.32-504.1.3.el6.x86_64
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
Python 2.7.10

**Comment by fnollet** [comment]
Same problem here.

This binary is not compatible with our RHEL 6.x systems anymore. Can we recompile this binary separately or can we have a fix for this?

Thanks
Filip Nollet

**Comment by gsn7** [comment]
we have a binary that runs on older linux systems such as redhat 6.x.
copy the files in ftp://ftp.ebi.ac.uk/pub/databases/interpro/iprscan/5/bin/sfld_binary.zip into bin/sfld

**Comment by fnollet** [comment]
Works perfect! Thx!
