### ISSUE TITLE
Fill empty/blank cells in TSV output with "NA"

### ISSUE THREAD

**Issue by vragh** [ebi-pf-team/interproscan#161]
Dear InterProsScan team,

Thank you for the great work put into maintaining `InterProScan`!

I have a question regarding how `InterProScan` formats its TSV output. As it stands, cells with no data are left blank. This leads to output that looks like this, for example:

```
PROT1    mymd512345    blah    blah    blah
PROT2    mymd512345    blah    blah
```

This can become a pain to deal with downstream (e.g., importing into a data science environment for analysis).

I'd like to know if it is it possible for the end user to configure `InterProScan` to output TSVs with `NA`s or another optional `NA-string` for cells that do not contain any data instead of the current blanks? (The solution--externally--is one `awk` command away, I believe?)

I apologize if this has been addressed before already (in which case I would be grateful for a link to the relevant documentation).

Best regards!

**Comment by gsn7** [comment]
currently its not possible to configure tsv output to deal with empty columns. but we will review this and come up with some solution

**Comment by vragh** [comment]
> currently its not possible to configure tsv output to deal with empty columns. but we will review this and come up with some solution

Thank you, that would be great! It doesn't necessarily have to be integrated **into** `InterProScan`. You could just ship a solution as an auxiliary script, e.g., [the way the Trinity RNA-seq assembler does](https://github.com/trinityrnaseq/trinityrnaseq/tree/master/util).

In the spirit of being helpful, here's what I've done (in case some user stumbles upon this in the future): presuming the `InterProScan` TSVs are located at some directory `/my/dir` and are named `<something>_interpro.tsv`, invoking the script below (having saved it as `myscript.bash`; invoke as `./myscript.bash /my/dir`) will create new TSVs (in the same directory as the input TSVs) named `<something>_interpro_fixed.tsv`. These files will contain `NA`s in place of blank cells.

```
#!/bin/bash

for IPSFILE in $1/*_interpro.tsv;
do

awk -F"\t" -v OFS="\t" '{
       for (i=1;i<=15;i++) {
         if ($i == "") $i="NA"
       }
       print $0
 }' ${IPSFILE} > $1/$(basename ${IPSFILE} .tsv)_fixed.tsv;

done
```

**Comment by gsn7** [comment]
the blanks at the end of the tsv are now replaced with a '-'

**Comment by vragh** [comment]
@gsn7 is this as of `interproscan-5.51-85.0`? Thank you for taking care of this!!
