### ISSUE TITLE
Make path to panther data an command line option

### ISSUE THREAD

**Issue by jshleap** [ebi-pf-team/interproscan#162]
hello, I would like to suggest that the panther data be optional as a command line argument. This will allow users that do not have writing privileges to interproscan home, provide their own version of panther data.
Best

**Comment by gsn7** [comment]
you can use ~/.interproscan-5/interproscan.properties and put the panther data properties in there

**Comment by jshleap** [comment]
Thanks... I though the properties was in the bundle's path.
Best

**Comment by gsn7** [comment]
the default properties file is interproscan.properties in the installation directory, but InterProScan will also look at properties defined in ${user.home}/.interproscan-5/interproscan.properties if the file exists
