### ISSUE TITLE
hmmer3 and properties

### ISSUE THREAD

**Issue by Juke34** [ebi-pf-team/interproscan#164]
In the properties file you set two hmmer3 version. Do we really need both of them?
Or using 3.3 for both of them is fine? 
If both are needed could you tell us why?

```
#hmmer 3
binary.hmmer3.path=${bin.directory}/hmmer/hmmer3/3.1b1
binary.hmmer3.hmmscan.path=${bin.directory}/hmmer/hmmer3/3.1b1/hmmscan
binary.hmmer3.hmmsearch.path=${bin.directory}/hmmer/hmmer3/3.1b1/hmmsearch

binary.hmmer33.path=${bin.directory}/hmmer/hmmer3/3.3
binary.hmmer33.hmmscan.path=${bin.directory}/hmmer/hmmer3/3.3/hmmscan
binary.hmmer33.hmmsearch.path=${bin.directory}/hmmer/hmmer3/3.3/hmmsearch
```

**Comment by gsn7** [comment]
using 3.3 for both of them should be fine. we don't update an analysis to use a newer version until we have tested it against all sequences in UniProtKB. we don't expect significant  differences in results
