### ISSUE TITLE
Interproscan stuck

### ISSUE THREAD

**Issue by vcastroagudin** [ebi-pf-team/interproscan#165]
Hello,

I am trying to run Interproscan5 remotely through FUNANNOTATE, and it keeps getting stuck. In the log file, I get an error message which I am not sure how to interpret and troubleshoot it.

Any help is welcome! Thank you in advance.

[Calonectria_pseudonaviculata_CBS139395.proteins_1.txt](https://github.com/ebi-pf-team/interproscan/files/5247519/Calonectria_pseudonaviculata_CBS139395.proteins_1.txt)

Vanina

**Comment by gsn7** [comment]
hi Vanina, the error points to a missing library _libdw1_ . you can install this library as follows:
on ubuntu:
`sudo apt install libdw1 libdw-dev
on centos/redhat:`
`yum install libdw1 libdw-dev`

other distributions have similar commands
