### ISSUE TITLE
hmmer2 compilation - update documentation for multithreading

### ISSUE THREAD

**Issue by Juke34** [ebi-pf-team/interproscan#166]
Here https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries
you forgot to compile with multi-thread. 
It should be 
```
wget ftp://selab.janelia.org/pub/software/hmmer/2.3.2/hmmer-2.3.2.tar.gz
tar -xzvf hmmer-2.3.2.tar.gz
cd hmmer-2.3.2
./configure --enable-threads
make
make check
make install
```

otherwise we end up with such error:
```
FATAL: Posix threads support is not compiled into HMMER; --cpu doesn't have any effect
```

when calling `hmmpfam` with `--cpu 1`. Indeed `--cpu 1` is the default value for hmmpfam into the `interproscan.properties` you provide by default.

**Comment by gsn7** [comment]
thanks for the info, we will update the documentation
