### ISSUE TITLE
interproscan.sh: line 48: 268506 Killed              

### ISSUE THREAD

**Issue by dosshra** [ebi-pf-team/interproscan#174]
Hello
I am running interproscan on Linux desktop  with 8 cores and 7GB ram. I run the following command:

`./interproscan.sh -i ~/Dropbox/G305/flank_contigs.fas  -b ~/testprot   -dra`

I get this output:
"./interproscan.sh: line 43: python: command not found
30/11/2020 08:46:01:713 Welcome to InterProScan-5.47-82.0
30/11/2020 08:46:01:716 Running InterProScan v5 in STANDALONE mode... on Linux
30/11/2020 08:46:15:705 Loading file /home/hanan/Dropbox/G305/flank_contigs.fas
30/11/2020 08:46:15:708 Running the following analyses:
[CDD-3.17,Coils-2.2.1,Gene3D-4.2.0,Hamap-2020_01,MobiDBLite-2.0,PANTHER-15.0,Pfam-33.1,PIRSF-3.10,PRINTS-42.0,ProSitePatterns-2019_11,ProSiteProfiles-2019_11,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
./interproscan.sh: line 48: 268506 Killed                  "$JAVA" -XX:+UseParallelGC -XX:ParallelGCThreads=4 -Xms1028M -Xmx4072M -jar interproscan-5.jar $@ -u $USER_DIR"

The size of the protein fasta file is 4Mb.
I have set Xmx4072M in ./interproscan.sh and max number of workers=4 in the properties file. 
When I run the test file, I get the results.
Thank you.

**Comment by gsn7** [comment]
there is an error message above saying "python: command not found". 
do you have python3 on your machine? the following command should verify it:
`python3 --version`
If you don't have python3 then install it first.
then try the command:
`./interproscan.sh -i test_all_appl.fasta  -f tsv -dp_-b ~/testprot`

if this works you should be able to run on your input sequences without problems. I would change your command to explicitly add the max number of workers on the command line with the --cpu option and also as it seems your input sequences are translated proteins use -dp to disable using the precalculated match lookup:
`./interproscan.sh -i ~/Dropbox/G305/flank_contigs.fas -b ~/testprot -dra -dp --cpu 4`
