### ISSUE TITLE
Java version-check fails if OpenJDK detects _JAVA_OPTIONS

### ISSUE THREAD

**Issue by brandoninvergo** [ebi-pf-team/interproscan#182]
Various Java behaviors can be tweaked by setting the `_JAVA_OPTIONS` environment variable (e.g. for graphical options). These can be set system-wide in the `/etc/profile.d/jre.sh` file. At least under OpenJDK (any version), running the `java` command when `_JAVA_OPTIONS` is set causes it to output to `stdout`, before anything else, something like the following:

    Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel

Because this is printed out before any other output, this breaks the version checking in `interproscan.sh`: 

```
$ java -Xms32M -Xmx32M -version 2>&1
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
$ ./interproscan.sh -i test_all_appl.fasta -f tsv
Java version 11 is required to run InterProScan.
Detected version
Please install the correct version.
```

Even if you try to temporarily clear it out, e.g. a simple `_JAVA_OPTIONS= ./interproscan.sh ...`, the command still spits out a "Picked up _JAVA_OPTIONS" message.

I would suggest making the `interproscan.sh` script robust against this by changing line 32 from:

    JAVA_VERSION=$("$JAVA" -Xms32M -Xmx32M -version 2>&1 | head -n 1 | awk -F '"' '{print $2}' )

To perhaps something like:

    JAVA_VERSION=$("$JAVA" -Xms32M -Xmx32M -version 2>&1 | sed -n '/version/p' | awk -F '"' '{print $2}' )

or

    JAVA_VERSION=$("$JAVA" -Xms32M -Xmx32M -version 2>&1 | awk -F '"' '{if ($0 ~ /version/){print $2}}' )

I haven't tested these with other Java implementations as I only have OpenJDK available.

**Comment by gsn7** [comment]
thanks for providing this detailed help. we will definitely test it on more java builds and use it in the next release
