### ISSUE TITLE
"Completed indexing the hmm models." but it really didn't

### ISSUE THREAD

**Issue by dence** [ebi-pf-team/interproscan#186]
Hi, I'm working with my sys admins to get interposcan 5.50-84.0 working on our compute cluster. After they had installed it in a new module, I tried running it from a command-line and saw this error, followed by the interproscan usage statement. 

It looks like those indices of the ".hmm" files were not made during installation. I think interproscan tries to make the indices and reports "Completed indexing the hmm models", but because of my permissions, the indices aren't actually made. 

I think interproscan should check for the h3i files, or the check that is happening isn't working. 

Thanks,
Daniel

----------------------------------------------------------------------------------
module load iprscan/5.50-84.0
interproscan.sh -h
Checking any hmm models that need indexing ... this may take a few minutes
failed to open SSI index data/gene3d/4.2.0/gene3d_main.hmm.h3i
failed to open SSI index data/hamap/2020_05/hamap.hmm.lib.h3i
failed to open SSI index data/panther/15.0/panther.hmm.h3i
failed to open SSI index data/pfam/33.1/pfam_a.hmm.h3i
failed to open SSI index data/pirsf/3.10/sf_hmm_all.h3i

Error: failed to open SSI index data/sfld/4/sfld.hmm.h3i

Error: failed to open SSI index data/superfamily/1.75/hmmlib_1.75.h3i
failed to open SSI index data/tigrfam/15.0/TIGRFAMs_HMM.LIB.h3i
Completed indexing the hmm models.
usage: java -XX:+UseParallelGC -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Xms128M
            -Xmx2048M -jar interproscan-5.jar
----------------------------------------------------------------------------------

**Comment by gsn7** [comment]
Before you run interproscan for the first time, the person who has permissions should run the command:
`python3 initial_setup.py`
otherwise it will fail. see https://interproscan-docs.readthedocs.io/en/latest/HowToDownload.html#index-hmm-models

we will add more checks to make sure the program exits if there are no indices.
