### ISSUE TITLE
Interproscan with TORQUE?

### ISSUE THREAD

**Issue by mcsimenc** [ebi-pf-team/interproscan#19]
I want to use InterProScan 5.21-60.0 on our cluster which is running TORQUE. I have seen these instructions:

https://freelancingscience.com/2008/07/10/configuring-torque-and-interproscan/
ftp://ftp.hgc.jp/pub/mirror/ebi/software/iprscan/4/FAQs.html

But they do not seem applicable to the version I have. Can I set up InterProScan 5.21-60.0 with TORQUE?

Thanks!
Matt

**Comment by gsn7** [comment]
You can setup Interproscan5 with TORQUE, other users have previously mentioned this. We have not tested it though as we don't have a TORQUE cluster to test on. Have you tried to create a simple job script like the following and run it?

#!/bin/bash 
#PBS -l nodes=1:ppn=8
#PBS -M example@example.com
#PBS -m abe
#PBS -N interproscan5Job 
#PBS -o /-path/to/output-file-name
#PBS -j oe
/path/to/interproscan.sh -i /path/to/test_all_appl.fasta -b /path/to/test_all_appl.result

**Comment by mifraser** [comment]
Hi,

This is a general error that is not specific to PBS/Torque.

The binaries that we distribute with InterProScan should work on most linux systems. However, in some cases they may not work on a particular system. If this happens you need to compile the binary on your own system in order for it to work.

In this case you'll need the instructions for recompiling sfld_preprocess/sfld_postprocess binaries documented at the bottom of https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries

Hope that helps?

Matt
