### ISSUE TITLE
Java version 11 is required to run InterProScan. Detected version  Please install the correct version

### ISSUE THREAD

**Issue by gaoxiangcao** [ebi-pf-team/interproscan#198]
when i run ./interproscan.sh -i test_all_appl.fasta  -f tsv -gotrems -T /tmp /newlustre/home/caogx/interproscan/interproscan-5.50-84.0/test.tsv, it shows that 
Java version 11 is required to run InterProScan.
Detected version 
Please install the correct version
but i chek my java version ,i think it's right.it shows that
[caogx@mu02 cgx-jobs]$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
then ,what's wrong  with my java and how can i get the right runing. Thanks for your reply.

**Comment by gsn7** [comment]
we have updated the java version detection in the latest version InterProScan 5.51-85.0. so update to v5.51-85.0
