### ISSUE TITLE
how to update to pfam 34.0?

### ISSUE THREAD

**Issue by JWDebler** [ebi-pf-team/interproscan#201]
Hi,
I am running 5.51-85.0 which comes with pfam 33.1.
Can I manually update my install to pfam 34.0?

Not sure which files to get and what to do with them though: http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam34.0/

Cheers
J

**Comment by gsn7** [comment]
It is not possible to update to pfam 34.0 in InterProScan-5.51-85.0. When  a member database like Pfam releases a new version, it is first integrated into InterPro and thereafter it is available in InterProScan.  InterProScan-5.51-85.0 includes a subset of InterPro data that references pfam 33.1 data.

Pfam 34.0 should be available in the next release
