### ISSUE TITLE
No EC codes in KEGG pathway identifier

### ISSUE THREAD

**Issue by a-ag** [ebi-pf-team/interproscan#202]
Hi,

I am running interproscan to get pathway data on protein sequences, but I don't see any EC codes attached with KEGG pathway identifier. I remember that Interproscan provided EC codes in an Interproscan4 version. Previously, in the interproscan json output, the pathwayXRefs for KEGG mentioned the id as: `00240+2.7.7.7` and now it only has `00240`.

Is this something that interproscan does not provide anymore or is there an argument/flag that needs to be passed for EC codes to be available?

Cheers!

**Comment by gsn7** [comment]
You are right the pathwayXRefs for KEGG mentioned the id such as: 00240+2.7.7.7. The change to 00240 was a bug. Unfortunately, we have discontinued providing KEGG pathways due to licencing restrictions. So, latest releases, which could have fixed this problem don't have KEGG pathways.
