### ISSUE TITLE
Problem with XSD schema

### ISSUE THREAD

**Issue by duboism** [ebi-pf-team/interproscan#209]
We are evaluating `interproscan-5.51-85.0` but we have some issues with the XSD schema:
  - according to [the doc](https://interproscan-docs.readthedocs.io/en/latest/OutputFormats.html#the-xml-schema-definition) we must use [interproscan-model-3.0.xsd](http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/schemas/interproscan-model-3.0.xsd) but it doesn't work:
    ```python
    >>> import xmlschema 
    >>> d = xmlschema.to_dict("36.xml", "interproscan-model-3.0.xsd")
    xmlschema.validators.exceptions.XMLSchemaChildrenValidationError: failed validating <Element '{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}hmmer3-site' at 0x7fed0cb2df90> with XsdGroup(model='sequence', occurs=[1, 1]):
    
    Reason: Unexpected child with tag 'tns:group' at position 2.
    
    Schema:

      <xs:complexType xmlns:xs="http://www.w3.org/2001/XMLSchema" name="Hmmer3SiteType">
          <xs:complexContent>
              <xs:extension base="tns:HmmerSiteType">
                  <xs:sequence />
              </xs:extension>
          </xs:complexContent>
      </xs:complexType>

    Instance:

      <hmmer3-site xmlns="http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5" description=" Binds [4Fe-4S]-AdoMet cluster" numLocations="3">
        <site-locations>
          <site-location residue="C" start="196" end="196" />
          <site-location residue="C" start="199" end="199" />
          <site-location residue="C" start="192" end="192" />
        </site-locations>
        <group>0</group>
        <hmmEnd>0</hmmEnd>
        <hmmStart>0</hmmStart>
      </hmmer3-site>
    
    Path: /protein-matches/protein[32]/matches/hmmer3-match-with-sites/locations/hmmer3-location-with-sites/sites/hmmer3-site
    ```
    This seems to indicate that the file is outdated.

  - we noticed that [the FTP directory](http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/schemas/) contains 2 identical files named `interproscan-model-3.1.xsd` and `interproscan-model-4.0.xsd` but they don't work either:
    ```python
    >>> import xmlschema
    >>> d = xmlschema.to_dict("36.xml", "interproscan-model-4.0.xsd")
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/xmlschema/documents.py", line 32, in get_context
        schema, locations = fetch_schema_locations(source, locations, base_url=base_url)
      File "/usr/lib/python3.9/site-packages/xmlschema/resources.py", line 197, in fetch_schema_locations
        raise XMLSchemaValueError(msg.format(source))
    xmlschema.exceptions.XMLSchemaValueError: the XML data resource XMLResource(tag='{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}protein-matches', basename='36.xml') does not contain any schema location hint.
    ```
    This seems to indicate that the schema is broken.

Can somebody help ?

**Comment by duboism** [comment]
I corrected a few errors in the issue.

**Comment by duboism** [comment]
Any idea ?

**Comment by tgrego** [comment]
From InterProScan 5 from version 5.51-85.0 onwards [interproscan-model-4.5.xsd](http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/schemas/interproscan-model-4.5.xsd) is recommended.

Can you please try that and see if it works?
If so I will update the documentation accordingly.

**Comment by duboism** [comment]
Hello,

We are currently testing the new XSD file with `interproscan-5.52-86.0`. I will keep you in touch.

**Comment by duboism** [comment]
We have tested [interproscan-model-4.5.xsd](http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/schemas/interproscan-model-4.5.xsd) with `interproscan-5.52-86.0` and it worked (note that we haven't tested `interproscan-5.51-85.0`). I think you can update the doc and close the issue.

**Comment by tgrego** [comment]
Thanks for reporting the issue and confirming it is working.
