### ISSUE TITLE
Build custom iprmatch db

### ISSUE THREAD

**Issue by hyphaltip** [ebi-pf-team/interproscan#21]
Is it possible to build a custom interpro match database for local service to provide annotations already run (but not in the IPR master database). I have the generated XML locally for new proteomes not in uniprot but need to re-search these after improvements to the genome annotation and gene models and would prefer to not have the expense of re-running all.

**Comment by gsn7** [comment]
we have never built the lookup match service from the output xml. but am sure it can be done if you have time to invest in refactoring the code that handles this part. 
how many sequences are in these proteomes? 
i would guess it would take less time (man-hours) to re-run than to build the custom lookup.
