### ISSUE TITLE
How to map HMM profile name to interpro entry?

### ISSUE THREAD

**Issue by xiekunwhy** [ebi-pf-team/interproscan#210]
Hi,

Can some one tell me how to map hmm profile name to interpro entry?

For example, 3pifB07-i2 in gene3d_main.hmm match which interpro entry? MF_00001 in hamap/2020_05/hamap.hmm.lib match which interpro entry? PTHR31755.orig.30.pir in panther/15.0/panther.hmm match which interpro entry? 0034782 in superfamily/1.75/hmmlib_1.75 match which interpro entry? ...

Is there a table to list these exactly mapping infomation?

Best,
Kun

**Comment by matthiasblum** [comment]
Hi,

The mapping between profiles and InterPro entries is done internally in InterProScan.

If you want to do it yourself, you need to convert the HMM profile name to the signature accession. For most member databases, the name of the model _is_ the accession for the signature, but there are exceptions, e.g.

- Gene3D (`data/gene3d/4.3.0/gene3d_main.hmm`): use the mapping file `data/gene3d/4.3.0/model_to_family_map.tsv` to look-up models (e.g. `3pifB07-i2` -> `6.10.140.950`, so the accession is `G3DSA:6.10.140.950`)
- PANTHER (`data/panther/15.0/panther.hmm`): if a profile is named `PTHR33671.orig.30.pir`, its accession is `PTHR33671`. If a profile is named `PTHR33671.SF11.pir`, its accession is `PTHR33671:SF11`
- SUPERFAMILY (`data/superfamily/1.75/hmmlib_1.75`): use the mapping file `data/superfamily/1.75/model.tab` to look-up models (e.g. model `0034782` -> `54076`, so the accession is `SSF54076`).

Finally, from the signature accession, you can get the InterPro entry by querying our REST API.

For instance, for the SUPERFAMILY `SSF54076`, the query `https://www.ebi.ac.uk/interpro/api/entry/ssf/SSF54076/` returns:
```json
{
    "metadata": {
        "accession": "SSF54076",
        "entry_id": null,
        "type": "homologous_superfamily",
        "go_terms": null,
        "source_database": "ssf",
        "member_databases": null,
        "integrated": "IPR036816",
        "hierarchy": null,
        "name": {
            "name": "RNase A-like",
            "short": null
        },
        "description": null,
        "wikipedia": null,
        "literature": null,
        "overlaps_with": null,
        "counters": {
            "domain_architectures": 0,
            "matches": 3388,
            "proteins": 3347,
            "proteomes": 215,
            "structures": 448,
            "taxa": 668,
            "interactions": 0,
            "pathways": 0,
            "sets": 0,
            "structural_models": {
                "trRosetta": 0,
                "full_length": 0
            }
        },
        "entry_annotations": [
            "hmm",
            "logo"
        ],
        "cross_references": {}
    }
}
```

As you can see, the InterPro entry is `IPR036816`.
