### ISSUE TITLE
Unexpected EOF when untar 5.52-86.0

### ISSUE THREAD

**Issue by davised** [ebi-pf-team/interproscan#213]
Hi,

I checked the integrity of the tar.gz:

```
$ md5sum -c interproscan-5.52-86.0-64-bit.tar.gz.md5
interproscan-5.52-86.0-64-bit.tar.gz: OK
md5sum -c interproscan-5.52-86.0-64-bit.tar.gz.md5  22.68s user 4.17s system 99% cpu 26.853 total
```

When I untar:

```
...
interproscan-5.52-86.0/data/gene3d/4.3.0/gene3d_main.hmm
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
tar -pxvzf interproscan-5.52-86.0-64-bit.tar.gz  1.04s user 31.52s system 20% cpu 2:35.89 total
```

Any ideas on what might be going on?

**Comment by tgrego** [comment]
Hi,

I have no issues untaring the file...
not sure what can be going on.

Can you let me know your OS and the exact command used so that I can try and replicate that?

**Comment by davised** [comment]
I'm on centos7 and I ran `tar -pxvzf interproscan-5.52-86.0-64-bit.tar.gz` as instructed in the install directions. I've downloaded several versions before without issue...

Maybe I'll try redownloading despite the md5 showing OK.

**Comment by tgrego** [comment]
I tried on a centos7 system and could not replicate.
please do try redownloading.

**Comment by davised** [comment]
I redownloaded, got the OK again on md5sum, and now it's working. Very strange, thanks for testing for me!
