### ISSUE TITLE
InterProScan-5.52-86.0 analysis failed. Exception thrown by StandaloneBlackBoxMaster

### ISSUE THREAD

**Issue by sanaek** [ebi-pf-team/interproscan#217]
Hello, Im trying to run InterProScan-5.52-86.0 with 33,000 protein sequences in linux 64bit, JAVA-11, python 3.7. I get the following error: 

![Captura de Pantalla 2021-07-23 a la(s) 09 21 48](https://user-images.githubusercontent.com/72226418/126799094-fe113087-b62b-4a92-ab9e-0c839ab676ea.png)

I split the fasta file into 1000 seqs long, and the same error occurs. I ran the the test with test_all_appl.fasta and finished with no problems. 

Can anyone help me with this?

Thanks in advance

**Comment by matthiasblum** [comment]
Hi,

The error occurs because a library that is required by PROSITE is missing.

On Ubuntu, you can install this library with the following command:

```
sudo apt install libpcre3-dev
```

Kind regards
