### ISSUE TITLE
allow symlinking interproscan.sh

### ISSUE THREAD

**Issue by epruesse** [ebi-pf-team/interproscan#22]
Posting as a ticket as I'm not sure PRs on this repo are easily mergeable for you. 

It would be useful if `interproscan.sh` could be symlinked into the path. However, it currently finds its location with `cd $(dirname "$0")`, which does not traverse symlinks. Replacing the line with the below code fixes this (tediously avoiding GNU readlink's `-f` option not available everywhere). 

```
INSTALL_DIR="${BASH_SOURCE[0]}"
while [ -h "$INSTALL_DIR" ]; do
  cd "$(dirname "$INSTALL_DIR")"
  INSTALL_DIR="$(readlink "$(basename "$INSTALL_DIR")")"
done
cd "$(dirname "$INSTALL_DIR")"
INSTALL_DIR="$(pwd)/"
```

**Comment by gsn7** [comment]
thanks. we will test this script.

**Comment by mifraser** [comment]
Thanks for that! This should be in the next release of InterProScan (5.24-63.0).

**Comment by epruesse** [comment]
Thanks!
