### ISSUE TITLE
How to extract a unique set of domain annotations?

### ISSUE THREAD

**Issue by vragh** [ebi-pf-team/interproscan#220]
Dear team `InterProScan`,

I hope you're all doing well. Thank you for the awesome tool (and website + documentation + support)!!

Say I ran `InterProScan` for a protein against `Pfam` and `CDD`. Let's say I also got overlapping annotations like this:

```
seq    len    src    annot    start    stop
prot1    100   Pfam    dom_x    20    30
prot1    100   CDD    dom_y    22    33
```

Is there an easy way to de-duplicate these? For instance, I'd probably like to hold on to `dom_y` only, because it covers the same positions and happens to be a bit longer.

**Comment by matthiasblum** [comment]
Hi @vragh,

InterProScan does not provide an option to merge overlapping domains. Using `dom y` as you mentioned would be perfectly reasonable.

On the InterPro website, we merge domains from member database signatures integrated in the same InterPro entry, so we can represent the annotation at the entry level.

For instance, both `PF00306` and `cd18113` (integrated in `IPR000793`) match `A0A320` (372-496 and 376-501, respectively). To represent `IPR000793`, we merge these two domains into one (372-501):

![image](https://user-images.githubusercontent.com/2097501/128713960-96e8ce79-225a-4fe2-a3cc-2a8e6652bd6e.png)
(Screenshot from https://www.ebi.ac.uk/interpro/protein/UniProt/A0A320/)

**Comment by vragh** [comment]
@matthiasblum ,

Thanks for clarifying that for me!!

Would there be any dangers in me attempting a merge manually? (Like the one you've illustrated here)

Those overlapping annotations in the example were merged because an expert curator went over this, right? I presume this is not something I should attempt to replicate with a cheesy script of my own?

Additionally, what are your thoughts on mixing and matching annotations from various databases? For instance, if I were to have a `dom_z` from `SMART` covering residues `60-80`, would it be alright to go ahead with that one and `dom_y` from `CDD` as the final annotations for the sequence? Or is there some arcane requirement that all annotations on the sequence must be sourced from one database only?

**Comment by matthiasblum** [comment]
In my example, both `PF00306` and `cd18113` are integrated in `IPR000793` (i.e. an expert curator considered after evaluation, that these two profiles represent the same domain). This is why we are "merging" the annotations, and we are only doing it to simplify visual representation.

If InterProScan yields two annotations from different profiles (e.g. `dom_x` from Pfam, and `dom_y` from CDD), and if these two profiles are integrated in the same InterPro entry, then yes, it is reasonable to "merge" the annotations and use the InterPro accession to refer to this domain.

However, if the two profiles do not belong to the same InterPro entry, curators may have decided that these two profiles do not actually represent the same domain or the same family. In this case, I would recommend against merging the annotations.

**Comment by vragh** [comment]
Hi @matthiasblum ,

Apologies for the late reply.

Thank you for clarifying that. I think I'll refrain from merging domains at all then.

I'd like your input on one last source of confusion: would it be inappropriate to mix and match domain sources like this:

```
Seq1 --------[DOM1_from_CDD]------------------------------------------
Seq1 ------------------------------------------[DOM2_from_Pfam]--------

##########Final set of annotations for Seq1############
Seq1 --------[DOM1_from_CDD]--------[DOM2_from_Pfam]--------
```

I'm actually asking this because there's a well-known sequence from _Drosophila melanogaster_ ([`O61735` from `UniProt`, actually](https://www.uniprot.org/uniprot/O61735)) that is supposed to have the following domain structure: 
```
----[BHLH]----[PAS]----[PAS]----
```

But if you try and annotate that sequence with `Pfam`, you get:
```
----[BHLH]------------[PAS]----
```

But `SMART` (for instance) annotates all three domains. So my question in this case to you is whether I can sort of "paint in" that missing domain from `SMART` but just go with the `Pfam` domains otherwise.

**Comment by matthiasblum** [comment]
Hi @vragh,

In the case of `O61735`, there is only one `PAS` domain reported by Pfam (`PF14598`) most likely because the second one has been filtered out due to its score. 

It would not be incorrect or inappropriate to _pick 'n' mix_ annotations from different sources, but less consistent so maybe more prone to misunderstandings.

Finally, one can also use InterPro entries to circumvent this issue and describe a domain architecture:
* `IPR011598` integrates signatures from various sources annotating the `bHLH` domain
* `IPR000014` integrates signatures from various sources annotating both `PAS` domains.

Therefore, we can describe the domain organisation like this:
```
[bHLH:IPR011598]---[PAS:IPR000014]---[PAS:IPR000014]
```

**Comment by vragh** [comment]
Hi @matthiasblum ,

Many thanks for your inputs and suggestions!! That's solved my problem.
