### ISSUE TITLE
Error: Failed to open binary auxfiles for data/panther/15.0/panther.hmm: use hmmpress first

### ISSUE THREAD

**Issue by liaochenlanruo** [ebi-pf-team/interproscan#221]
The error happened when running the example "./interproscan.sh -i test_all_appl.fasta -f tsv -dp". Anyone who knows how to deal with it?

**Comment by matthiasblum** [comment]
Hi @liaochenlanruo ,

Normally, when running `./interproscan.sh`, a Python script checks if any HMM profile database should be "pressed" (binary compressed files are built).

Could you please check the following:

1. Do you have a file called `initial_setup.py` in the InterProScan directory?
2. If so, what is the output of running `python3 initial_setup.py`?

**Comment by liaochenlanruo** [comment]
Yes, I have the file. The output is showed as follows:

(base) [hualin@master interproscan-5.52-86.0]$ python3 initial_setup.py
Checking any hmm models that need indexing ... this may take a few minutes
SSI index file data/panther/15.0/panther.hmm.h3i already exists;
Delete old hmmpress indices first
Completed indexing the hmm models.

**Comment by matthiasblum** [comment]
According to the error, the `hmmpress` command failed because one file it is supposed to create already exists (`data/panther/15.0/panther.hmm.h3i`).

Please manually delete this file, and all the following files (if they exists):

- `data/panther/15.0/panther.hmm.h3m`
- `data/panther/15.0/panther.hmm.h3f`
- `data/panther/15.0/panther.hmm.h3p`

Then, next time you run `./interproscan.sh`, these files should be properly re-created.

**Comment by liaochenlanruo** [comment]
#### I deleted the files, and rerun ```./ interproscan.sh -i test_all_appl.fasta -f tsv -dp```, and get the following information:
- Checking any hmm models that need indexing ... this may take a few minutes
- Working...    bad file format in HMM file data/panther/15.0/panther.hmm
- Completed indexing the hmm models.
#### I think maybe the panther.hmm is incomplete, and checked the MD5 of the downloaded file interproscan-5.52-86.0-64-bit.tar.gz with ```md5sum -c interproscan-5.52-86.0-64-bit.tar.gz.md5``` and got "interproscan-5.52-86.0-64-bit.tar.gz: OK".
#### The file was extracted by ```tar -pxvzf interproscan-5.52-86.0-64-bit.tar.gz``` and got information that may be an error tip:
- tar: interproscan-5.52-86.0/data/panther/15.0/panther.hmm: Cannot write: Remote I/O error
- tar: Exiting with failure status due to previous errors

#### I am sure that I have the write permation by running ```ls -la```:
- drwxrwxr-x.  3 hualin hualin        185 Aug 11 21:48 .
- drwxrwxr-x. 13 hualin hualin        297 Jul 27 20:49 ..
- drwxrwxr-x.  7 hualin hualin       4096 Jun  2 23:08 interproscan-5.52-86.0
- -rw-rw-r--.  1 hualin hualin 7928212488 Jul 28 01:08 interproscan-5.52-86.0-64-bit.tar.gz
- -rw-rw-r--.  1 hualin hualin         71 Jul 29 14:57 interproscan-5.52-86.0-64-bit.tar.gz.md5

**Comment by matthiasblum** [comment]
Based on the error message (`Cannot write: Remote I/O error`), it seems to be more an issue with the disk (or file system) than with your permission.

Are you trying to extract the archive to a distributed file system? Can you try to extract the archive to a different location?

**Comment by liaochenlanruo** [comment]
Hi,
The error has been solved by ```chmod 777 interproscan-5.52-86.0-64-bit.tar.gz```, and the program ran successfully. Thanks a lot for your help!

**Comment by matthiasblum** [comment]
Excellent.

Closing this issue, if you have any further questions please feel free to submit a new issue.
