### ISSUE TITLE
Missing pathway and go annotation on first line annotated coil

### ISSUE THREAD

**Issue by JamesWZM** [ebi-pf-team/interproscan#227]
When I used the command below:

`interproscan.sh -i blast_result.fasta  -f tsv -goterms -pa -cpu 32`

The first line of my result file comes:

`YP_003240111.1  c99011fffae558f7c7d91c17c35cbb2b    644 Coils   Coil    Coil    583 603 -   T   06-09-2021  -   -`

It should have GO and pathway annotation on this line, even if it's empty. This raised an error when I tried to read it and only goes when it's on the first line.

Please check why could this happen.

**Comment by matthiasblum** [comment]
This match is a coiled coils prediction. 
GO terms and pathways are associated to InterPro entries, and because Coiled coils predictions are not integrated into InterPro, no GO terms or pathways are reported for such hits.
