### ISSUE TITLE
Interproscan on Bash on Windows

### ISSUE THREAD

**Issue by jflowers002** [ebi-pf-team/interproscan#23]
I have been trying to run Interproscan 5.22-61 in the bash terminal for a Bash on Windows installation, and I keep getting the following error:

Command: bin/gene3d/DomainFinder3 -l 5900 -e 0.001 -i /mnt/c/Users/jflowers/bin/interproscan-5.22-61.0/temp/SEA-JFLOWERS10_20170308_010158429_jixk//jobGene3d/000000000001_000000000002.input.ssf -o /mnt/c/Users/jflowers/bin/interproscan-5.22-61.0/temp/SEA-JFLOWERS10_20170308_010158429_jixk//jobGene3d/000000000001_000000000002.output.ssf
Error output from binary:
bin/gene3d/DomainFinder3: 1: bin/gene3d/DomainFinder3: Syntax error: "(" unexpected

I am not sure where this syntax error is coming from.  

Thanks,

Jason

**Comment by jflowers002** [comment]
Still no solution. It might just be that I am trying to run it on Bash on WIndows, and there is some compatibility issue.  Still do not understand why the test sequences provided by interproscan work though.

**Comment by gsn7** [comment]
We have not tested InterProScan on bash for windows. InterProScan is only supported on Linux systems. Its possible the test sequence works because the analysis is not done on your local system but rather it gets pre-calculated matches from the match lookup up server.

**Comment by jflowers002** [comment]
I ended up making my computer dual boot, and interproscan works fine on the linux partition on my sequences.  Therefore, it must be a Bash on Windows issue.  Thanks.
