### ISSUE TITLE
Cannot deserialize value of type `int` from String "Nter"

### ISSUE THREAD

**Issue by fedeserral** [ebi-pf-team/interproscan#230]
Hi! I have this issue when I run interproscan. I can´t find how to solved.

This is the whole issue:
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `int` from String "Nter": not a valid Integer value
 at [Source: (FileInputStream); line: 7666, column: 38] (through reference chain: java.util.LinkedHashMap["1313"]->uk.ac.ebi.interpro.scan.io.SimpleSequenceMatch["domainMatches"]->java.util.LinkedHashMap["PIRSR006246-5"]->java.util.ArrayList[0]->uk.ac.ebi.interpro.scan.io.SimpleDomainMatch["ruleSites"]->java.util.ArrayList[0]->uk.ac.ebi.interpro.scan.io.RuleSite["start"])

Thanks!

Regards

**Comment by IdoBar** [comment]
Hi, 
I had exactly the same issue.
Please note that disabling residue annotation with `-dra` didn't solve the problem and I had to exclude the PIRSR analysis completely with `-exclappl PIRSR`.
I hope this will get resolved soon.
Does this issue exist in previous releases as well or can I revert to an older version?

Thanks, Ido

**Comment by nikostr** [comment]
So this is the same issue as #219 - is the code presented in https://github.com/ebi-pf-team/interproscan/issues/219#issuecomment-899628387 a reasonable work-around? :)

**Comment by matthiasblum** [comment]
@nikostr Yes, the code at https://github.com/ebi-pf-team/interproscan/issues/219#issuecomment-899628387 can be used as a workaround. We are working on a PIRSR update (data + code fix). Hopefully, it will be included in the next release (scheduled for late February).
