### ISSUE TITLE
cite interproscan? If so, how?

### ISSUE THREAD

**Issue by dschwoerer** [ebi-pf-team/interproscan#234]
As I couldn't find anything in the documentation I have been wondering whether there is a recomended way how to cite this program.

I could only find:
>License
>
>The InterProScan software is distributed under the open source Apache License , as are the included scanning tools (except SignalP and TMHMM). Therefore, you do not need a special license for commercial use but please **cite the resource** and keep the Copyright statement with your installation.

which seems to imply you don't want to be cited in scientific publications ...

**Comment by tgrego** [comment]
Hi,
You're right that the interproscan documentation is missing that information... we do appreciate being cited so I'll look into adding it!
In the mean time you can check it on the interpro documentation here:
https://interpro-documentation.readthedocs.io/en/latest/citing.html

**Comment by dschwoerer** [comment]
Just wondering, wouldn't it make sense to keep the issue open until you added the documentation?

**Comment by matthiasblum** [comment]
The documentations have been updated: https://interproscan-docs.readthedocs.io/en/latest/Citing.html.
