### ISSUE TITLE
Moving InterProScan/data/ to a different drive than where the program is installed

### ISSUE THREAD

**Issue by eric-jm-lang** [ebi-pf-team/interproscan#237]
Hello,

I would like to have the content of InterProScan/data/ installed on a different drive than the core program is (I am working on a cluster). Is it possible to do that, or will it slow things down considerably?

If it is possible what is the best way to let the rest of the code know where the /data is? Would a symbolic link be ok?

Many thanks in advance!

**Comment by tgrego** [comment]
Hello,
That should not be a problem, if latency is low it should work fine.
You don't need a symbolic link, you you can edit the `interproscan.properties` file and update the `data.directory` property with the path you want to use.
