### ISSUE TITLE
SFLD crashes for some sequences

### ISSUE THREAD

**Issue by rattei** [ebi-pf-team/interproscan#24]
A recent run of interproscan against a proteome resulted in failure of approximately 5% of the sequences, although nothing was apparently wrong with them. One example is attached. A java exception is thrown pointing to SFLD. The error occurs with a freshly downloaded interproscan-5.22-61.0, using Oracle java 1.8.0_121.

commandline to reproduce:
/tmp/interproscan-5.22-61.0/interproscan.sh -i failing_sequence.fa --output-file failing_sequence.fa.xml --formats XML -dp -appl sfld

[failing_sequence.fa.zip](https://github.com/ebi-pf-team/interproscan/files/839578/failing_sequence.fa.zip)
[interproscan_out.txt](https://github.com/ebi-pf-team/interproscan/files/839579/interproscan_out.txt)

**Comment by rattei** [comment]
Thanks for your help!

Best,
Thomas Rattei

**Comment by rattei** [comment]
Just an additional observation. The error is restricted to situations in which the working directory is on a network share (nfs mount). Using a local directory or ramdisk for -T parameter prevents the problem. Maybe there is some check for filesystem metadata involved in sfld, which is not as quickly available as needed.

**Comment by gsn7** [comment]
uncomment the following line in interproscan.properties file
# nfs.delay.milliseconds=0

and experiment with different delay times and use the one that seems to work for your system.

**Comment by gsn7** [comment]
sfld issues are resolved in newer releases
