### ISSUE TITLE
Release notes for interproscan-5.54-87.0?

### ISSUE THREAD

**Issue by cmunk** [ebi-pf-team/interproscan#245]
I cannot find release notes for the newest interproscan version -- similar to : https://github.com/ebi-pf-team/interproscan-docs/blob/master/docs/ReleaseNotes.rst (which currently is for `5.53-87.0`

Could you provide if/what changes are since the last update?

**Comment by matthiasblum** [comment]
Hi,

Sorry for not providing release notes sooner. 

In December, a critical vulnerability has been detected in the Log4j library, which is one of InterProScan's dependencies.

Several of our users reported not being able to use InterProScan on their university/institute cluster as IT removed the local installation of InterProScan.

InterProScan `5.54-87.0` was release with a patched version of Log4j. There are no data changes in this release.

We updated the release notes: https://interproscan-docs.readthedocs.io/en/latest/ReleaseNotes.html.
