### ISSUE TITLE
problem when running the test data

### ISSUE THREAD

**Issue by shiyi-pan** [ebi-pf-team/interproscan#246]
Hi, I installed the interproscan but  hen running the sample data, there was no result for a long time.

First I downloaded the interproscan-5.47-82.0-64-bit.tar.gz and run the following command:

tar -zxvf interproscan-5.47-82.0-64-bit.tar.gz
cd interproscan-5.47-82.0-64
python3 initial_setup.py

The log is normal:

Checking any hmm models that need indexing ... this may take a few minutes
Working...    done.
Pressed and indexed 18259 HMMs (18259 names and 18259 accessions).
Models pressed into binary file:   data/pfam/33.1/pfam_a.hmm.h3m
SSI index for binary model file:   data/pfam/33.1/pfam_a.hmm.h3i
Profiles (MSV part) pressed into:  data/pfam/33.1/pfam_a.hmm.h3f
Profiles (remainder) pressed into: data/pfam/33.1/pfam_a.hmm.h3p
Working...    done.
Pressed and indexed 3283 HMMs (3283 names and 3283 accessions).
Models pressed into binary file:   data/pirsf/3.10/sf_hmm_all.h3m
SSI index for binary model file:   data/pirsf/3.10/sf_hmm_all.h3i
Profiles (MSV part) pressed into:  data/pirsf/3.10/sf_hmm_all.h3f
Profiles (remainder) pressed into: data/pirsf/3.10/sf_hmm_all.h3p
Working...    done.
Pressed and indexed 299 HMMs (299 names and 299 accessions).
Models pressed into binary file:   data/sfld/4/sfld.hmm.h3m
SSI index for binary model file:   data/sfld/4/sfld.hmm.h3i
Profiles (MSV part) pressed into:  data/sfld/4/sfld.hmm.h3f
Profiles (remainder) pressed into: data/sfld/4/sfld.hmm.h3p
Working...    done.
Pressed and indexed 15438 HMMs (15438 names and 15438 accessions).
Models pressed into binary file:   data/superfamily/1.75/hmmlib_1.75.h3m
SSI index for binary model file:   data/superfamily/1.75/hmmlib_1.75.h3i
Profiles (MSV part) pressed into:  data/superfamily/1.75/hmmlib_1.75.h3f
Profiles (remainder) pressed into: data/superfamily/1.75/hmmlib_1.75.h3p
Working...    done.
Pressed and indexed 4488 HMMs (4488 names and 4488 accessions).
Models pressed into binary file:   data/tigrfam/15.0/TIGRFAMs_HMM.LIB.h3m
SSI index for binary model file:   data/tigrfam/15.0/TIGRFAMs_HMM.LIB.h3i
Profiles (MSV part) pressed into:  data/tigrfam/15.0/TIGRFAMs_HMM.LIB.h3f
Profiles (remainder) pressed into: data/tigrfam/15.0/TIGRFAMs_HMM.LIB.h3p
Completed indexing the hmm models.

Then, I run the following two commands but both not return a result even I wait a long time :

./interproscan.sh

./interproscan.sh -i test_proteins.fasta -f tsv

I hope you help me fix this problem . thank you very much.

**Comment by shiyi-pan** [comment]
Hi, I think I know where the problem is.  My java and glibc are incompatible.
The interproscan needs  glibc 2.14 and java 11. When I set the glibc 2.14 into my environment variable, the "java -version" don't work. When I  don't set the glibc 2.14 into my environment variable, the following command will report an error:

./interproscan.sh -i test_proteins.fasta  -f tsv -dp

26/01/2022 14:00:16:522 Welcome to InterProScan-5.47-82.0
26/01/2022 14:00:16:530 Running InterProScan v5 in STANDALONE mode... on Linux
26/01/2022 14:00:41:171 Loading file /ds3512/home/panyp/NN1138-2/22.resistance_gene/00.install_RGAugury/interproscan-5.47-82.0/test_proteins.fasta
26/01/2022 14:00:41:172 Running the following analyses:
[CDD-3.17,Coils-2.2.1,Gene3D-4.2.0,Hamap-2020_01,MobiDBLite-2.0,PANTHER-15.0,Pfam-33.1,PIRSF-3.10,PRINTS-42.0,ProSitePatterns-2019_11,ProSiteProfiles-2019_11,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
2022-01-26 14:00:47,671 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:199] ERROR - Command line failed with exit code: 1
Command: bin/hmmer/hmmer3/3.3/hmmscan -E 0.01 --acc --cpu 1 -o /ds3512/home/panyp/NN1138-2/22.resistance_gene/00.install_RGAugury/interproscan-5.47-82.0/temp/NCSI.njau.edu.cn_20220126_140023732_k6f//jobPIRSF/000000000001_000000000006.raw.out --domtblout /ds3512/home/panyp/NN1138-2/22.resistance_gene/00.install_RGAugury/interproscan-5.47-82.0/temp/NCSI.njau.edu.cn_20220126_140023732_k6f//jobPIRSF/000000000001_000000000006.raw.domtblout.out data/pirsf/3.10/sf_hmm_all /ds3512/home/panyp/NN1138-2/22.resistance_gene/00.install_RGAugury/interproscan-5.47-82.0/temp/NCSI.njau.edu.cn_20220126_140023732_k6f//jobPIRSF/000000000001_000000000006.fasta
Error output from binary:
bin/hmmer/hmmer3/3.3/hmmscan: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/hmmer/hmmer3/3.3/hmmscan)
bin/hmmer/hmmer3/3.3/hmmscan: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by bin/hmmer/hmmer3/3.3/hmmscan)

2022-01-26 14:00:47,678 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:213] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: bin/hmmer/hmmer3/3.3/hmmscan -E 0.01 --acc --cpu 1 -o /ds3512/home/panyp/NN1138-2/22.resistance_gene/00.install_RGAugury/interproscan-5.47-82.0/temp/NCSI.njau.edu.cn_20220126_140023732_k6f//jobPIRSF/000000000001_000000000006.raw.out --domtblout /ds3512/home/panyp/NN1138-2/22.resistance_gene/00.install_RGAugury/interproscan-5.47-82.0/temp/NCSI.njau.edu.cn_20220126_140023732_k6f//jobPIRSF/000000000001_000000000006.raw.domtblout.out data/pirsf/3.10/sf_hmm_all /ds3512/home/panyp/NN1138-2/22.resistance_gene/00.install_RGAugury/interproscan-5.47-82.0/temp/NCSI.njau.edu.cn_20220126_140023732_k6f//jobPIRSF/000000000001_000000000006.fasta
Error output from binary:
bin/hmmer/hmmer3/3.3/hmmscan: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/hmmer/hmmer3/3.3/hmmscan)
bin/hmmer/hmmer3/3.3/hmmscan: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by bin/hmmer/hmmer3/3.3/hmmscan)

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:201) ~[interproscan-management-5.47-82.0.jar:?]
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor98.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]

Could you help me fix this problem? Thank you very much.

**Comment by matthiasblum** [comment]
If your version of GLIBC is too old and you cannot update it, you can try our [Docker image](https://hub.docker.com/r/interpro/interproscan/).
