### ISSUE TITLE
Inconsistent option name in interproscan.properties

### ISSUE THREAD

**Issue by abretaud** [ebi-pf-team/interproscan#247]
Hi,
In the default `interproscan.properties ` file, there are 2 options that don't match what's used by the code: instead of using `binary.prosite.pfscanv3.path` and `binary.prosite.pfsearchv3.path`, the code uses `binary.pfscanv3.path`, and a mix of `binary.prosite.pfsearchv3.path` and `binary.pfsearchv3.path`

**Comment by matthiasblum** [comment]
This has been fixed in the latest release of InterProScan (`5.56-89.0`).
