### ISSUE TITLE
Issue  with superfamily via conda install

### ISSUE THREAD

**Issue by AdamStuckert** [ebi-pf-team/interproscan#248]
Hi,

I've installed version 5.54-87.0 via conda. I followed the instructions to download the tarball and move the data files into the appropriate location. But, when I try to run the initial setup I am getting errors with the superfamily library that comes with the install.

```python3 initial_setup.py
Checking any hmm models that need indexing ... this may take a few minutes
Working...    SSI index construction failed:
  primary keys not unique: '7,8-didemethyl-8-hydroxy-5-de' occurs more than once
Working...    SSI index construction failed:
  secondary keys not unique: '100879' occurs more than once
Completed indexing the hmm models.
```

Then, when I try the initial test run with `./interproscan.sh -i test_all_appl.fasta -f tsv -dp` I get this error:

> Error: Failed to open binary auxfiles for data/superfamily/1.75/hmmlib_1.75: use hmmpress first

Running `hmmpress data/superfamily/1.75/hmmlib_1.75` does not fix the issue, and yields the same error about secondary keys not being unique.

Head of the superfamily library:

```head data/superfamily/1.75/hmmlib_1.75
HMMER3/b [3.0 | March 2010]
NAME  0034782
ACC   54076
DESC  RNase A-like
LENG  124
ALPH  amino
RF    no
CS    no
MAP   no
COM 1 This model under the license at http://supfam.org/SUPERFAMILY/license.html
```

Thanks,
Adam

**Comment by matthiasblum** [comment]
Hi,

This issue has already been reported (see #232). 

To avoid this error, you can use an older version of HMMER (`3.1b2`) to index the profile databases with duplicated keys (SUPERFAMILY and SFLD).

**Comment by Lsz-20** [comment]
@matthiasblum I have also installed 5.54-87.0 via conda,the hmmer=3.3.2 & hmmer2=2.3.2.Then i change to hmmer=3.1b ,but the results have not change...
