### ISSUE TITLE
About conda install interproscan

### ISSUE THREAD

**Issue by Lsz-20** [ebi-pf-team/interproscan#249]
I want to install interproscan with lower version,but it seems can't work?
Ex:in bioconda interproscan can be installed with 5.54 version, but i want 5.53.how can i get this?when i use interproscan=5.53-87.0,it can't work.
Thanks!

**Comment by matthiasblum** [comment]
Hi,

The InterPro team at EMBL-EBI does not maintain the Bioconda package.

It seems that InterProScan `5.53-87.0` is not available through Bioconda, but `5.52-86.0` is (see https://bioconda.github.io/recipes/interproscan/README.html#package-interproscan).

Also, please note that the data and annotations are the same in `5.53-87.0` and `5.54-87.0`. InterProScan `5.54-87.0` was released to fix a major security vulnerability.

Finally, if you need to use an older version of InterProScan, you can download past releases at http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/.

**Comment by Lsz-20** [comment]
@matthiasblum 
Hello,Thanks for the reply I m currently using 5.54 installed via conda but the results differ between what I ran and the example provided.I want to confirm that the operation is correct:
I have just 'conda install InterProScan' without other action although it shows this:
============
# get the md5 of the databases
wget http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/-/interproscan---64-bit.tar.gz.md5
# get the databases (with core because much faster to download)
wget http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/-/interproscan---64-bit.tar.gz   
# checksum
md5sum -c interproscan---64-bit.tar.gz.md5
# untar gz
tar xvzf interproscan---64-bit.tar.gz.md5
# remove old DB
rm -rf /opt/conda/envs/Ri/share/InterProScan/data/
# copy past the new db
cp -r interproscan--/data /opt/conda/envs/Ri/share/InterProScan/
============
Perhaps i need to change the data file?
Thanks!
