### ISSUE TITLE
Interproscan looking for file that is not present in temp directory

### ISSUE THREAD

**Issue by raj76** [ebi-pf-team/interproscan#25]
Hi,

I am testing a new installation of interproscan (v 6.23-62.0). I am using the provided test_protein.fasta file and using the following command:

$ ./interproscan.sh -dp -i test_proteins.fasta -f tsv -T /dev/shm/

The program runs till 75% completion and then dies throwing an IOException.
I've attached the output in the interproscan.log
[interproscan.log.txt](https://github.com/ebi-pf-team/interproscan/files/862966/interproscan.log.txt)
 

The error indicates that it couldn't find the file /dev/shm/uga-a24852b.scm_20170322_171029961_l0md//jobGene3d/000000000001_000000000006_one.raw.out in the /dev/shm (my temp area). 
I don't see any temp file created with the name 000000000001_000000000006_one.raw.out instead I see files created with the name 000000000001_000000000006.raw.out.

Is this a buy or am I doing something wrong?

Thanks,
Raj

**Comment by gsn7** [comment]
The Gene3D binary bundled with InterProScan has slightly different parameter values than the  Redhat/Centos 6  binary.
Add the following line to the interproscan.properties file if you are using the Redhat/Centos 6 Gene3d binary:
cath.resolve.hits.switches.gene3d=--input-format=hmmer_domtblout

**Comment by raj76** [comment]
Thanks! You fix worked.
