### ISSUE TITLE
Overriding config files

### ISSUE THREAD

**Issue by Pooryamb** [ebi-pf-team/interproscan#250]
Hi all,

I am using interproscan installed on a server. Precalculated match lookup has been disabled for the installed version, and I cannot modify the config files. Is it possible that I override the config files with some command-line options? I could not find anything in this regard.

Best,

**Comment by matthiasblum** [comment]
Hi @Pooryamb,

You can create the `interproscan.properties` file in `${HOME}/.interproscan-5/` and add properties to override those defined in the default config file.
