### ISSUE TITLE
conda 5.54_87.0 and pfsearchV3

### ISSUE THREAD

**Issue by Lsz-20** [ebi-pf-team/interproscan#251]
I have installed the 5.54_87.0 with conda install -c bioconda interproscan
then i run the ./interproscan,but i got the outputs different from samples,which has lost many sequence.And it show me :
25/02/2022 15:07:50:447 Welcome to InterProScan-5.54-87.0
25/02/2022 15:07:50:448 Running InterProScan v5 in STANDALONE mode... on Linux
25/02/2022 15:07:54:585 RunID: 926a67f1c5b6_20220225_150754494_dm5n
25/02/2022 15:08:01:683 Loading file /nfs/my/lsz/NLR/NLRtracker-master/sample_data/sample.fasta
25/02/2022 15:08:01:684 Running the following analyses:
[CDD-3.18,Gene3D-4.3.0,Pfam-34.0,PRINTS-42.0,ProSiteProfiles-2021_01,SMART-7.1,SUPERFAMILY-1.75]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
25/02/2022 15:08:07:496 34% completed
25/02/2022 15:08:12:593 52% completed
25/02/2022 15:08:13:689 78% completed
25/02/2022 15:08:19:714 91% completed
25/02/2022 15:08:26:344 100% done:  InterProScan analyses completed 
2022-02-25 15:08:26,850 [main] [uk.ac.ebi.interpro.scan.jms.main.Run:1883] WARN - deleteWorkingDirectoryOnCompletion : false
=============================
I'm not sure should i change the data file in interproscan?
Then i have tried to: hmmer-->3.1b and change the data file in right path,but it also has error:
=============================
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
2022-02-26 06:07:47,594 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:199] ERROR - Command line failed with exit code: 1
Command: python3 bin/prosite/runprosite.py data/prosite/2021_01/profile_models /opt/conda/envs/Ri/share/InterProScan/temp/926a67f1c5b6_20220226_060734569_97n8//jobPrositeProfiles/000000000001_000000000031.fasta /opt/conda/envs/Ri/share/InterProScan/temp/926a67f1c5b6_20220226_060734569_97n8//jobPrositeProfiles/000000000001_000000000031.raw.out pfsearchV3 -f -o 7 -t 4 
Error output from binary:
Error running prosite binary pfsearchV3
2022-02-26 06:07:47,598 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: python3 bin/prosite/runprosite.py data/prosite/2021_01/profile_models /opt/conda/envs/Ri/share/InterProScan/temp/926a67f1c5b6_20220226_060734569_97n8//jobPrositeProfiles/000000000001_000000000031.fasta /opt/conda/envs/Ri/share/InterProScan/temp/926a67f1c5b6_20220226_060734569_97n8//jobPrositeProfiles/000000000001_000000000031.raw.out pfsearchV3 -f -o 7 -t 4 
Error output from binary:
Error running prosite binary pfsearchV3
........

**Comment by matthiasblum** [comment]
Hi,

What happens if you do a test run?

```
./interproscan.sh -i test_all_appl.fasta -f tsv -o test_all_appl.fasta.tsv  -dp
```

Do you see the same error?

**Comment by Lsz-20** [comment]
> Hi,
> 
> What happens if you do a test run?
> 
> ```
> ./interproscan.sh -i test_all_appl.fasta -f tsv -o test_all_appl.fasta.tsv  -dp
> ```
> 
> Do you see the same error?

Yes, it seems that 5.54 has some trouble?
when i tried 5.52 it can work well?
