### ISSUE TITLE
Interproscan data graphical visualization

### ISSUE THREAD

**Issue by MalikS10** [ebi-pf-team/interproscan#26]
Hi 

Are there any tools to visualise the data other than BlAst2Go. I came across IPRStats but it doesn't work on Interproscan5 files.

Thanks

**Comment by gsn7** [comment]
we don't have graphical visualisation tools, but depending on what you want it should relatively easily to create the visualisation you want from the tsv data

**Comment by gsn7** [comment]
you should now be able to visualise your results, by uploading a json file at https://www.ebi.ac.uk/interpro/result/InterProScan/#table
