### ISSUE TITLE
problem with annotation IPR00816

### ISSUE THREAD

**Issue by jalan01** [ebi-pf-team/interproscan#260]
Hello, 
There is a discrepancy between the annotation of entry A0A075FKY9 as it appears in the Interpro database and when using the Interproscan function. The sequence regions identified as containing collagen triple-helical repeat (IPR00816) are different (please see attached picture. Inspection of the fasta file suggests the later to be correct. What could be causing this?

<img width="1014" alt="Screenshot 2022-04-04 at 21 18 26" src="https://user-images.githubusercontent.com/102993978/161617980-aa3740ac-8d43-41da-95a6-a691814b3ab5.png">
<img width="1058" alt="Screenshot 2022-04-04 at 21 20 38" src="https://user-images.githubusercontent.com/102993978/161617991-1a355bb8-47c1-4140-b41b-34bc161df47e.png">

**Comment by matthiasblum** [comment]
Hi @jalan01 ,

Sorry for the late reply.

InterProScan does not report _InterPro_ matches. It reports matches from various analyses/databases (such as Pfam, PANTHER, CDD, etc.). On the InterPro website, when a model/signature (e.g. PF01391)  is integrated in an InterPro entry, we add an InterPro annotation/track. This is more useful when the entry integrates more than one signature, as it gives an overall idea of the coverage.

We found a bug in the InterPro website, where the InterPro annotation/track is not correctly built for InterProScan results: ProteinsWebTeam/interpro7-client#386.
