### ISSUE TITLE
gene3d hangs for particular sequence groups

### ISSUE THREAD

**Issue by rattei** [ebi-pf-team/interproscan#27]
We run the latest interproscan-5.23-62.0 on sequence chunk from a de novo assembly. For many of the chunks, interproscan gets stuck in the java process, after all calculations have finished. The process does not finish after 16 hours (we did not wait longer).
We can reproduce the error when only requesting gene3d:
`interproscan-5.23-62.0/interproscan.sh -dp --goterms -i test.fasta2.reform.fasta -appl gene3d -f tsv`
whereas all other methods without gene3d run fine without problems:
`interproscan-5.23-62.0/interproscan.sh -dp --goterms -i test.fasta2.reform.fasta -appl cdd,coils,gene3d,hamap,mobidblite,panther,pfam,phobius,pirsf,prints,prodom,prositepatterns,prositeprofiles,sfld,signalp_euk,signalp_gram_negative,signalp_gram_positive,smart,superfamily,tigrfam,tmhmm -f tsv`

We did not change any gene3d related parameter in interproscan.properties. The temporary directory is in a local path under /tmp, excluding NFS delays as a reason.

Very strange: if we further split the input file test.fasta2.reform.fasta, all smaller parts of it run fine. The problem is therefore not the result of a single sequence...

Thanks for your help!!
Best,
Thomas

[test.fasta2.reform.fasta.zip](https://github.com/ebi-pf-team/interproscan/files/916311/test.fasta2.reform.fasta.zip)

**Comment by fungs** [comment]
Not sure but I think we might see a similar effect with the gene3d collection.

**Comment by gsn7** [comment]
Gene3D post processing seems to require more memory for some protein sequences. the quick fix would be to double or triple the  value in interproscan.sh
Or check what is the max memory  used by interproscan with the problem input sequences. then use double that value as the Xmx value in interproscan.sh

**Comment by rattei** [comment]
Thanks! Confirm that everything works fine now with -xmX=10g.

Best,
Thomas

**Comment by gsn7** [comment]
this is resolved in the newer releases
