### ISSUE TITLE
log4j vulnerability listed in interproscan package

### ISSUE THREAD

**Issue by jayramr** [ebi-pf-team/interproscan#272]
Hi there,

Our IT found and raised the log4j vulnerability in the nterproscan latest package version - 5.56-89.0

lib/log4j-1.2.17.jar

Below is the resolution as per our IT

Log4j 1.x has reached End of Life in 2015 and is no longer supported. Vulnerabilities reported after August 2015 against Log4j 1.x were not checked and will not be fixed. Users should
 upgrade to Log4j 2 to obtain security fixes.

Please fix the same

Thanks
Jay

**Comment by matthiasblum** [comment]
Hi,

The `log4j-1.2.17.jar` dependency will be remove in the next release of InterProScan (late July).
