### ISSUE TITLE
annotation of collagen repeats

### ISSUE THREAD

**Issue by jalan01** [ebi-pf-team/interproscan#274]
I am trying to create a database of the eukaryotic proteins that contain collagen triple helical repeats. It seems that InterPro is not correctly annotating certain regions of sequences, even though visual inspection clearly reveals that these contain collagen repeats. For example, the sequence regions 2-97 and 108-158 of the accesssion A0A087WTY5 are annotated to IPR008160. Close inspection suggests that after an interruption of 3 amino acids 159-161, the collagen triplet repeat continues until sequence position 180. This is followed by another 13 amino acid interruption (181-193) and then again a collagen triple repeat until the end of the sequence. Perhaps the reason why InterPro fails to annotate these latter sequences is because the repeat sequence in between the interruptions is too short. This is clearly a false negative. Sequences on either side of an interruption can be safely annotated as IPR008160 if it contains at least six collagen triplet repeats. 

Manual inspection is clearly not feasible (>80k sequences). I have also tried to run interproscan on home computer to see if it annotates these missed regions but in vain. Is there a way to fix this? 

<img width="1148" alt="Screenshot 2022-06-21 at 11 17 21" src="https://user-images.githubusercontent.com/102993978/174764467-c6b702ad-6c0c-4f19-ac84-39b11f45e05e.png">

**Comment by matthiasblum** [comment]
Hi @jalan01,

The InterPro annotation `IPR008160` comes from the underlying Pfam model `PF01391`. In this case, the issue is not with InterProScan (software) but with the Pfam model. 

I'll ask Pfam curators what they think and update this issue.

**Comment by jalan01** [comment]
Hi @matthiasblum 
Fantastic and many thanks for looking into it.

**Comment by matthiasblum** [comment]
Hi @jalan01,

I had a discussion with InterPro/Pfam curators. The repeats are indeed not consistent which is why the `PF01391` model does not always correctly annotate them. Unfortunately we will not be able to "fix" `PF01391` because changing the model to make it perfectly annotates your example would cause it to be less accurate for other sequences.

**Comment by jalan01** [comment]
Hi @matthiasblum,
Thanks for the update. I guess we will have to live with what we have :)
cheers,
