### ISSUE TITLE
Convert output to FASTA format

### ISSUE THREAD

**Issue by kelvenr** [ebi-pf-team/interproscan#281]
I am working on a project to assemble and annotate a genome. I used Interproscan for functional annotation and generated GFF3 and TSV files.  My aim is to run OrthoMCL after this step for comparative genomics. However, the inputs needed for OrthoMCL are annotated genome and protein fasta files; here is an example of the input files:
```
$ head annotations-small/2010EL-1749.faa
>2010EL-1749_00001 Stalked cell differentiation-controlling protein
MDARLFDNTQTLRASVLCGLSFFWALIAFLMALINFWSTRLVELASLELVCAFYSLYIYS
LAKRRIHTKQQVYLYLFILTGTTLFATYMKPLMMGVYIWSCFVPILFYIFTSARFAFVTS
...

$ head annotations-small/2010EL-1749.ffn
>2010EL-1749_00001 Stalked cell differentiation-controlling protein
ATGGATGCTAGGTTATTTGACAATACACAAACGCTTCGAGCTTCAGTGCTATGCGGCCTA
AGTTTCTTTTGGGCTTTGATCGCTTTCTTGATGGCGCTGATCAATTTCTGGTCAACACGG
...
```

How can I convert the GFF3 or TSV file into annotated genome and protein files?

Also, Interproscan generated several possible annotations for every sequence. How should I decide which annotation to choose?

I am new to this tool and am still getting the hang of it, and haven't found the answer to my question in any documentation, so any help is appreciated.

Thank you in advance.

**Comment by matthiasblum** [comment]
You can extract the annotations provided by InterPro and add them to the header of the sequences in the FASTA file. However, I never used OrthoMCL so I don't know if it expects a particular FASTA header format. If a sequences is annotated by several InterPro entries, you can add all of them in the header.

I am joining an archive ([tsv-to-fasta.zip](https://github.com/ebi-pf-team/interproscan/files/9495706/tsv-to-fasta.zip)) of a Python script with two example files (FASTA and TSV). The script takes two arguments: a FASTA file (as provided to InterProScan) and a TSV file generated by InterProScan, and prints the FASTA file with InterPro annotations added to the header. You can run the script
 with these two files as follows:

```py
$ python tsv-to-fasta.py sequences.fasta annotations.tsv > annotated-sequences.fasta
```
