### ISSUE TITLE
Error running prosite binary bin/prosite/pfsearchV3

### ISSUE THREAD

**Issue by cpavloud** [ebi-pf-team/interproscan#282]
Hi!

I am trying to run InterProScan (5.56-89.0) at an HPC 

`interproscan.sh -i genome.masked.fa -t n -d intepro_masked -iprlookup -pa -goterms -f TSV, XML, JSON, GFF3 -cpu 38`

But the job crushes. 
In the output file, among others, I get these error messages

**The version of InterProScan you are using is 5.56-89.0
The version of the lookup service you are using is 5.57-90.0
As the data in these versions is not the same, you cannot use this match lookup service.
InterProScan will now run locally
If you would like to use the match lookup service, you have the following options:
i) Download the newest version of InterProScan5 from our FTP site by following the instructions on:
   https://www.ebi.ac.uk/interpro/interproscan.html
ii) Download the match lookup service for your version of InterProScan from our FTP site and install it locally.
    You will then need to edit the following property in your configuration file to point to your local installation:
    precalculated.match.lookup.service.url=

In the meantime, the analysis will continue to run locally.**

`
Error output from binary:
bin/prosite/pfsearchV3: error while loading shared libraries: libpcre.so: cannot open shared object file: No such file or directory
Error running prosite binary bin/prosite/pfsearchV3
`

`
2022-08-25 01:16:53,941 [amqEmbeddedWorkerJmsContainer-9] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:222] ERROR - StepExecution with errors - stepName: stepPrositeProfilesRunBinary
`

`
Could not execute bin/prosite/pfscanV3 --matrix-only -o4 -L-1 /tmp/ps338809-1.tmp /tmp/ps338809-3.tmp  > /tmp/ps338809-2.tmp: Inappropriate ioctl for device at bin/prosite/ps_scan.pl line 1751.
`

Do you have any idea how to workaround this issue?

I have uploaded the complete output so that you can observe the errors. 
[interpro_output.txt](https://github.com/ebi-pf-team/interproscan/files/9425041/interpro_output.txt)

**Comment by tgrego** [comment]
Hello
The error occurs because a library that is required by prosite is missing. On debian-based systems you can install this library with the following command:
sudo apt install libpcre3-dev

Kind regards

**Comment by 991011zyy** [comment]
hi, i meet the same error"Command: bin/prosite/ps_scan.pl -d data/prosite/2023_05/prosite_patterns.dat --pfscan bin/prosite/pfscanV3 -b data/prosite/2023_05/evaluator.dat -r -s -o ipro /media/HD3/database/my_interproscan/interproscan-5.66-98.0/temp/emma-TRX40-AORUS-PRO-WIFI_20240228_112039941_chcb//jobPrositePatterns/000000000001_000000003457.fasta 
Error output from binary:
bin/prosite/pfscanV3: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
Could not execute bin/prosite/pfscanV3 --matrix-only -o4 -L-1 /tmp/ps752937-1.tmp /tmp/ps752937-3.tmp  > /tmp/ps752937-2.tmp: Inappropriate ioctl for device at bin/prosite/ps_scan.pl line 1751.

2024-02-28 11:22:28,876 [amqEmbeddedWorkerJmsContainer-7] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 25
Command: bin/prosite/ps_scan.pl -d data/prosite/2023_05/prosite_patterns.dat --pfscan bin/prosite/pfscanV3 -b data/prosite/2023_05/evaluator.dat -r -s -o ipro /media/HD3/database/my_interproscan/interproscan-5.66-98.0/temp/emma-TRX40-AORUS-PRO-WIFI_20240228_112039941_chcb//jobPrositePatterns/000000000001_000000003457.fasta 
Error output from binary:
bin/prosite/pfscanV3: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
Could not execute bin/prosite/pfscanV3 --matrix-only -o4 -L-1 /tmp/ps752937-1.tmp /tmp/ps752937-3.tmp  > /tmp/ps752937-2.tmp: Inappropriate ioctl for device at bin/prosite/ps_scan.pl line 1751 " can you share your solve keys?

**Comment by tgrego** [comment]
that a missing  pcre2 library missing. On debian based systems you can install with:
`sudo apt-get install -y libpcre2-dev`
