### ISSUE TITLE
Javaversion 11 is required to run InterProScan.

### ISSUE THREAD

**Issue by chenwy804** [ebi-pf-team/interproscan#283]
This may seem a woolly problem, but I still wonder where I have gone wrong.This was stated in the manual of use ”Any Oracle/Open JDK/JRE with Java 1.8.x should work with InterProScan.“
But when I run. / interproscan.sh The following responses were present :

Javaversion 11 is required to run InterProScan.
Detected version 1.8.0_332
Please install the correct version

Thank you very much!

**Comment by tgrego** [comment]
InterProScan from version 5.37-76.0 requires Java 11.
This is stated in the online documentation on https://interproscan-docs.readthedocs.io/en/latest/InstallationRequirements.html

Can you point me to where you found the Java 1.8.x requirement? that will be updating.
Thank you!

**Comment by Ghepardo** [comment]
Hi

You don't have to look far for this.  It's at https://interproscan-docs.readthedocs.io/en/latest/InstallationRequirements.html#appendix-historical-java-version-testing-information.  HTH ;-)
