### ISSUE TITLE
Installing SMART licensed models

### ISSUE THREAD

**Issue by J-Calvelo** [ebi-pf-team/interproscan#284]
Hello, this must be basic but I'm not sure how to use SMART licensed models. The public ones that come with interprot san are a single file while the licensed ones are multiples. Do I need to combine them and generate some indexing?

Thanks

**Comment by matthiasblum** [comment]
If licenses models are individual profile HMM files, it might be enough to concatenate them

```sh
cat /path/to/models/* > smart.HMMs
```

then index them with HMMER 2:

```sh
hmmconvert -b smart.HMMs smart.HMMs.bin
```

and replace the `smart.HMMs` and `smart.HMMs.bin` from the InterProScan installation with the new files.

However, we don't support licenses SMART models and won't provide assistance if the analysis fails.
