### ISSUE TITLE
Multiple GO IDs

### ISSUE THREAD

**Issue by ucabuk** [ebi-pf-team/interproscan#285]
Dear EBI-team,

In the output file, one Pfam is assigned to multiple Gene Ontology IDs. How does the interproscan decide proteins are assigned into which gene ontology level ? Also, would it be correct to manually add the other levels in case the protein is assigned into level 5, 6, or so on, in Gene Ontology.

Thank you.
Ugur

**Comment by matthiasblum** [comment]
InterPro curators assign GO terms to InterPro entries. When annotating sequences, InterProScan checks whether the signatures of identified matches are integrated in a InterPro entries: if it's the case, the InterPro entry (and all GO terms assigned to it) are reported.
