### ISSUE TITLE
Java version 11 is required to run InterProScan.

### ISSUE THREAD

**Issue by cherryDAP** [ebi-pf-team/interproscan#287]
Hello, recently I am using interproscan-5.57-90.0, run the test data and got an error.
$ interproscan.sh -i test_proteins.fasta -f tsv
Java version 11 is required to run InterProScan.
Detected version 1.8.0_92
Please install the correct version.

But I checked my java version as below
$ java -version
java version "11.0.14" 2022-01-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.14+8-LTS-263)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.14+8-LTS-263, mixed mode)

Don't know where is the problem. Is it a problem where the java is called for the script?

**Comment by matthiasblum** [comment]
Hi,

What does the commands below return?

**Comment by lvqiang0120** [comment]
> Hello, recently I am using interproscan-5.57-90.0, run the test data and got an error. $ interproscan.sh -i test_proteins.fasta -f tsv Java version 11 is required to run InterProScan. Detected version 1.8.0_92 Please install the correct version.
> 
> But I checked my java version as below $ java -version java version "11.0.14" 2022-01-18 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.14+8-LTS-263) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.14+8-LTS-263, mixed mode)
> 
> Don't know where is the problem. Is it a problem where the java is called for the script?

Hello, I encountered the same error as you did. May I ask how you eventually resolved the issue?
