### ISSUE TITLE
[amqEmbeddedWorkerJmsContainer-10] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:199] ERROR - Command line failed with exit code: 1

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [ebi-pf-team/interproscan#290]
I run the "~/software/interproscan-5.52-86.0/interproscan.sh    -i hap1_protein.fasfa -b hap1.iprscan  -iprlookup -pa   -f tsv -dp  --cpu 20"

its error 
03/10/2022 08:24:19:301 Welcome to InterProScan-5.52-86.0
03/10/2022 08:24:19:305 Running InterProScan v5 in STANDALONE mode... on Linux
03/10/2022 08:24:24:823 RunID: s002_20221003_082424285_6qpb
03/10/2022 08:24:33:754 Loading file /public/home/zhaoli/dama/annotation/hap1/interopro/hap1_protein.fasfa
03/10/2022 08:24:33:756 Running the following analyses:
[CDD-3.18,Coils-2.2.1,Gene3D-4.3.0,Hamap-2020_05,MobiDBLite-2.0,PANTHER-15.0,Pfam-33.1,PIRSF-3.10,PIRSR-2021_02,PRINTS-42.0,ProSitePatterns-2021_01,ProSiteProfiles-2021_01,SFLD-4,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
03/10/2022 08:24:40:201 Uploaded 27111 unique sequences for analysis
2022-10-03 08:24:48,452 [amqEmbeddedWorkerJmsContainer-10] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:199] ERROR - Command line failed with exit code: 1
Command: bin/hmmer/hmmer3/3.3/hmmsearch -Z 65000000 -E 0.001 --domE 0.00000001 --incdomE 0.00000001 --cpu 1 -o /public/home/zhaoli/dama/annotation/hap1/interopro/temp/s002_20221003_082424285_6qpb//jobPanther/000000019001_000000019500.raw.out --domtblout /public/home/zhaoli/dama/annotation/hap1/interopro/temp/s002_20221003_082424285_6qpb//jobPanther/000000019001_000000019500.raw.domtblout.out data/panther/15.0/panther.hmm /public/home/zhaoli/dama/annotation/hap1/interopro/temp/s002_20221003_082424285_6qpb//jobPanther/000000019001_000000019500.fasta 
Error output from binary:

Error: File format problem in trying to open HMM file data/panther/15.0/panther.hmm.
Opened data/panther/15.0/panther.hmm.h3m, a pressed HMM file; but format of its .h3i file unrecognized

2022-10-03 08:24:48,464 [amqEmbeddedWorkerJmsContainer-10] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: bin/hmmer/hmmer3/3.3/hmmsearch -Z 65000000 -E 0.001 --domE 0.00000001 --incdomE 0.00000001 --cpu 1 -o /public/home/zhaoli/dama/annotation/hap1/interopro/temp/s002_20221003_082424285_6qpb//jobPanther/000000019001_000000019500.raw.out --domtblout /public/home/zhaoli/dama/annotation/hap1/interopro/temp/s002_20221003_082424285_6qpb//jobPanther/000000019001_000000019500.raw.domtblout.out data/panther/15.0/panther.hmm /public/home/zhaoli/dama/annotation/hap1/interopro/temp/s002_20221003_082424285_6qpb//jobPanther/000000019001_000000019500.fasta 
Error output from binary:

Error: File format problem in trying to open HMM file data/panther/15.0/panther.hmm.
Opened data/panther/15.0/panther.hmm.h3m, a pressed HMM file; but format of its .h3i file unrecognized

![image](https://user-images.githubusercontent.com/101324838/193495623-805916e4-f2ff-4fca-860b-28a0f10e298b.png)
how to slove it. thank you

**Comment by tgrego** [comment]
it looks as if there was an error while pressing the panther hmm file... please try removing the pressed files:
`rm -rf data/panther/15.0/panther.hmm.*`

you can then run the initial_setup.py script (or just run interproscan as the it should repress the hmm file)

**Comment by Jiangjiangzhang6** [comment]
hello, my friend,  I run the command with the " /public/home/software/opt/bio/software/interproscan/5.55-88.0/interproscan.sh  -i hap1_protein.fasfa -b hap1.iprscan  -iprlookup -pa   -f TSV -T /public/home/zhaoli/temp2 -dp  --cpu 25 
-appl  Pfam -appl  PANTHER"
ite show 
![image](https://user-images.githubusercontent.com/101324838/193689126-1bd5f658-9008-4562-997e-19234dcdf2e8.png)


this software was module form cluster, so its also error

**Comment by tgrego** [comment]
Hi, for the pfsearchV3 error please refer to #288 for a solution.
