### ISSUE TITLE
Idea: Stop codons in amino acid sequence

### ISSUE THREAD

**Issue by jjkoehorst** [ebi-pf-team/interproscan#30]
Would it be a "wise" idea to mark stop codons (*) as X? such that protein sequences with a predicted but not necessary a stop codon can still be analyzed? Or do not all applications like this character?

**Comment by gsn7** [comment]
yes, you can change the STOP codon positions from (*) to X in the input sequence file to interproscan. Did you get an error with such input?

**Comment by jjkoehorst** [comment]
No no issue was just wondering if this would be a wise thing to do sometimes.
