### ISSUE TITLE
Large File Space Causing Issues Running InterProScan

### ISSUE THREAD

**Issue by rghosh670** [ebi-pf-team/interproscan#318]
I'm trying to use InterProScan in standalone mode on a cluster with a large file space (8E). Whenever I try to run the tool, I get the following error:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.activemq.xbean.XBeanBrokerService#0' defined in class path resource [spring/jms/master/standalone-master-context.xml]: Invocation of init method failed; nested exception is org.apache.activemq.ConfigurationException: **File system space reported by: /hot/user/rghosh/splicing_project/protein_analysis/lib/interproscan-5.61-93.0 was negative, possibly a huge file system, set a sane usage.total to provide some guidance**

Is there any way for me to work around this issue? I think the large file space is causing an overflow error.

**Comment by matthiasblum** [comment]
It looks like it's an issue with the file system indeed. You can try to run [InterProScan with Docker](https://hub.docker.com/r/interpro/interproscan/), otherwise you will need to request our cluster admin to provide a smaller file system.
