### ISSUE TITLE
Interpro uses more CPUs than I specified:

### ISSUE THREAD

**Issue by sbthandras** [ebi-pf-team/interproscan#325]
I've launched interpro with this command (using the docker image):

interproscan_5.45-80.0_1.sif -i chunk_1.fasta -f tsv,xml -d outdir -C 2 -c -T 1_tmp

It should use 2 CPU-s but for  some reason my entire HPC is flooded with CPUs until Interpro fails with the thread creation failed message.

**Comment by matthiasblum** [comment]
Hi @sbthandras,

Sorry for the late reply. Could you paste the entire log message?
