### ISSUE TITLE
Incorrect downloads under 'Releases'?  

### ISSUE THREAD

**Issue by Ghepardo** [ebi-pf-team/interproscan#326]
Hi

On the GitHub 'Releases' page for InterProScan, the pair of downloads for the latest version - .zip and .tar.gz - are only 93M and 94M in size respectively.  They do not include the 'data' directory.  They appear to be "core" flavours of the download, even though they're not labelled as such.  The 'Releases' page states that they should be 5.5G in size.  

This problem also affects a download for at least the previous version of InterProScan.  

I appreciate we can go to https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/ for all flavours of the downloads.  Perhaps the GitHub page should just point users in that direction, rather than making downloads available itself?

**Comment by matthiasblum** [comment]
Hi @Ghepardo ,

That's a good point, thanks for raising it. We'll start adding links to our FTP site for the next release.
