### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by multimeric** [ebi-pf-team/interproscan#330]
Hi, interproscan seems to have a lot of binary dependencies. Although a pre-compiled version is provided, it's not entirely unlikely that a user will have a system that is incompatible with those binaries. For example, at my institute our GLIBC is 2.17 which is lower than the version interproscan is compiled for.

A reasonable solution might be to provide a Docker image for interproscan, which could run on an old system using apptainer or podman. It seems there have been initiatives to do this in the past, but for example the [`interpro/interproscan`](https://hub.docker.com/r/interpro/interproscan) image hasn't been updated for 2 years (5.51-85.0), whereas the newest version seems to be 5.63-95.0. I would be happy to contribute a `Dockerfile` for this, or help with updating an existing one if it exists?

**Comment by matthiasblum** [comment]
Hi @multimeric ,

We've updated our Docker image on [Docker Hub](https://hub.docker.com/r/interpro/interproscan) to support the latest version of InterProScan (`5.63-95.0`).

**Comment by multimeric** [comment]
Many thanks!
