### ISSUE TITLE
Pfam-N in InterProScan command line?

### ISSUE THREAD

**Issue by photocyte** [ebi-pf-team/interproscan#335]
Hi there,

I came across Pfam-N annotations as an alternative to standard Pfam/HMMER annotations. Many InterPro annotations have such annotations:
https://www.ebi.ac.uk/interpro/protein/UniProt/B6SKY5/ 

Here are some other relevant links:
https://www.nature.com/articles/s41587-021-01179-w
https://proteinswebteam.github.io/interpro-blog/2022/10/20/InterPro-91.0-latest-developments/
https://xfam.wordpress.com/2022/10/20/a-new-version-of-pfam-n-is-available/
https://xfam.wordpress.com/2021/03/24/google-research-team-bring-deep-learning-to-pfam/

Is there any plan to include Pfam-N predictions in InterProScan?

**Comment by matthiasblum** [comment]
Hi @photocyte,

Sorry for the late reply.

Currently, our collaborators at Google Research provides us the Pfam-N predictions, not the model to run the predictions ourselves. However, there is a long-term plan to include Deep Learning methods (such a Pfam-N) in InterProScan, but I can't tell you when this will be implemented.
