### ISSUE TITLE
Error in mobidb: invalid next size

### ISSUE THREAD

**Issue by xingjianfeng100** [ebi-pf-team/interproscan#336]
Hi, 
It has successfully run when using test data，but reported an error when using targeted protein sequence by the commond `interproscan-5.64-96.0/interproscan.sh -i query.faa -b out.iprscan -goterms -iprlookup -pa -dp -cpu 32,` details are as follows:

> *** Error in 'interproscan-5.64-96.0/bin/mobidb/2.0/binx/iupred/bin64/iupred_string': free(): invalid next size (normal): 0x0000000000a0ee80 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7f5ff452c329]
/lib64/libc.so.6(fclose+0x177)[0x7f5ff4519247]
interproscan-5.64-96.0/bin/mobidb/2.0/binx/iupred/bin64/iupred_string[0x402520]
interproscan-5.64-96.0/bin/mobidb/2.0/binx/iupred/bin64/iupred_string[0x400fe1]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f5ff44cd555]
interproscan-5.64-96.0/bin/mobidb/2.0/binx/iupred/bin64/iupred_string[0x400c59]
======= Memory map: ========
00400000-00404000 r-xp 00000000 fd:03 75220331962                        interproscan-5.64-96.0/bin/mobidb/2.0/binx/iupred/bin64/iupred_string
00603000-00604000 rw-p 00003000 fd:03 75220331962                      interproscan-5.64-96.0/bin/mobidb/2.0/binx/iupred/bin64/iupred_string
00a04000-00a25000 rw-p 00000000 00:00 0                                  [heap]
7f5ff0000000-7f5ff0021000 rw-p 00000000 00:00 0
7f5ff0021000-7f5ff4000000 ---p 00000000 00:00 0
7f5ff4295000-7f5ff42aa000 r-xp 00000000 fd:00 1074175050                 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f5ff42aa000-7f5ff44a9000 ---p 00015000 fd:00 1074175050                 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f5ff44a9000-7f5ff44aa000 r--p 00014000 fd:00 1074175050                 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f5ff44aa000-7f5ff44ab000 rw-p 00015000 fd:00 1074175050                 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f5ff44ab000-7f5ff466f000 r-xp 00000000 fd:00 1073814048                 /usr/lib64/libc-2.17.so
7f5ff466f000-7f5ff486e000 ---p 001c4000 fd:00 1073814048                 /usr/lib64/libc-2.17.so
7f5ff486e000-7f5ff4872000 r--p 001c3000 fd:00 1073814048                 /usr/lib64/libc-2.17.so
7f5ff4872000-7f5ff4874000 rw-p 001c7000 fd:00 1073814048                 /usr/lib64/libc-2.17.so
7f5ff4874000-7f5ff4879000 rw-p 00000000 00:00 0
7f5ff4879000-7f5ff489b000 r-xp 00000000 fd:00 1073742413                 /usr/lib64/ld-2.17.so
7f5ff4a6f000-7f5ff4a72000 rw-p 00000000 00:00 0
7f5ff4a98000-7f5ff4a9a000 rw-p 00000000 00:00 0
7f5ff4a9a000-7f5ff4a9b000 r--p 00021000 fd:00 1073742413                 /usr/lib64/ld-2.17.so
7f5ff4a9b000-7f5ff4a9c000 rw-p 00022000 fd:00 1073742413                 /usr/lib64/ld-2.17.so
7f5ff4a9c000-7f5ff4a9d000 rw-p 00000000 00:00 0
7ffd09c88000-7ffd09cb8000 rw-p 00000000 00:00 0                          [stack]
7ffd09ccc000-7ffd09cce000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

But finally, we also get the output file  *dp.fasta.tsv.  Could you help us figure out the cause for this problem? Thanks!

**Comment by matthiasblum** [comment]
Hi @xingjianfeng100,

Any change you can share the input fasta file so I can try to reproduce the issue?

**Comment by xingjianfeng100** [comment]
> Hi @xingjianfeng100,
> 
> Any change you can share the input fasta file so I can try to reproduce the issue?

Thanks, but I finally abandoned the mobidb annotation, and it work successfully. It seems unnecessary to do mobidb annotation because I used interproscan only to perform GO and inter annotation.
