### ISSUE TITLE
Custom database path

### ISSUE THREAD

**Issue by mesti90** [ebi-pf-team/interproscan#337]
I'd like to install interproscan in a singularity container.
My goal is to install only the software, and in another step download the database to the server.
For this I should be able to feed interproscan a custom database path. Is it possible?
So interproscan.sh would be found in /usr/bin, and the ./data folder e.g. in /home/user/interpro/data

**Comment by matthiasblum** [comment]
Hi @mesti90,

We already provide a Docker image (https://hub.docker.com/r/interpro/interproscan/), which you can use with Singularity. 

This image expects the data directory to be in `/opt/interproscan/data`. You can bind paths to bind the path outside the container to `/opt/interproscan/data`.
