### ISSUE TITLE
Error running InterProScan (Unable to access jarfile interproscan-5.jar)

### ISSUE THREAD

**Issue by D-Git-Bit** [ebi-pf-team/interproscan#338]
Hi,

I am working remotely on a linux server where I have downloaded and uncompressed the .zip file. I followed the instructions in the doc and run the setup.py script with no problem. However, when i started the test run I got this message: "Error: Unable to access jarfile interproscan-5.jar". I cannot locate this jar file in my installation. How can I solve this problem?

Many thanks!

**Comment by matthiasblum** [comment]
Hi @D-Git-Bit,

Did you download the `.zip` file distributed on GitHub (e.g. listed at https://github.com/ebi-pf-team/interproscan/releases/tag/5.64-96.0)?

This file contains the source code and won't be able to run InterProScan. You need to download InterProScan from our FTP site. For the latest release, the link is https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.64-96.0/interproscan-5.64-96.0-64-bit.tar.gz
