### ISSUE TITLE
Problem with setting up port number for local lookup service

### ISSUE THREAD

**Issue by maglau** [ebi-pf-team/interproscan#34]
Hi,

I am trying to set up the port number to run the local lookup service. But it stated that some apps are missing. Are they essential? If the answer is yes, I need to find out whether I could install them on the HPC units.

cd /path-to-lookup_service_5.25-64.0
java -Xmx2000m -jar server-5.25-64.0-jetty-console.war --headless --port 9123
321 [main] INFO org.simplericity.jettyconsole.DefaultJettyManager - Added web application on path / from war /scratch/gpfs/maglau/lookup_service_5.25-64.0/server-5.25-64.0-jetty-console.war
321 [main] INFO org.simplericity.jettyconsole.DefaultJettyManager - Starting web application on port 9123
323 [main] INFO org.eclipse.jetty.server.Server - jetty-8.1.12.v20130726
1296 [main] INFO org.eclipse.jetty.plus.webapp.PlusConfiguration - **No Transaction manager found** - if your webapp requires one, please configure one.
3577 [main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - **NO JSP Support** for /, did not find org.apache.jasper.servlet.JspServlet
3601 [main] INFO / - **No Spring WebApplicationInitializer** types detected on classpath
3906 [main] INFO / - Initializing Spring root WebApplicationContext
Initializing BerkeleyDB Match Database (creating indexes): Please wait...

Thanks,
Maggie

**Comment by mifraser** [comment]
This is default output from Jetty, yes I see how too much information can be confusing! You can ignore these, the service should still start and these are just information messages (INFO). WARN or ERROR is what to look out for.

The service can take a while to start up. If you did "Testing the service" from https://github.com/ebi-pf-team/interproscan/wiki/LocalLookupService and you get data back then it is working as expected.

Kind regards,

Matt
