### ISSUE TITLE
Is it possible to extract representative domains from an interpro-scan run?

### ISSUE THREAD

**Issue by steven-pilger** [ebi-pf-team/interproscan#340]
According to this [tweet](https://twitter.com/interprodb/status/1707328292364157348), representative domains are now displayed on the protein page. I tried running interproscan-5.64-96.0 on a sequence that has representative domains in the EBI hosted version of interpro, but could not find a corresponding attribute in the generated output.xml file from my run using my local interpro.

Could you point me to some documentation that explains how these representative domains are selected, and how I could extract them from an interpro-scan run? Thanks!

**Comment by matthiasblum** [comment]
Hi @steven-pilger,

Representative domains are not yet available for InterProScan results. We'll soon publish a standalone script to extract these domains for InterProScan results.

**Comment by matthiasblum** [comment]
Hi @steven-pilger,

We want representative domains to be visible in InterProScan results on the InterPro website as well, so I am thinking about selecting representative domains directly in InterProScan, but that takes more time. I hope we'll have that ready for the next release of InterPro (mid January 2024).

**Comment by matthiasblum** [comment]
Hi @steven-pilger,

Representative domains are reported in the InterProScan XML and JSON output files. We added a `representative` boolean attribute/property which informs whether the match is a discontinuous domain.
