### ISSUE TITLE
error run InterProScan5.63-95 with Singularity Container

### ISSUE THREAD

**Issue by Liyong-Zhang** [ebi-pf-team/interproscan#341]
Hi there, 

I am trying to use InterProScan following (https://agbase-docs.readthedocs.io/en/latest/interproscan/using_iprs_cmd.html#running-interproscan-with-singularity-or-apptainer-on-hpc).

After downloading dabaset:
```
wget ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.63-95.0/alt/interproscan-data-5.63-95.0.tar.gz
wget ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.63-95.0/alt/interproscan-data-5.63-95.0.tar.gz.md5
md5sum -c interproscan-data-5.63-95.0.tar.gz.md
```

and pulling docker://agbase/interproscan:5.63-95 with Singluarity, I run with the following command:

 `singularity run -B ${workdir}:/data -B ${db}:/opt/interproscan/data interproscan_5.63-95.sif -i pep.fa -d $outdir -f tsv,json,xml,gff3
 -g -c -p -n biocurator -D database -x 90675 -l > "interproscan_Nov9.log" 2> "interproscan_Nov9.stderr"`

The error message is **"ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back."**

See details at the attached log file:
[interproscan_Nov9.log](https://github.com/ebi-pf-team/interproscan/files/13321401/interproscan_Nov9.log)

Please help me take a look when you get a chance.

Many thanks,
Liyong

**Comment by matthiasblum** [comment]
Hi @Liyong-Zhang,

Could you give our own [Docker image](https://hub.docker.com/r/interpro/interproscan/) a try? AgBase's image is not official, and seems to have different options, therefore limiting the help we can provide.

**Comment by Liyong-Zhang** [comment]
Hi Matthias,

Thanks for the suggestion.    I have already installed the original interproscan from (https://interproscan-docs.readthedocs.io/en/latest/) and run successfully.    I forgot to close this.  Sorry for the bother.

Liyong
