### ISSUE TITLE
Default parameter values on web interface?

### ISSUE THREAD

**Issue by suz11001** [ebi-pf-team/interproscan#343]
Hello, 

I am trying to determine what are default parameter values being used on the web interface? I am assuming the web interface parameter values match the values defined in [application-default.properties](https://github.com/ebi-pf-team/interproscan/blob/master/core/jms-implementation/src/test/resources/application-default.properties), but I would like to confirm this.
Additionally, for some parameters that are not defined in [application-default.properties](https://github.com/ebi-pf-team/interproscan/blob/master/core/jms-implementation/src/test/resources/application-default.properties), are the application's default values used? For example, for the smart database, the e-value cutoff is not defined in application-default.properties so is the default e-value 10 (as specified in hmmpfam)? Please let me know if I my questions is not clear.

Best,

Sumaira

**Comment by matthiasblum** [comment]
Hi @suz11001,

The web interface does not offer many options. The only optional parameters are:

- `appl`: which analyses (Pfam, CDD, SMART, etc.) are run (default: all)
- `goterms`: whether GO term annotations are included in the output (default: true)
- `pathways`: whether pathways annotations are included in the output (default: true)

All other parameters (e.g. e-value cutoffs) are taken from [application-default.properties](https://github.com/ebi-pf-team/interproscan/blob/master/core/jms-implementation/src/main/resources/application-default.properties) and [interproscan.properties](https://github.com/ebi-pf-team/interproscan/blob/master/core/jms-implementation/support-mini-x86-32/interproscan.properties).

Regarding missing values, you are correct. If they are not defined in configuration files, InterProScan runs the underlying applications with its default settings.

**Comment by suz11001** [comment]
Absolutely, this is the sequence:
> 402076
MVEAATEKAFAKRQKTTTSYVGIGRQVIESDDYNFSCSSEITTITYLLEQVGQKSLIDLALEEARTRDKEMDDKGSSAGNWSDIPGSSDKPDYSFRTADTAALSWSLVAFVMELKDELAEVYTECLGETTARLNAIKRAQSSRKFAYAESDEEEDKPEDQTGTQEQDSEAGKEENDSPRVERIGLPGDTQGTGPKAWYGKKRIRKEHLETFEKVFQRTKRPTGALIQNIVELTHVPRKRVLDWFENRRQEHAARRKDWELLISAELRRYPCLSMIRSKVGQSLTDVAVKICPGMDDELFVLGMLTEKKVAGVLPILYSGKLQNGDCYLVTRYCQQITLDMQAEAILSLARGVAMTLGRFSREGVVHGDVSIGNIVFGTDRHGGIHPYLVDFGSAVTGGLPVSFLRGGVSRATRQDGRAVSPTEAADRKTRCFSLESEFQEEVIDKCKRAGPVVAIRRLRDLFWKCGYNENVKVDQFMQCLI

I've also attached results from the latest inteproscan and our implementation (interflowscan). 

[interproscan-5.65-97.402076.txt](https://github.com/ebi-pf-team/interproscan/files/13619648/interproscan-5.65-97.402076.txt)
[interflowscan.402076.txt](https://github.com/ebi-pf-team/interproscan/files/13619649/interflowscan.402076.txt)

**Comment by matthiasblum** [comment]
InterProScan does not filter by e-value by default. But hits go through a post-processing.
