### ISSUE TITLE
How can I speed it up ?

### ISSUE THREAD

**Issue by qkqk-hub** [ebi-pf-team/interproscan#344]
Hello, thanks for developing interproscan

I now use the following code to run more than 9000 genome files, after calculation, I need more than 1000 days, although I use 40 cpus, but the speed is still very slow, how can I improve the speed? Thank you!

My requirement is to run all the analysis

The code is as follows:

`for i in *; do /data_alluser/interproscan-5.65-97.0/interproscan.sh -iprlookup -goterms -f TSV -i $i -o /data_alluser/09_Bacteria_interproscan/"$i"/"$i".ipscan -cpu 40; done`

In interproscan.properties I added the following line:

`hmmer3.hmmsearch.cpu.switch.pfam=40`

Thanks for reply

**Comment by matthiasblum** [comment]
Hi @qkqk-hub,

I'd recommend leaving `hmmer3.hmmsearch.cpu.switch.pfam` to its default value (`--cpu 1`) and run InterProScan with `-cpu 36` (36 "workers" + 1 master process). 
Also, if you're only interested in Pfam annotations, you can add `-appl pfam` to your command line: InterProScan will ignore all other analyses (PANTHER, CDD, etc.) and this will significantly decrease the time you'll need to annotate all your genomes.

We have a page on our documentation dedicated to performances, which might interest you: https://interproscan-docs.readthedocs.io/en/latest/ImprovingPerformance.html.

Best

**Comment by qkqk-hub** [comment]
Hi @matthiasblum ,

Thank you for your prompt reply

Although I added `hmmer3.hmmsearch.cpu.switch.pfam=40` to the interproscan.properties file, interproscan actually runs on 1 cpu, so far my commands are as follows:

1.hmmer3.hmmsearch.cpu.switch.pfam=40 was removed from  interproscan.properties by me

2.`for i in *; do ../interproscan-5.65-97.0/interproscan.sh -iprlookup -goterms -f TSV -i $i -cpu 20 -t n --disable-precalc -o ../interproscan33_result/"$i"/"$i".ipscan; done`

My requirement is to run all the analysis,But now I can only annotate one genome file per hour on average:

![1](https://github.com/ebi-pf-team/interproscan/assets/54273704/48ed115c-b967-4671-9412-404afd852c53)

I have 48 cpus,Is there any other way to improve the running speed?

Best

**Comment by matthiasblum** [comment]
Chunking your input files might help, especially when using nucleic acid sequences. In this case, try to limit input to ~10k sequences/file. And if you have 48 CPUs, you can use something like `-cpu 45` when starting InterProScan, so more tasks are run in parallel.

On a side note, the value `hmmer3.hmmsearch.cpu.switch.pfam` should be `--cpu N` (with `N` being the number of worker threads for HMMER to use), not just `N`.

**Comment by qkqk-hub** [comment]
Ok, I see. Thank you for your guidance. I'll bother you again if there are any new questions. Thanks again!
