### ISSUE TITLE
Implementation of Prosite and Panther

### ISSUE THREAD

**Issue by suz11001** [ebi-pf-team/interproscan#345]
We have an implementation of interproscan designed to work with other dbs and also within our workflow services system. There are two things we need to make sure. 
1. ps_scan.pl (used for prosite) will no longer work for the current data structure of prosite correct? Now that the profiles are scattered across various files and not packaged in prosite_profiles.dat or prosite.dat, we need to execute runprosite.py?
2. How is interproscan currently executing Panther? It seems that the data available for panther in the interproscan package is limited and pather_score.pl has become obsolete? This is our best guess as to what interproscan doing regarding panther, please let us know if we are close or completely off: 
`hmmsearch -Z 65000000 -E 0.001 --domE 0.00000001 --incdomE 0.00000001 --notextw -o hmmerout.raw --domtblout tblout \ data/panther/18.0/famhmm/binHmm fasta.in`
`python bin/panther/treegrafter.py run fasta.in hmmerout.raw data/panther/18.0/ -o panther.out.out --epa-ng bin/panther/epa-ng -T /tmp/ -e 0.00000001 --keep`

Your guidance is much appreciated!

**Comment by matthiasblum** [comment]
### PROSITE

PROSITE is split between _Patterns_ and _Profiles_:

#### PROSITE Patterns

Uses `ps_scan.pl`, which is a Perl wrapper for `pfscan`.

```sh
perl ps_scan.pl -d prosite_patterns.dat --pfscan pfscanV3 -b evaluator.dat -r -s -o input.fasta
```

#### PROSITE Profiles

Uses `runprosite.py`, which is a Python wrapper for `pfsearch`.

```sh
python runprosite.py prosite_profiles input.fasta output.txt pfsearchV3 -f -o 7
```

### PANTHER

The commands you pasted seem correct. Basically we now use our own implementation of [TreeGrafter](https://academic.oup.com/bioinformatics/article/35/3/518/5056037), a phylogenetic tree-based method to annotate protein (developed by PANTHER) where we first identify the best homologous family (with `hmmsearch`), then graft the sequence to an annotated family tree with `treegrafter.py`, which itself calls `EPA-ng`.
