### ISSUE TITLE
Inquiry on the interproscan.properties file

### ISSUE THREAD

**Issue by sanalbert** [ebi-pf-team/interproscan#347]
Hello, thanks for the great tool!

I have downloaded the latest version of InterProScan (`interproscan-5.65-97.0`) and trying to recompile `Pfscan/Pfsearch` following the [documentation](https://interproscan-docs.readthedocs.io/en/latest/CompilingBinaries.html#pfscan-pfsearch-used-by-prosite-profiles-prosite-patterns-and-hamap)

It says to update the paths in the `interproscan.properties` file as follows:

```
binary.prosite.pfscan.path=bin/prosite/pfscan
binary.prosite.pfsearch.path=bin/prosite/pfsearch
```

Unfortunately, my `interproscan.properties` file does not seem to have an initial `binary.prosite.pfscan.path=` or `binary.prosite.pfsearch.path=` - I cannot find this anywhere in the file.

The `md5sum` check went OK so I believe I have downloaded the right file, but may be there a problem with the file?
Or, how should I specify the updated pfscan/pfsearch path for my InterProScan?

Thank you for your support.

**Comment by tgrego** [comment]
Hi, apologies for the delay
indeed the interproscan.properties file has gone through some cleanup and many properties have been updated and/or moved.
In the case of prosite binaries, they are now by default:
```
binary.prosite.pfscanv3.path=${bin.directory}/prosite/pfscanV3
binary.prosite.pfsearchv3.path=${bin.directory}/prosite/pfsearchV3
```

You may add those properties to your interproscan.properties file to override the default values.
I will update the documentation to reflect this.
