### ISSUE TITLE
Possibility to run whole genome protein domain scanning?

### ISSUE THREAD

**Issue by BitaoQiu** [ebi-pf-team/interproscan#356]
Dear Interproscan developers,

I wonder if it's possible to scan protein domains at a whole genome scale instead of proteins/nucleotides? Rfam and Infernal can do this, and I guess it should be possible for Interpro (with all six frames and ignore potential introns)?

**Comment by matthiasblum** [comment]
Hi @BitaoQiu,

Sorry for the late reply.

InterProScan can annotate entire genomes. Use `-t n` to run InterProScan in nucleic acid mode. In this node, each DNA or RNA sequence is translated into six ORFs before being annotated.
