### ISSUE TITLE
Command line Flag indicating the DataBase path?

### ISSUE THREAD

**Issue by cmeesters** [ebi-pf-team/interproscan#360]
Hi,

It appears that interproscan does expect its database to be unpacked in the software installation directory (or linked therein). Wouldn't it be more user-friendly to have a flag pointing to the database location? 

Thanks for your consideration.

**Comment by matthiasblum** [comment]
Hi @cmeesters,

You can define a custom path by editing the `interproscan.properties` file in InterProScan's directory. The `data.directory` property defines the path where InterProScan looks for data files.

**Comment by cmeesters** [comment]
Hi Matthias,

Thank you. In a scenario, where a software on a multiuser system is installed globally, editing configuration file post installation is possible, yet smelly. Hence my question.

**Comment by matthiasblum** [comment]
On a multi-user system, such as an HPC, users can have a copy of `interproscan.properties` in `${HOME}/.interproscan-5/ `. Any property defined there will override the default property defined in the global `interproscan.properties` located in InterProScan's directory.
