### ISSUE TITLE
assorted errors

### ISSUE THREAD

**Issue by jasonwjohns** [ebi-pf-team/interproscan#361]
Hi,

I am trying to run Interproscan on an hpc and I am getting various errors. I have included both the errLog and outLog files below. When I run ./interproscan.sh I get:

`Welcome to InterProScan-5.67-99.0
04/05/2024 09:41:35:959 Running InterProScan v5 in STANDALONE mode... on Linux
usage: java -XX:+UseParallelGC -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Xms128M
            -Xmx2048M -jar interproscan-5.jar`

Previously I was getting an error associated with pfscan/pfsearch, so I installed the "ps_scan_linux_x86_elf.tar.gz" binaries from Expasy and updated the interproscan.properties values as directed. Given my errors below, I'm wondering if you would recommend doing the same for fingerPRINTSscan and hhmer3? As you can see, there was also an error for pfscan with the invalid option -- 'l'. Maybe you can help resolve this as well?

I'm posting now in hopes that you can help guide my troubleshooting and cut it down, as I have some hours into it already at this point. I'm pretty novice when it comes to software configuration and the nitty gritty of computers in general. Thank you in advance for any guidance you can provide!

Jason

**errLog**
[errLog.txt](https://github.com/ebi-pf-team/interproscan/files/15210397/errLog.txt)

**outLog**
[outLog.txt](https://github.com/ebi-pf-team/interproscan/files/15210398/outLog.txt)

**Comment by matthiasblum** [comment]
Hi @jasonwjohns,

You can give our [Docker image](https://hub.docker.com/r/interpro/interproscan/) a try. This way, you shouldn't have any dependency issues.
