### ISSUE TITLE
when run the interproscan, its error like this perl: symbol lookup error: /usr/lib64/perl5/auto/IO/IO.so: undefined symbol: Perl_xs_apiversion_bootcheck

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [ebi-pf-team/interproscan#362]
Error output from binary:
perl: symbol lookup error: /usr/lib64/perl5/auto/IO/IO.so: undefined symbol: Perl_xs_apiversion_bootcheck
![image](https://github.com/ebi-pf-team/interproscan/assets/101324838/d994a41a-bd82-4f17-8943-ff458035eb8a)
what is the error

**Comment by tgrego** [comment]
Hello
that indicates an issue with your perl installation, likely a clash of different perl installs.
you can try to solve that or you can try running interproscan via a container
https://interproscan-docs.readthedocs.io/en/latest/HowToUseViaContainer.html
