### ISSUE TITLE
Something goes wrong when I use interproscan Help me plz. ERROR - StepExecution with errors - stepName: stepPantherRunHmmer3 |Error output from binary:

### ISSUE THREAD

**Issue by helloworldABCD1234** [ebi-pf-team/interproscan#364]
Something goes wrong when I use interproscan Help me plz

ERROR - StepExecution with errors - stepName: stepPantherRunHmmer3

Error output from binary:
munmap_chunk(): invalid pointer ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back

When the program reaches 70%, an error occurs, and then the program continues to run. After 78%, there is no further increase in progress. Continuous for 8 hours without increasing progress

![interpproscan2](https://github.com/ebi-pf-team/interproscan/assets/63828474/57406cf0-7414-48b8-83df-ec12838144d6)
![interproscan1](https://github.com/ebi-pf-team/interproscan/assets/63828474/bd7fb119-82e9-4484-98aa-d8bc9c093afc)

**Comment by matthiasblum** [comment]
Hi @helloworldABCD1234,

How big is your input file? Can you paste the command you submitted? Can you give try to process your sequences with our [Docker image](https://hub.docker.com/r/interpro/interproscan/)?
