### ISSUE TITLE
Error when executing InterProScan

### ISSUE THREAD

**Issue by Kash-Pandz** [ebi-pf-team/interproscan#365]
Hi,

I tried to run InterProScan and I got the below error. Any idea on why I'm getting this? 

![image](https://github.com/ebi-pf-team/interproscan/assets/86837869/934359ef-0c5d-4691-96fe-6c46eaa06af8)

Thank you!

**Comment by tgrego** [comment]
you can try recreating the index files, it might have gotten corrupted
`python3 setup.py -f interproscan.properties`
