### ISSUE TITLE
error in using iprscan5.py

### ISSUE THREAD

**Issue by zhengyanstu** [ebi-pf-team/interproscan#367]
Dear Developers:
I encount error when I try to annotate protein sequences using interproscan5 api.
Here are my codes:
python iprscan5.py --multifasta test.fasta  --email xxx@gmail.com --outformat tsv --maxJobs 25 --useSeqId
but it shows:"/nfs/public/rw/es/projects/wp-jdispatcher/sources/prod/jobs/iprscan5/rest/20240603/0600/iprscan5-R20240603-060113-0892-16016260-p1m.params (No such file or directory)"
Could you help me solving this problem? thank you.

test.fasta:
>nad4
MLEHFCECYSDLSGLILCPVLGSITPLFIPNSRIRPIRLIGLCASLITFLYPPVLRIQFDPSTAKSQFVESLRWLPYENINFDLGIDGISLFFVILTTFLIPICISVGWSGMRSYGKEYITASLIREFLMIAVFRILDPLLFYVFPESVPIPMFIIIGVWGSRQRKIKAAYQFFLYTLLGSVFMLLAILLILFQTGTTDLQILLTTEFSERRQIFLWIAFFASFAVKVPMVPVHIWLPEAHVEAPTAGSVILAGILLKLGTYGFLRFSIPMFPEATLCFTPFIYTLSAIAIIYTSLTTLRQIDLKKIIAYSSVAHMNLVTIGMFSLNIQGIGGSILLMLSHGLVSSALFLCVGVLYDRHKTRLVRYYGGLVSTMPNFSTIFLFLTLANMSLPGTSSFIGEFLILVGAFQRNSLVATLAALGMILGAAYSLWLYNRVVSGNLKPSFLHKFSDPNGREVSIFIPFLVGVVRMGVHPKVFPDRMHTSVSNLVQHGKFH
>atp6-fragment
LIHKFICLYAANSKFSHTLLHSY
>nad2-fragment
MFNLFLAVSPEIFIINATFILLIHGVVFSTSKKLDYPPLVSNVGWLGLLSVLITLLLLAAGAPLLTIAHLFWNNLFRGDNFTYFCQILLLLSTAGTISMCFDSSEQERFDASESIVLIPLPTRSMLFMILAHDSIAMYLAIEPQSLCFYVIAASKRKSEFSTEAGSKYLILGAFSSGILLFGFGLWGLLPSLPLSLLHSFHIPLLCSQLL
>rpl5-fragment
NEFEIFEHIRGFNVTIVTSANTQDETLPPWSGF
>atp8-fragment
MPQLDNSHNSSGHAFSSLLSIFP
>rps1
MMSIYLSRSFPRSNSSFFLCSGNALQSSVLRLREEMFLVDAGPGTPRICMQDEPTGVPINRATRFENKVGSLDLVAGESLIKEQILERFFIDLVAGESLIKERAAARFNDLVGSTDVVAGEPLLLLPRRFRQNRAWMELNKIWRTNTKVKGFIIEKGKGGYSVAIAGFITFLPFRPLISQRISNDRFTIESINPKRTNIVVF
>nad5-fragment
PLSNFWANSPFVLPKNEILAESEFAAPTITKLIPIPFSTSGASVAYNVNPVADQFQRAFQTSTFCNRLYSFFNKRWFFDQVLNDFLVRSFLRFGYEVSFEALDKGAIEILGPYGISYTFRRLVERISQLQSGFVYHYAFAMLLGLTLFVTFSRMWDSLSSWVGNRAYFIWIVITFYNNKSSQE
>ccmFc
MVQLHNFFFFITSMVVPRGTAAPVLLKWFVSRDVPTGAPSSNGTIIPIPIPSFPLLVYLHSRKFIRPTDGAKSGVLVRASRPILLPDIIGRSSSETRERNASFRFVPVLNFLLLQSKGDFSYLESFCGVFRLLLFRTFFFLPRDRSAKRERARRRKGQTLRPNGNEQRRNDKMRCPGHPHLERRIDGFGPVAFPVPPSSGGPCVGGAPPSIGLEALALPTSRQLMAVGHDYYQKAPIKIHISHGGVCICMLGVLLSNTKKIEFTQRLPLGSELYMEKERCSLRGLDHLHGPTFHSICGNFMIYKPSLTNDRLMLKDEHDESLRADLLPINFPASYENGKLEHFLHRWMKNLEHKNFWLTMFLENRNFRETTSTTEVAIHTNPFTDLYASIGTSSSRTCGWYTTIMKLPFIFFIWIGFMLASLGGSRSLLRQLQKDKLRWNRESSVELIIA
>cox2
MIVLEWLFLTIAPCDAAEPWQLGSQDAATPTMQGIIDLHHDIFFFLILIFVFVSRILVRALWHFHYKRNPIPQRIVHGTTIEILRTIFPSIIPMFIAIPSFALLYSMDEVVVDPAITIKAIGHQWYRTYEYSDYNSSDEQSLTFDSYTIPEDDPELGQSRLLEVDNRVVVPAKIDLRIIVTPADVPHSWAVPSSGVKCDAVPGRLNQTSISVQREGVYYGQCSEICGTNHAFTPIVVEAVPRKDYGSRVSNQLIPQTGEA
>ccmC
MSVSLLQPSFLMSKTRSYAQILIGFRLFLTAMAIHLSLRVAPLDLQQGGNSRIPYVHVPAARMSILVYIATAINTFLFLLTKHPLFLRSSGTGTEMGAFSTLFTLVTGGFRGRPMWGTFRVWDARLTSVFISFLIYLGALRFQKLPVEPAPISIRAGPIDIPIIKSSVNWWNTSHQPGSISRSGTSIHVPMPIPILSNFANSPFSTRIFFVLETRLPIPSFLESPLTNKIEAREGIPKPSSLAESLCIHD
>atp4
MRLSSTNMQARKMLFAAILSICASSSKKISIYNEEMIVARCFIGFIIFSRKSLGKTFKVTLDGRIQAIQEESQQFPNPNEVVPPESNEQQRLLRISLRICGTVVESLPMARCAPKCEKTVQALLCRNLNVKSATLPNATSSRRICLQDDLVTGFHFSVSERFVPGCTLKASIVELIREGLAVLRMVRVGGFS
>nad4L
MIISISGIRGILLNRRNIPIMSMPIESMLLAVNSNFLVFSVSSDDMMGQSFASLVPTVAAAESAIGSAIFVITFRVRGTIAVESINSIQG
>cox1-fragment
SISLSAVDSAISSLHLSGTFIITSGTGTDCYH

**Comment by tgrego** [comment]
Hello,
your fasta file in invalid, the description lines need to start with a '>' character (for example, `>nad4` should be the first line).
With an updated fasta file you can run:
`python iprscan5.py --sequence test.fasta --email xxx@gmail.com --outformat tsv`
and you should get the expected result.
