### ISSUE TITLE
Deactivated analyses

### ISSUE THREAD

**Issue by Paolopab** [ebi-pf-team/interproscan#368]
Hello everyone,

After installing InterProScan and placing Phobius, SignalP, and TMHMM in the folders required by InterPro, the following analyses still appear to be disabled:

Deactivated analyses: SignalP_GRAM_NEGATIVE (4.1) : Analysis SignalP_GRAM_NEGATIVE is deactivated, because the resources expected at the following paths do not exist: bin/signalp/4.1/signalp TMHMM (2.0c) : Analysis TMHMM is deactivated, because the resources expected at the following paths do not exist: bin/tmhmm/2.0c/decodeanhmm, data/tmhmm/2.0c/TMHMM2.0c.model SignalP_EUK (4.1) : Analysis SignalP_EUK is deactivated, because the resources expected at the following paths do not exist: bin/signalp/4.1/signalp Phobius (1.01) : Analysis Phobius is deactivated, because the resources expected at the following paths do not exist: bin/phobius/1.01/phobius.pl SignalP_GRAM_POSITIVE (4.1) : Analysis SignalP_GRAM_POSITIVE is deactivated, because the resources expected at the following paths do not exist: bin/signalp/4.1/signalp

How can I solve this?

**Comment by tgrego** [comment]
Hello,
can you please confirm the files shown on the error message exist as expected in your InterProscanDir?
InterProscanDir/bin/signalp/4.1/signalp
InterProscanDir/bin/tmhmm/2.0c/decodeanhmm
InterProscanDir/data/tmhmm/2.0c/TMHMM2.0c.model
InterProscanDir/bin/phobius/1.01/phobius.pl

Interproscan will need those files in order to activate the analyses.

**Comment by Paolopab** [comment]
Hello thank you,
interproscan-5.68-100.0/bin/signalp/4.1/signalp

interproscan-5.68-100.0/bin/signalp/4.1/signalp$ ls

conversion_utils  make_output_files.py   predict.py
__init__.py       make_sequence_plot.py  sequential_model.py
__main__.py       model_weights          utils.py

interproscan-5.68-100.0/bin/phobius/1.01

interproscan-5.68-100.0/bin/phobius/1.01$ ls

decodeanhmm        OPSD_SHEEP           phobius.model    phobius.pl  README
decodeanhmm.64bit  phobius_install.txt  phobius.options  Q8TCT8

interproscan-5.68-100.0/bin/tmhmm/2.0c

interproscan-5.68-100.0/bin/tmhmm/2.0c$ ls

decodeanhmm.Linux_i386  decodeanhmm.Linux_ia64    TMHMM2.0.model     tmhmm.ORIG
decodeanhmm.Linux_i486  decodeanhmm.Linux_x86_64  TMHMM2.0.options
decodeanhmm.Linux_i586  tmhmm                     tmhmmformat.pl
decodeanhmm.Linux_i686  TMHMM1.0.model            tmhmm_install.txt


interproscan.properties:

# Binary file locations (required for setup.py)
binary.hmmer3.path=${bin.directory}/hmmer/hmmer3/3.3
phobius.signature.library.release=1.01
binary.phobius.pl.path=bin/phobius/1.01/phobius.pl

signalp_euk.signature.library.release=4.1
signalp_gram_positive.signature.library.release=4.1
signalp_gram_negative.signature.library.release=4.1
binary.signalp.path=bin/signalp/4.1/signalp
signalp.perl.library.dir=bin/signalp/4.1/lib

tmhmm.signature.library.release=2.0c
binary.tmhmm.path=bin/tmhmm/2.0c/decodeanhmm

tmhmm.model.path=data/tmhmm/2.0c/TMHMM2.0c.model

is it correct?

**Comment by tgrego** [comment]
No, there are some mixups in the files...

For tmhmm, all files are currently in bin/tmhmm/2.0c
the file bin/tmhmm/2.0c/TMHMM2.0.model needs to be in data/tmhmm/2.0c/TMHMM2.0.model
`mv bin/tmhmm/2.0c/TMHMM2.0.model data/tmhmm/2.0c/TMHMM2.0.model`
Also the binary to be used is bin/tmhmm/2.0c/decodeanhmm, which does not exist. You'll need to rename the appropriate one for your system (usually Linux_x86_64) to the correct name
`cp bin/tmhmm/2.0c/decodeanhmm.Linux_x86_64 bin/tmhmm/2.0c/decodeanhmm`
That should be all to activate tmhmm.

For signalp, the files should be directly under bin/signalp/4.1/ (not bin/signalp/4.1/signalp).
there should be a `bin/signalp/4.1/signalp` file (the binary) and also a `bin/signalp/4.1/lib/` (that should contain a FASTA.pm file).

For phobius the required binaries need to be in `bin/phobius/1.01/` so that actually seems correct

**Comment by Paolopab** [comment]
It seems that I installed SignalP 6, while InterProScan was looking for SignalP 4.1. 

Once SignalP 4.1 was installed, I ran this command: 
./interproscan.sh -i test_all_appl.fasta -f tsv -dp 
I got this error: - Command line failed with exit code: 2
Command: perl bin/signalp/4.1/signalp -T 
Error on binary output:
Can't locate FASTA.pm in @INC (may need to install FASTA module).
I did: nano bin/signalp/4.1/signalp
use strict;
use lib 'bin/signalp/4.1/lib';
After this,
chmod +x bin/signalp/4.1/signalp
./interproscan.sh -i test_all_appl.fasta -f tsv -dp
output:
 - Command line failed with output code: 2
Command: perl bin/signalp/4.1/signalp -T 
Error on binary output:
File /usr/opt/www/pub/CBS/services/SignalP-4.1/signalp-4.1/bin/nnhowplayer.Linux_x86_64 cannot be found. at bin/signalp/4.1/signalp line 49.

nano bin/signalp/4.1/signalp.
my $nnhowplayer = 'bin/signalp/4.1/bin/nnhowplayer.Linux_x86_64';
chmod +x bin/signalp/4.1/bin/nnhowplayer.Linux_x86_64

(base) user@user:~/interproscan-5.68-100.0$ ./interproscan.sh -i test_all_appl.fasta -f tsv -dp
17/06/2024 16:09:10:414 Benvenuti in InterProScan-5.68-100.0
17/06/2024 16:09:10:415 Esecuzione di InterProScan v5 in modalità STANDALONE... su Linux
17/06/2024 16:09:12:986 RunID: user_20240617_160912909_i41h
17/06/2024 16:09:18:401 Loading file /home/user/interproscan-5.68-100.0/test_all_appl.fasta
17/06/2024 16:09:18:402 Running the following analyses:
[AntiFam-7.0,CDD-3.20,Coils-2.2.1,FunFam-4.3.0,Gene3D-4.3.0,Hamap-2023_05,MobiDBLite-2.0,NCBIfam-14.0,PANTHER-18.0,Pfam-37.0,Phobius-1.01,PIRSF-3.10,PIRSR-2023_05,PRINTS-42.0,ProSitePatterns-2023_05,ProSiteProfiles-2023_05,SFLD-4,SignalP_EUK-4.1,SignalP_GRAM_NEGATIVE-4.1,SignalP_GRAM_POSITIVE-4.1,SMART-9.0,SUPERFAMILY-1.75,TMHMM-2.0c]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
17/06/2024 16:25:34:509 26% completed
17/06/2024 16:25:48:880 51% completed
17/06/2024 16:26:04:814 77% completed
17/06/2024 16:26:12:499 91% completed
17/06/2024 16:26:34:686 100% done:  InterProScan analyses completed 

Now, if I use the following command:
interproscan.sh -i /home/user/file.faa -f tsv,gff3 -goterms -d /home/results/ -pa -cpu 28 -t p
The output is:
2024-06-17 16:28:57,977 [amqEmbeddedWorkerJmsContainer-20] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:216] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 1
Command: bin/hmmer/hmmer3/3.3/hmmsearch -Z 65245 -E 0.001 --cpu 1 -o /home/user/interproscan-5.68-100.0/temp/user_20240617_162843616_9eqv//jobFunFam/000000004001_000000005357.raw.out data/gene3d/4.3.0/gene3d_main.hmm /home/user/interproscan-5.68-100.0/temp/user_20240617_162843616_9eqv//jobFunFam/000000004001_000000005357.fasta 
Error output from binary:

Thank you so much for the support!!
Error: File format problem in trying to open HMM file data/gene3d/4.3.0/gene3d_main.hmm.
Opened data/gene3d/4.3.0/gene3d_main.hmm.h3m, a pressed HMM file; but format of its .h3i file unrecognized

**Comment by tgrego** [comment]
great, looks like you got signalp to work. Indeed it needs to be version 4.1

The error you're getting regarding gene3d indicates that something went wrong pressing the hmm files.
You can repress them by running in the interproscan install dir:
`python3 setup.py -f interproscan.properties`

**Comment by Paolopab** [comment]
It didn't work, but 
rm data/gene3d/4.3.0/gene3d_main.hmm.h3*
bin/hmmer/hmmer3/3.3/hmmpress data/gene3d/4.3.0/gene3d_main.hmm
nano interproscan.properties
gene3d.hmm.library.path=data/gene3d/4.3.0/gene3d_main.hmm
It works
Thank you very much for your helpfulness and kindness! I wish you the best :)
