### ISSUE TITLE
README.md update - could you perhaps add some information about the programming language(s) used and required?

### ISSUE THREAD

**Issue by ghost** [ebi-pf-team/interproscan#37]
Hello ebi-team for InterProScan!

A suggestion:

README.md update - could you perhaps add some information about the programming language(s) used and required?

The reason why I ask is that you mention that linux is the primary target platform, but the readme is a bit sparses. For example, I am wondering which programming language(s) are used. I ask that in particular because I am used to the C/C++ family, also python (ncbi-blast+, relion, viennarna etc...) but not so used to Java. So I'd like to know, if possible, beforehand downloading the source. Please do feel free to close this issue at any moment in time - thank you!

**Comment by gsn7** [comment]
refer to https://github.com/ebi-pf-team/interproscan/wiki/InstallationRequirements
