### ISSUE TITLE
How to configure local lookup service? 

### ISSUE THREAD

**Issue by zyh4482** [ebi-pf-team/interproscan#370]
For example, I downloaded the lookup service file under `/data/InterProscan`. 

Then, how should I configure `precalculated.match.lookup.service.url` to make it use the local file? 

Thank you very much.

**Comment by tgrego** [comment]
Hello,
after you start the local service you need to configure interproscan to use it.
You can find the full instructions at:
https://interproscan-docs.readthedocs.io/en/latest/LocalLookupService.html
