### ISSUE TITLE
Activating Phobius/SignalP/TMHMM analyses in singularity image

### ISSUE THREAD

**Issue by Artifice120** [ebi-pf-team/interproscan#373]
Afternoon,

Thank you for creating a docker image of this program. I have successfully used your singularity image in the past. Unfortunately, I noticed there does not seem to be a direct way of adding  Phobius,SignalP, and TMHMM analysis to the image as the config file in the container is read-only.

Is there another way to add the Phobius, SignalP, and TMHMM analysis to the singularity image?

**Comment by matthiasblum** [comment]
Hi @Artifice120,

The config file will be modified for the next release of InterProScan, so licensed components (Phobis, SignalP, TMHMM) are expected to be mounted from outside the container.

I'll leave this issue open until the release. Once the new version of InterProScan is released, I'll update this issue before closing it.

**Comment by Artifice120** [comment]
No worries,

Ended up just installing from the source with a conda environment to hold its dependencies and downloaded the other components repeatable. 

Good to know I did'nt miss something on my end.

**Comment by matthiasblum** [comment]
@Artifice120, we released InterPro 102.0 and InterProScan 5.70-102.0. The latest [Docker image](https://hub.docker.com/r/interpro/interproscan) supports the licensed components (Phobius, SignalP, TMHMM). They are not included, but it's easy to activate them.
