### ISSUE TITLE
Descriptions missing for some CDD matches

### ISSUE THREAD

**Issue by kimrutherford** [ebi-pf-team/interproscan#385]
Hi.  Thanks for InterProScan.  It's working very well for PomBase.

We've noticed that for some CDD matches, the the long description that's available on the InterPro web pages isn't included the InterProScan JSON output.

An example is `cd15474` on the page for `myo51`: https://www.ebi.ac.uk/interpro/protein/reviewed/O74805/
In the InterProScan (v5.70-102.0) output for myo51 the name and description are "Myo5p-like_CBD_fungal":

```json
          "signature": {
            "accession": "cd15474",
            "name": "Myo5p-like_CBD_fungal",
            "description": "Myo5p-like_CBD_fungal",
            "signatureLibraryRelease": {
              "library": "CDD",
              "version": "3.20"
            },
            "entry": null
          }
```

The InterPro website has a longer description:
"cargo binding domain of fungal myosin V -like proteins"

https://www.ebi.ac.uk/interpro/protein/reviewed/O74805/
![image](https://github.com/user-attachments/assets/cbf07a57-8aed-40fc-9363-0725ed0ce6f2)

Would it be possible to include the long description from CDD in the JSON output?

Another example is `cd00174` where the name and description in the JSON are "SH3" but the website has the long description:

https://www.ebi.ac.uk/interpro/protein/reviewed/Q09822/
![image](https://github.com/user-attachments/assets/caaa0320-2501-44fc-bcdc-0a048df52959)

Thanks in advance.

CC: @ValWood

**Comment by matthiasblum** [comment]
Hi @kimrutherford,

I am afraid that it's not something we can easily do for the current implementation of InterProScan. However, we are working on a new implementation, and the long descriptions will be included in the JSON/XML outputs. We hope to release a beta later this year or in January.

**Comment by kimrutherford** [comment]
Thanks for the reply @matthiasblum 

We are very happy to help with beta testing of the new version when it is available.
