### ISSUE TITLE
Individual interproscan.properties files

### ISSUE THREAD

**Issue by rchui** [ebi-pf-team/interproscan#39]
The way our system is setup does not allow users to make changes to software installed on the system. They simply use the tools that we set up for them. Therefore they are unable to edit the interproscan.properties file for their individualized run, and multiple copies of interproscan need to be installed for each users's needs. To work around this we introduced a simple change that allowed them to set an environmental variable which would point towards their file.

In interproscan-5.jar, there is a file spring/spring-properties-context.xml. In the block
```
<property name="locations">
  <list>
    <value>file:interproscan.properties</value>
    <value>file:${user.home}/.interproscan-5/interproscan.properties</value>
    <value>file:${system.interproscan.properties}</value>
  </list>
</property>
```

we added
```
<value>file:${INTER_CONFIG_DIR}/interproscan.properties</value>
```

so that if you set
```
export INTER_CONFIG_DIR=/absolute/path/to/directory/with/interproscan.properties
```

it would run off of an editable version of interproscan.properties. If possible, it would be nice if this feature could be included in the official version of interproscan.

**Comment by gsn7** [comment]
<value>file:${user.home}/.interproscan-5/interproscan.properties</value> should work fine for you as well. the user can add the properties specific for them in .interproscan-5/interproscan.properties file

**Comment by jfass** [comment]
@rchui That's really helpful, because in our cluster environment there are currently some issues with tokens providing access to one's home directory. Most people are working in nfs-shared working directories, though, where it would be useful to put specific interproscan.properties files specific to the project being worked on.

**Comment by jfass** [comment]
It's funny, though, @rchui  ... I still see my home directory being checked ... it's like IPS is checking all locations in that list, when I would think it would check the local directory first, then only if it doesn't find a properties file would it move down the line.

**Comment by gsn7** [comment]
the behaviour of interproscan wrt to property files:
the default properties file is interproscan.properties (1).
if ${user.home}/.interproscan-5/interproscan.properties (2)  exists, any properties defined there will override those in 1
if ${system.interproscan.properties} (3) exists, any properties defined there will override those in 1 and 2

**Comment by jfass** [comment]
What does the location of (1) need to be? The directory that interproscan.sh and/or the jar file are in? The pwd from where the shell script is called?

**Comment by gsn7** [comment]
its the directory that interproscan.sh and/or the jar file are in.
