### ISSUE TITLE
Using interproscan on a HPC Cluster

### ISSUE THREAD

**Issue by samfux84** [ebi-pf-team/interproscan#4]
on HPC cluster, databases often have to be separated from the installation directory of a software. Is it possible to store the data directory of interproscan in a different location outside the installation directory ?

**Comment by mifraser** [comment]
Hi!

Yes, you can use a different data directory if you update your interproscan.properties file too. E.g. if you search the properties file for "=data/" you'll find various properties like "pfam-a.hmm.path=data/pfam/28.0/pfam_a.hmm" which would all need updating to point at the new location.

Kind regards,

Matt
