### ISSUE TITLE
Installing 5.26-65.0 on an old Centos6 HPC

### ISSUE THREAD

**Issue by maxf130** [ebi-pf-team/interproscan#42]
Hi,

as the title suggests, I'm trying to install interproscan on an old (-ish) centos 6 based cluster.  

 I've recompiled a number of the included binaries to work with our older version of GLIBC as expected.  I wasn't successful in compiling 'cath-resolve-hits' from source, but the centos6 pre-compiled binary seems to work just fine.  I also applied the fix for that mentioned in issue #25.

However that fix appears not to have worked.  The stacktrace from Java is kind of overwhelming, but I think this is the relevant part:

    $ interproscan.sh -i /path/to/some/.faa/file -f tsv
    2017-11-08 16:23:57,741 [amqEmbeddedWorkerJmsContainer-8] uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:199] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
    java.lang.IllegalStateException: IOException thrown when attempting to parse /ibers/ernie/home/maf54/temp/bert_20171108_162240951_ak7l//jobGene3d/000000000001_000000000011_one.raw.out
        at uk.ac.ebi.interpro.scan.management.model.implementations.gene3d.Gene3DParseAndPersistOutputStep.execute(Gene3DParseAndPersistOutputStep.java:117)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
    .
    .
    .
    .

I'm somewhat out of ideas.  I've attached the full output if it is of interest.
[interproscan_out.txt](https://github.com/ebi-pf-team/interproscan/files/1454626/interproscan_out.txt)

**Comment by gabo-ing** [comment]
It could be something related to Gene3d analysis, what about if you run interproscan but disabling that particular analysis?

**Comment by maxf130** [comment]
Disabling Gene3d analysis removes that issue.  My understanding is that `cath-resolve-hits` is involved in the gene3d analysis, so that makes sense.  Any idea on how to fix that?

**Comment by mifraser** [comment]
It could be a version issue as InterProScan is designed to work with a certain version of cath-resolve-hits. Did you download using these instructions with these version numbers? https://github.com/ebi-pf-team/interproscan/wiki/KnownIssues#1-cddrpsblast-gene3d-and-sfld-errors-on-older-or-new-systems

Thanks,

Matt

**Comment by maxf130** [comment]
I tried that version also:
```
$ interproscan/5.26-65.0/bin/gene3d/4.1.0/cath-resolve-hits --version
============
cath-resolve-hits v0.12.26-0-g6b4524f [2017-03-09]
============
```

```
$ interproscan.sh --version
InterProScan version 5.26-65.0
```

But that didn't behave differently.

**Comment by gsn7** [comment]
have you added the following to the interproscan.properties file :
 cath.resolve.hits.switches.gene3d=--input-format=hmmer_domtblout
send the full output after you add this.
