### ISSUE TITLE
Testing the service with server ip address

### ISSUE THREAD

**Issue by 2236529177** [ebi-pf-team/interproscan#45]
thanks for your great contributiuon to makw such a big software for us. 
I want to ask if  I want to test the lookup service with a sever ip address, can you give us an example

**Comment by 2236529177** [comment]
I want to revise the url as "192.168.xx.xxx" , but how the process find the local look-up, we do not need to give the local look-up path?
thanks a lot

**Comment by gsn7** [comment]
sorry, missed this post. hope you found a solution to the question if not open  a new issue
