### ISSUE TITLE
erro while after # the lookup function

### ISSUE THREAD

**Issue by 2236529177** [ebi-pf-team/interproscan#46]
Error output from binary:
bin/blast/ncbi-blast-2.6.0+/rpsblast: error while loading shared libraries: libgnutls.so.28: cannot open shared object file: No such file or directory

**Comment by har-wradim** [comment]
I don't think the error message could be more transparent: the library is missing from your system.

	$ apt-file find libgnutls.so.28
	libgnutls28: /usr/lib/x86_64-linux-gnu/libgnutls.so.28
	libgnutls28: /usr/lib/x86_64-linux-gnu/libgnutls.so.28.30.1
	$ sudo apt-get install libgnutls28

**Comment by 2236529177** [comment]
yes, thanks for you help. but we have “Computer cluster”， we need to make them share the same enviroment, so apt-get may not be a method

**Comment by 2236529177** [comment]
I check the requirements as the manual tells, I am encountered a bew problem as below:
bin/sfld/sfld_postprocess: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bin/sfld/sfld_postprocess)

It is reall y tough for me to install such packages, so can you give another checkfile to make the indeed requirements.

I really appreciate your help.

**Comment by 2236529177** [comment]
thanks,  after a whole day try, I finally get it, our admistrator does not take this into his duty. 
thanks @har-wradim

**Comment by mifraser** [comment]
Hi, you can also try to compile the rpsblast (cdd) and sfld binaries on your own system and use those within InterProScan instead. There are instructions for this in https://github.com/ebi-pf-team/interproscan/wiki/KnownIssues#1-cddrpsblast-gene3d-and-sfld-errors-on-older-or-new-systems

**Comment by 2236529177** [comment]
@mifraser thanks， I install hmm and replace the the path as sfld readme tells, thanks. I want to know whether you ever set the local look-up, thanks
