### ISSUE TITLE
make major versions interoperable

### ISSUE THREAD

**Issue by rmflight** [ebi-pf-team/interproscan#5]
It would be really nice if there was a way to keep interoperability on the major version numbers for local installs that use the lookup service, especially given how often there are new releases. 

We have analyses where we run Interproscan on thousands of sequences, so of course we setup our own local installation.

However, with every *new* release of interpro (currently every couple of months), our local install cannot make use of the lookup service. So we have to install and test the new versions (not a trivial process), or have really slow local lookups.  However, setting up our own lookup server looks to be way more work than re-installing Interproscan itself.

In my mind, any release of software marked the same by major version (e.g. v5.x.y) should all work together. When the major release changes, it is expected that they will no longer work. However, this is not the case for Interproscan. 

I realize that this is partly due to how the software and databases are tied together, however it seems there should be some kind of possible solution where the regular expressions and hidden markov models in each database get a set of *version tags*, so that older versions of local installations could still use the online lookup service?

**Comment by gsn7** [comment]
Each InterProScan-5 release is synchronised with an InterPro release. So, InterProScan version 5.19-58.0 will be synchronised with InterPro release 58.0. A user searching InterPro 58.0 via the InterPro  website or using InterproScan 5.19-58.0 will get the same results. The lookup-match service is also synchronised with an InterPro release.

The API for InterProScan-5 is largely unchanged across all 5.x releases and that is conformant to the versioning convention.

To build a lookup-match service that works across InterPro releases requires lots of changes. Using version tags you suggest would not scale. Moreover such a service would require more time and resources to support it. There are no plans to do this at this time. 

We are aware some users want to continue using older versions of InterProScan or analyse private data. These users can use the local lookup match service, which they can support as long as they like. We have made the setup and configuration of the local lookup match service as straightforward as possible. 

If you are having problems with the setup of the local lookup match service let us know, and we are happy to help or make improvements.

Regards,
Gift
