### ISSUE TITLE
default cutoff threshold ?

### ISSUE THREAD

**Issue by ptranvan** [ebi-pf-team/interproscan#53]
Hi, 

I have run a simple command to retrieve pfam, ipr and go annoataion.

However, I don't find any information about the default cut-off from which a hit is reported.

Can you tell me where to find this information ?

Thanks for your help,
Patrick

**Comment by gsn7** [comment]
refer to [#9](../issues/9) 
we will improve the documentation wrt cutoff soon.

**Comment by jelber2** [comment]
Hi, I was wondering if this issue has been addressed yet, or if it is possible to add an enhancement to adjust default cut-offs for pfam to interproscan.

**Comment by gsn7** [comment]
You can not adjust the cutoff for Pfam as a whole, as Pfam uses Gathering thresholds. so each hmm profile for Pfam has a Gathering threshold - GA cut-off. InterProScan runs Pfam with Gathering thresholds turned on
