### ISSUE TITLE
Missing Input File When Using Phobius

### ISSUE THREAD

**Issue by TheOneHyer** [ebi-pf-team/interproscan#54]
First off, thanks to all the developers that have made such an amazing meta-database analysis software suite. I have installed InterProScan5 on our lab's computational cluster and acquired licenses for Phobius, TMHMM, and SignalP. With a few minor configuration tweaks (alternate install location) everything ran smoothly except for the Phobius database analysis. When running the [test runs](https://github.com/ebi-pf-team/interproscan/wiki/HowToRun#interproscan-5-test-run) listed on the InterProScan5 wiki, the following error arose:
```
Command: bin/phobius/1.01/phobius.pl /home/ahyer/downloads/temp/node2_20180312_183205248_c0b5//jobPho
bius/000000000001_000000000006.fasta 
Error output from binary:
Phobius ver 1.01
(c) 2004 Lukas Kall, Anders Krogh, Erik Sonnhammer

Could not read provided fasta sequence at bin/phobius/1.01/phobius.pl line 408.
```

As detailed in the error, the file:

> /home/ahyer/downloads/temp/node2_20180312_183205248_c0b5//jobPhobius/000000000001_000000000006.fasta

did not exist. I assume that interproscan.sh is not properly creating this intermediate file before attempting to run Phobius. Unfortunately, I do not know enough Java to help troubleshoot code but I am very willing to test patches. I've attached the full run log below.

[interpro.log](https://github.com/ebi-pf-team/interproscan/files/1808036/interpro.log)

I should note that if I disable the Phobius analysis, everything runs perfectly.

**Comment by gsn7** [comment]
this might be due to permissions or your set up and it might be worth trying several things: can you run the following command on your cluster
`bin/phobius/1.01/phobius.pl  test_all_appl.fasta`
if the command gives no errors, then try the following: change this property to force `delete.temporary.directory.on.completion=false` and run the test `./interproscan.sh -i test_proteins.fasta -f tsv -appl phobius`.  if this fails it would allow you to check if the specified fasta file actually exists

**Comment by TheOneHyer** [comment]
Thanks for responding so quickly and helping me through this process. I ran `bin/phobius/1.01/phobius.pl test_all_appl.fasta` successfully, then set `delete.temporary.directory.on.completion=false` and ran `./interproscan.sh -i test_proteins.fasta -f tsv -appl phobius`, which failed with the same error:

> Could not read provided fasta sequence at bin/phobius/1.01/phobius.pl line 408.
> ...
> java.lang.IllegalStateException: Command line failed with exit code: 126
> Command: bin/phobius/1.01/phobius.pl /home/ahyer/downloads/temp/node2_20180314_141847638_b04m//jobPhobius/000000000001_000000000006.fasta

However, that files exists and is readable:

> ls -lh /home/ahyer/downloads/temp/node2_20180314_141847638_b04m//jobPhobius/000000000001_000000000006.fasta 
> -rw-rw-r--. 1 ahyer ahyer 1.7K Mar 14 14:19 /home/ahyer/downloads/temp/node2_20180314_141847638_b04m//jobPhobius/000000000001_000000000006.fasta

I decided to manually run that command and it succeeded as follows:

> ./interproscan-5.28-67.0/bin/phobius/1.01/phobius.pl /home/ahyer/downloads/temp/node2_20180314_141847638_b04m//jobPhobius/000000000001_000000000006.fasta
> Phobius ver 1.01
> (c) 2004 Lukas Kall, Anders Krogh, Erik Sonnhammer
> 
> ID   1
> FT   DOMAIN        1    122       NON CYTOPLASMIC.
> ...

I've attached the full log file for this run of interproscan:

[interpro.phobius.log](https://github.com/ebi-pf-team/interproscan/files/1812970/interpro.phobius.log)

I'm not sure why I'd be able to run this command myself yet it fails when run by interproscan. Perhaps this is a permissions issue of some odd sort.

**Comment by TheOneHyer** [comment]
There is definitely a permissions issue here as when I run `sudo /usr/local/bin/interproscan.sh -i interproscan-5.28-67.0/test_proteins.fasta -f tsv -appl phobius` everything works fine. I'll be investigating this further today.
