### ISSUE TITLE
MobiDBLite not included ?

### ISSUE THREAD

**Issue by ptranvan** [ebi-pf-team/interproscan#55]
Hi,

Can you confirm that MobiDBLite intergration is not included during interproscan analysis ?

What I get is not an accession but "mobidb-lite".

**Comment by gsn7** [comment]
MobiDBLite is included by default in interproscan. a tsv output example for a MobiDBLite hit on a uniprot sequence UPI0000167F57  looks like as below:
UPI0000167F57	5f052143dad9be4819a7e9c14e53611d	1581	MobiDBLite	mobidb-lite	consensus disorder prediction	609	705	-	T	27-02-2018

send us your output.

**Comment by ptranvan** [comment]
Ok I have the "consensus disorder prediction" result, but I thought there will be an accession associated.
