### ISSUE TITLE
itegrity of the local lookup file

### ISSUE THREAD

**Issue by scienceforever** [ebi-pf-team/interproscan#56]
Hello, 

I have downloaded the local lookup service archive lookup_service_5.28-67.0.tar.gz
While the md5 sum checks fine, tar returns an error in the middle of successfully started uncompressing complaining about the file's integrity.
I am concerned about "location 1 => location 2 => generating md5" sort of situation when the file got corrupted while transferred to the actual ftp server ("location 2") (ftp.abi.ac.uk) 

Could you please check this?

**Comment by gsn7** [comment]
I have checked the lookup service files and they are not corrupted. I also downloaded and uncompressed the archive and started the service without problems. 
maybe try again  uncompressing the archive
