### ISSUE TITLE
Addition of numbers to identifiers in first column of tsv file

### ISSUE THREAD

**Issue by Luddo94** [ebi-pf-team/interproscan#61]
Hey, 

I've run interproscan-5.28-67.0 on a predicted set of transcripts and everything worked great. As the title suggests, the sequence identifiers in the first column of my `tsv` output has had numbers added to the end of the ID. 

For example, `transcript0001` might have multiple entries in the form of `transcript0001_13`, `transcript0001_21` and `transcript0001_27`. 

I've had a look around and couldn't find an explanation of what they represent. Am I able to edit the identifiers back to their original state? or is it best to keep the numbered versions?  

Any help would be appreciated. 

Cheers
Al

**Comment by gsn7** [comment]
InterProScan treats each sequence header as 
> seq1_UniqueIdentifier Description of seq1

Any string after > up to the first space break is treated as the sequence identifier. Any string after the space break is a description. If the sequence identifier is not unique in your input, InterProScan will make them unique by adding numbers as you can see from the TSV output.

For the TSV output, only the sequence identifier is output and you can't map the identifier to the original header using info from the tsv output alone. You can use json, or xml outputs as they will have the complete original header info. 

Or you can also get both the tsv, xml or json outputs (using -f tsv,xml) and get the original header from the xref element in xml i.e., protein/xref@name element.  protein/xref@id is your sequence identifier. The xref looks like <xref id="seq1_UniqueIdentifier" name="seq1_UniqueIdentifier Description of seq1"/>

**Comment by gsn7** [comment]
The xref looks like
`<xref id="seq1_UniqueIdentifier" name="seq1_UniqueIdentifier Description of seq1"/>`

**Comment by Luddo94** [comment]
Great, thanks for the info! 

Cheers
