### ISSUE TITLE
H2 Database Problems

### ISSUE THREAD

**Issue by TheOneHyer** [ebi-pf-team/interproscan#62]
I am currently running InterProScan on a large dataset and keep getting errors for the PRINTS database as follows:

> [amqEmbeddedWorkerJmsContainer-14] [uk.ac.ebi.interpro.scan.management.model.implementations.prints.ParsePrintsOutputStep:119] WARN - H2 database problem: failed to verify 117 matches in database for PRINTS after 1059039 ms  - matches found : 117

I've received about a dozen of these warnings and couldn't find anything about them online after several hours of research. I can run the test file successfully on my analysis cluster:

> interproscan.sh -i /usr/local/src/interproscan-5.28-67.0/test_all_appl.fasta -dp

**Comment by gsn7** [comment]
How big is input data? Looks like  its taking longer than usual for access operations to the the embedded db which is usually a sign is overloaded. If the input size is greater than 48,000 protein sequences I would recommend you chunk the input.

**Comment by TheOneHyer** [comment]
My input is huge as I'm working on a very large metagenomic dataset. The FAA file I gave InterProScan5 has 1,684,117 protein sequences. I will work on subdividing the reads to see if that works.

**Comment by gsn7** [comment]
that size of input is guaranteed to fail. chunk it up into smaller bits say no more than 48,000. and for metagenomic sets use -dp option all the time.

**Comment by anadon** [comment]
Why is there such an input limit?  Is it a technical limitation or a design choice?  That may be something which can be improved.

**Comment by TheOneHyer** [comment]
For anyone interested, I'm now trying to run InterProScan5 on metagenomic datasets using GNU Parallel. Here's my current test (I'll post if this works):

`parallel --pipepart --recstart ">" --block 10M --cat --jobs **<number of jobs to run at once>** interproscan.sh --cpu 1 --disable-precalc --iprlookup --goterms --pathways --input {} --output-dir interproscan-output-{#} :::: **FAA file**`

The 10MB block comes from the size of the first 40,000 sequences in my FAA file:

`head -n 80000 **<FAA file>** | wc -b | numfmt --to=iec`

While working this all out, I wanted to point out that the Parallel option `--cat` is necessary as InterProScan5 does not read from STDIN, and `--compressed` could not be used to reduce I/O as InterProScan5 cannot read compressed files.

**Comment by TheOneHyer** [comment]
I got the syntax of parallel down and this iteration of the command is currently running (InterPRosScan needs pre-existing output directories and won't create it's own so I had to run a shell):

> cpus=<Number of jobs to spawn concurrently>
> FAA=<Path to amino acid FASTA file>
> 
> parallel --pipepart --recstart ">" --block $(head -n 80000 ${FAA} | wc -c | numfmt --to=iec) --cat --jobs ${cpus} 'itmdir="intermediates/intermediate-${RANDOM}"; mkdir intermediates/${itmdir}; interproscan.sh --cpu 1 --disable-precalc --iprlookup --goterms --pathways --input {} --output-dir ${itmdir}' :::: ${FAA}

I'll post here if/when it succeeds in running. Of course, I'll have to work on a way to combine the output files afterwards but that should be a matter of using `cat` and maybe `head` to remove any header lines.
