### ISSUE TITLE
InterProScan logging on a single machine.

### ISSUE THREAD

**Issue by LeeBergstrand** [ebi-pf-team/interproscan#63]
Problem Description
--------------------
I am running InterProScan on a single machine. I am interested in having it generate a log file during processing of a known dataset which I can check later and parse out how long each database takes to scan through this dataset. I plan to triage and remove database that take longer than we need.

How to I activate logging. I noticed that the cluster configuration in the interproscan.propterties file can receive a logging folder property. Can this be used with a single machine as well? Where are the logs stored during a run?

**Comment by gsn7** [comment]
you will have to profile each database using --applications option  and use the standard output you get from interproscan. the logs option for cluster mode produces similar  standard output you get from standalone interproscan, but the logs are for each worker started on the cluster.

**Comment by LeeBergstrand** [comment]
@gsn7 Understood.

Is there a verbose output option? Perhaps something you can turn on in the ```interproscan.properties ``` file?

**Comment by gsn7** [comment]
verbose parameter added for the next release
