### ISSUE TITLE
Is there a way to pass InterProScan a set of member database sequence identifiers

### ISSUE THREAD

**Issue by LeeBergstrand** [ebi-pf-team/interproscan#64]
Problem Description:
---------------------

Is there a way to pass InterProScan a set of member database sequence identifiers and have it scan only for these? For example if I only want to scan for PTHR15154, TIGR03478 and PF00146 but not the other members of their respective databases. Or do I have to go in and strip out the data for all the other sequences in these databases?

**Comment by gsn7** [comment]
Why would you want to do that? 
You cannot pass database profile/signature identifiers and run interproscan only on those profiles. Running a subset of the HMMs is not a good idea. The way databases like Pfam, Panther implement post-processing is based on competitive scoring (ie, if a sequence makes a more significant match to one HMM than another, the highest scoring match wins out). If you use only a subset of HMMs, this competitive scoring will be affected and you will see different results to those obtained using the vanilla version of Pfam or InterPro.

**Comment by LeeBergstrand** [comment]
@gsn7

I am currently working on a project which is based off of [EBI Genome Properties](https://github.com/ebi-pf-team/genome-properties). Genome properties takes InterProScan output, however, it only uses a small subset of HMMs from the respective member databases. I was thinking if I could run only a subset of the HMMs we could get significant improvements in runtime. For example some properties only use one or two HMMs from a member database.

| Database Used             | HMMs used in all genome properties | HMMs used in released Genome Properties |
|---------------------------|-----------------------|----------------------------|
| ProDom                    | 3                     | 0                          |
| PFAM                      | 847                   | 551                        |
| PIRSF                     | 25                    | 2                          |
| PRINTS                    | 24                    | 0                          |
| PROSITE                   | 1                     | 0                          |
| PANTHER                   | 173                   | 13                         |
| SMART                     | 14                    | 1                          |
| TIGRFAM                   | 3028                  | 2463                       |
| Conserved Domain Database | 48                    | 1                          |
| Runtime                   | 173m = ~3 hours       | 111m = ~2 hours            |

Run times are for the _E. coli_ K12 proteome. 

Machine Info:

2x Intel E5310 (4c/4t) @ 1.60GHz
16 GB DDR2 ECC

Since these databases use competitive scoring and EBI Genome Properties uses the vanilla  scoring from InterProScan I assume that I must scan using the whole database. Can you suggest any other optimizations? I assume we would have to just scale out?

@gsn7 Can you point me towards some documentation on how the competitive scoring works?

Cheers

**Comment by gsn7** [comment]
sorry for the late reply here.
the pfam post processing happens here : https://github.com/ebi-pf-team/interproscan/blob/dev/core/business/src/main/java/uk/ac/ebi/interpro/scan/business/postprocessing/pfam_A/PfamHMMER3PostProcessing.java

and panther post processing happens here:  https://github.com/ebi-pf-team/interproscan/blob/dev/core/jms-implementation/support-mini-x86-32/bin/panther/panther_score.py

if genome properties use only a subset of member databases then use the -appl option to select those databases.
