### ISSUE TITLE
Result ID Splitting and Conversion

### ISSUE THREAD

**Issue by davidbio** [ebi-pf-team/interproscan#65]
Hi there,

I discussed this already with IPS support some time ago, but the "problem" remains.

[Input Fasta](https://github.com/ebi-pf-team/interproscan/files/2004943/gi.fasta.gz):

```xml
>gi|347618773|ref|NW_003533882.2|.g1
MPSVDDVLEQVGEFGWFQKQAFLNLCLTSVAFAPIYVGI...
```

Results in [gi.xml.gz](https://github.com/ebi-pf-team/interproscan/files/2004946/gi.xml.gz):

```xml
<protein>
          <sequence md5="ca675a0921ba91880dc9d9f7a07a4be0">MPSV...</sequence>
          <xref desc=".g2" db="ref" id="NW_003608984.1_7"/>
          <matches>
```

In the result the GI is missing, I cannot reconstruct the original name and therefore am unable to match the result.

[stdout.txt.gz](https://github.com/ebi-pf-team/interproscan/files/2004949/stdout.txt.gz)
This behavior is the same with the latest release 5_29_68.

I think the problem is located in XrefParser.java around line 141:
https://github.com/ebi-pf-team/interproscan/blob/ae28f3abae7a363d8298c806c5f98afe627b29a3/core/io/src/main/java/uk/ac/ebi/interpro/scan/io/sequence/XrefParser.java

The problem is that `chunks[1]` which contains the actual GI, is not passed on.

My question is, what is the benefit of splitting up the name?
Why not keep the name "as is"?

To me it would make more sense to conserve the name "as is" and to provide additional fields as you like.
E.g.:
```xml
...
<sequence md5="431b65776dcf20444b97fc43cb8acf71">MTLEEGM...</sequence>
<xref original_name="gi|347618773|ref|NW_003533882.2|.g1" desc=".g1" db="ref" id="NW_003533882.2"/>
<matches>
```

Best,
David

**Comment by gsn7** [comment]
this has been resolved a few months ago. since release 5.28-67.0, the xref element has  'name' and 'id'  attributes. The name is the original header and the id a unique identifier derived from the header.  eg. 
`<sequence md5="c4946129e274ef676215e4b64fd627d9">MPSVDDVLEQVGEFGWFQKQAFLNLCLTSVAFAPIYVGI</sequence>
        <xref id="gi|347618773|ref|NW_003533882.2|.g1" name="gi|347618773|ref|NW_003533882.2|.g1"/>`

can you check for release 5_29_68 that you really still have this problem?

**Comment by davidbio** [comment]
I just gave it a try and it works, thank you!
