### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by jjkoehorst** [ebi-pf-team/interproscan#67]
I am using a json parser to convert to json output to RDF. However did the JSON format change recently? And is there any documentation on the changes? As I was using cross references and models but they no longer seem to be present?

**Comment by mifraser** [comment]
The JSON format did change slightly in 5.28-67.0. The "models" were replaced with a "model-ac". It's briefly described in https://github.com/ebi-pf-team/interproscan/wiki/Interproscan5_28_67_ReleaseNotes - we will look at improving the JSON documentation on the wiki in the future.

The cross references should still be there, if you still can't find something then please could you supply an example with what seems to be missing? The fields changed slightly (e.g. identifier became id). Thanks!
