### ISSUE TITLE
Interproscan JAVA Environmental Variable Problem?

### ISSUE THREAD

**Issue by henricombrink** [ebi-pf-team/interproscan#71]
I am trying to get interproscan to work on my personal computer. Ubuntu 16.04 LTS.

I have set the JAVA environmental variables in my /etc/environment file:
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin"
JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java"
export JAVA_HOME
CLASSPATH="/usr/lib/jvm/java-8-openjdk-amd64/lib:."
export CLASSPATH

Running this in the command line:

$ bash ./interproscan.sh -i test_proteins.fasta -f tsv

Gives me this error:

05/07/2018 16:57:35:741 Welcome to InterProScan-5.30-69.0
05/07/2018 16:57:46:524 Running InterProScan v5 in STANDALONE mode... on Linux
2018-07-05 16:57:46,592 [Thread-7] [uk.ac.ebi.interpro.scan.jms.activemq.CleanRunDatabase:100] FATAL - Unable to find original database file: work/template/interpro.zip
Exception in thread "Thread-7" java.lang.IllegalStateException: Unable to find original database file
	at uk.ac.ebi.interpro.scan.jms.activemq.CleanRunDatabase.cleanInstalledDatabase(CleanRunDatabase.java:101)
	at uk.ac.ebi.interpro.scan.jms.activemq.CleanRunDatabase.run(CleanRunDatabase.java:76)
	at java.lang.Thread.run(Thread.java:748)

I would really appreciate some assistance,

Thanks,

Henri

**Comment by gsn7** [comment]
i don't expect this error when running on a native Linux system. Are you running on a native Linux system or within another system like the Windows Linux Subsystem?
did you check the integrity of the interproscan download file with 'md5sum' check?

**Comment by henricombrink** [comment]
Hi,

I am on a native Ubuntu system.  The checksum returned OK.

Anything I can maybe try?

Thanks

**Comment by gsn7** [comment]
this more likely has to do with your $PATH setup
what is your default shell _'echo $SHELL'_
when you issue the comman _'echo $PATH'_ do you get _'.:'_ as part of the path output?

**Comment by henricombrink** [comment]
My output:

echo $SHELL : /bin/bash

echo $PATH : 
.:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/jre/bin:/home/henri/Interproscan/interproscan-5.30-69.0/
