### ISSUE TITLE
interpro -t n hangs for large files

### ISSUE THREAD

**Issue by timkahlke** [ebi-pf-team/interproscan#72]
I tried running interproscan 5.30 on a large (~200k sequences) transcriptome file using the -t n option. I tried this before with another version but updated everything to the newest release. Unfortunately, it seems it's getting stuck after the getOrfs call. Unfortunately no error messages. The java process just get's stuck for days without doing much ... or better, it does "something" as indicated by cpu usage but still nothing happens. The output file for getOrfs in the temp folder seems complete but annotation doesn't start.

I tested it with small files ~1,000 sequences and had no problems though.

**Comment by mifraser** [comment]
Large numbers of sequences can cause performance problems like this. Chunking inputs into files of 1,000 nucleic acid sequences or 10,000 protein sequences is advised. Some more tips for improving performance are mentioned in https://github.com/ebi-pf-team/interproscan/wiki/ScanNucleicAcidSeqs#improving-performance

**Comment by jjkoehorst** [comment]
I have seen this message a few times now and perhaps a default parameter -split 1000 would people to at least by default make it possible to run interproscan no matter the file size. They can always tune the parameter further depending on their system specs but then they are diving deeper into the application. What do you think?

**Comment by gsn7** [comment]
the latest release,v5.37-76.0 should deal with large input much better
