### ISSUE TITLE
tmpdir of a crashed job

### ISSUE THREAD

**Issue by wkpalan** [ebi-pf-team/interproscan#75]
Would passing the `--tempdir`  parameter allow to continue jobs that have failed in the middle?

**Comment by mifraser** [comment]
Unfortunately it is not possible to restart jobs that have failed with the current software.

One suggestion if your jobs are taking a long time to run before failing, you could consider splitting them into smaller chunks and combining the output: https://github.com/ebi-pf-team/interproscan/wiki/ImprovingPerformance
