### ISSUE TITLE
error run rpsblast

### ISSUE THREAD

**Issue by huangl07** [ebi-pf-team/interproscan#76]
/mnt/ilustre/users/dna/.env//bin/rpsblast -query /mnt/ilustre/users/long.huang/DataBase/2018-8-27/InterProScan/interproscan-5.30-69.0/demo/temp/login02.local_20180903_082447080_f20j//jobCDD/000000023301_000000023375.fasta -db data/cdd/3.16/db/Cdd_NCBI -evalue 0.01 -seg no -outfmt 5 
Error output from binary:
[rpsblast] ERROR: Invalid argument: -query

thankyou！

**Comment by mifraser** [comment]
How are you running InterProScan? I assume you did https://github.com/ebi-pf-team/interproscan/wiki/HowToDownload and https://github.com/ebi-pf-team/interproscan/wiki/HowToRun

By default InterProScan should use the binary bin/blast/ncbi-blast-2.6.0+/rpsblast included within the distribution. In your output it says /mnt/ilustre/users/dna/.env//bin/rpsblast which appears to be a different version of rpsblast. InterProScan needs rpsblast 2.6.0+ which has the -query parameter (some versions of rpsblast don't support that). The default would give...

$ bin/blast/ncbi-blast-2.6.0+/rpsblast -version
rpsblast: 2.6.0+
 Package: blast 2.6.0, build Dec  7 2016 14:50:34

$ bin/blast/ncbi-blast-2.6.0+/rpsblast -h
...
[-query input_file]
...

Did you change any properties in the interproscan.properties? And what is the interproscan.sh command you are you running?

This isn't your error here, but many people have seen "error while loading shared libraries: libgnutls.so.28: ca nnot open shared object file: No such file or directory" while running rpsblast. If you got that then it can be resolved by: https://github.com/ebi-pf-team/interproscan/wiki/CompilingBinaries#rpsblastrpsbproc-used-by-cdd
