### ISSUE TITLE
hardcoded perl PATH in bin/prodom/2006.1/ProDomBlast3i.pl

### ISSUE THREAD

**Issue by estolle** [ebi-pf-team/interproscan#83]
Hi there

I just updated to interproscan-5.33-72.0 from an earlier version.

as in the earlier version, i found that at least one of the perl scripts contains a hard-coded perl-PATH's

File: bin/prodom/2006.1/ProDomBlast3i.pl
starts with #!/ebi/extserv/bin/perl/bin/perl

Had to be changed to #!/usr/bin/perl in order to be executable. 

I guess this is not supposed to be like this. Its an easy fix to change it myself but perhaps this was overlooked thus far.

**Comment by gsn7** [comment]
thanks, we will update this in the next release

**Comment by mifraser** [comment]
Resolved in InterProScan 5.34-73.0
