### ISSUE TITLE
FUTEX_WAIT_PRIVATE ETIMEDOUT

### ISSUE THREAD

**Issue by hwalinga** [ebi-pf-team/interproscan#87]
Interproscan seemed to be stuck. When I run "strace" on some of its processes all produced a continuous flow of the following messages:

```
futex(0x7f2ba400be78, FUTEX_WAIT_PRIVATE, 0, {0, 99998672}) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f2ba400be28, FUTEX_WAKE_PRIVATE, 1) = 0
```

Not sure what causes this and how it can be solved. It might be related to the fact I am running 20 instances of interproscan simultaneously. (In my tests adding more instances improved the speed, and it did that successfully for already a very large part of the analysis.)

**Comment by gsn7** [comment]
not sure this issue is a bug in interproscan. so am closing this.
