### ISSUE TITLE
CPU switch usage unclear

### ISSUE THREAD

**Issue by davidbio** [ebi-pf-team/interproscan#88]
I hope you can help me with this one.
The CPU switch is said to override any settings in interproscan.properties.
Setting it to 1 should employ 1 CPU and setting it to 5 should employ 5 CPUs, etc.
Am I correct?
Because after running a few tests, I realized that e.g. setting CPU to 8 uses about 3 to 4 CPUs or less.
I have run many (thousands) jobs with different data (all amino acids) and ranging from 100 to 200 sequences per input FASTA.

Additionally:
Setting CPU to 4 makes the program stall after some time and it never terminates (I killed the processes after a few hours of runtime). This happens every time with different input data.

The above has been reproduced with the last 3 major releases of IPS.
Currently I am using IPS 5.33-72.0 with: TIGRFAM, SFLD, Phobius, SignalP_GRAM_NEGATIVE, SUPERFAMILY, Gene3D, Hamap, ProSiteProfiles, Coils, SMART, CDD, PRINTS, ProSitePatterns, SignalP_EUK, Pfam, ProDom, MobiDBLite, SignalP_GRAM_POSITIVE, PIRSF, TMHMM.

Please let me know what additional information/data you need to look into this.

**Comment by gsn7** [comment]
i can also reproduce this behaviour. this is a bug in the way --cpu option is implemented. we will work to fix this.

**Comment by gsn7** [comment]
latest version v5.38-76.0 has the fix for this issue

**Comment by davidbio** [comment]
Thank you for looking into this gsn7.
I can confirm that --cpu 1 2 3 4 do not make the program stall anymore.
