### ISSUE TITLE
Interpreting E-values on Interpro

### ISSUE THREAD

**Issue by lilipeng** [ebi-pf-team/interproscan#9]
Hi,

I was reading the manual on Github about e-values:

"9.Score - is the e-value of the match reported by member database method (e.g. 3.1E-52)"

In the process of determining a threshold cutoff for e-values, I presume that the each of the source member databases have their own cutoff scores?  Is that information provided on Interpro, or must I search through each source database to find such threshold cutoffs?

thanks,
Lili

**Comment by gsn7** [comment]
Hi Lili,
the cut-offs are buried in the interproscan code. however, with respect to InterPro these cutoffs by themselves would not tell you the complete story as some member databases use other measures to filter matches (e.g. Pfam and the Hmmer GA cut-off). 

what you could do is to check whether or not a signature has been included in InterPro and
has an InterPro accession associated with the result.  If it has, it means it has passed our
additional quality checks and is very unlikely to be a false match.

**Comment by lilipeng** [comment]
Hi,

Thanks for the explanation.  When you say "check whether or not a signature has been included in InterPro and has an InterPro accession associated with the result." Do you mean that both the row entries for columns 'Signature_Description' and 'InterPro_Accession_ID'  must not be empty?

Thanks,
Lili

**Comment by gsn7** [comment]
its the InterPro_Accession_ID that would show the signature has passed through our curators quality checks.
