### ISSUE TITLE
What does mean prefix at the end?

### ISSUE THREAD

**Issue by ConstantinV** [ebi-pf-team/interproscan#90]
Hello,

After uploading fasta file with ORFs in nucleotides, I've received tsv table where each ORF name has a prefix like _N at the end where N is an integer number. What is the meaning of this number?

Thank you.

**Comment by gsn7** [comment]
given a nucleotide sequence with header 'nucleotide_sequence_header' , running interproscan generates several ORFs and to guarantee uniqueness, the header of each ORF is given a suffix - a unique number for each sequence so you end up with ORFs with headers 'nucleotide_sequence_header_1' .. 'nucleotide_sequence_header_N'

**Comment by ConstantinV** [comment]
Thank you!
