### ISSUE TITLE
FASTA output directly

### ISSUE THREAD

**Issue by Sanrrone** [ebi-pf-team/interproscan#92]
Hi, is there an option to obtain directly the protein and cds sequences?, is quite weird the gff3 file that interpro write, I tried bedtools, AEGENtools, and gff2fasta.pl (script from internet) to get my sequences and the only that works was bedtools but the names are not the same from the tsv and gff3.

regards

**Comment by gsn7** [comment]
you have to give more details of what you are trying to do, what is weird about the interpro gff3. can you give us an example of the commands you are using for bedtools and a sample of the input files.

we don't use gff3 internally but have validated it against the gff3 specification using tools such as http://genometools.org/cgi-bin/gff3validator.cgi

**Comment by Sanrrone** [comment]
For example, there is no coincidence between the ids from tsv (first col) and the gff3 ids (locus tag?).
a real case would be:
`interproscan -i genomeTest.fna -iprlookup -f TSV,GFF3 -t n`

give me a tsv with ids (col 1):
```
head -n 5 genomeTest.tsv
CP005987.1_94	5b2a736abc2199f6df254c2695e6e5d2	652	CDD	cd00075	HATPase_c	44	179	2.46875E-14	T	24-05-2019	IPR003594	Histidine kinase/HSP90-like ATPase
CP005987.1_94	5b2a736abc2199f6df254c2695e6e5d2	652	PRINTS	PR01159	DNA gyrase subunit B signature	383	403	2.8E-65	T	24-05-2019	IPR000565	DNA topoisomerase, type IIA, subunit B
CP005987.1_94	5b2a736abc2199f6df254c2695e6e5d2	652	PRINTS	PR01159	DNA gyrase subunit B signature	188	203	2.8E-65	T	24-05-2019	IPR000565	DNA topoisomerase, type IIA, subunit B
CP005987.1_94	5b2a736abc2199f6df254c2695e6e5d2	652	PRINTS	PR01159	DNA gyrase subunit B signature	479	488	2.8E-65	T	24-05-2019	IPR000565	DNA topoisomerase, type IIA, subunit B
CP005987.1_94	5b2a736abc2199f6df254c2695e6e5d2	652	PRINTS	PR01159	DNA gyrase subunit B signature	229	251	2.8E-65	T	24-05-2019	IPR000565	DNA topoisomerase, type IIA, subunit B

```
where "CP005987.1" is the contig and "_94" the protein number found? trying to get in the gff what means this whole name "CP005987.1_94". I have
```
grep "CP005987.1_94" genomeTest.gff
CP005987.1	getorf	ORF	8485	10440	.	+	.	Target=pep_CP005987.1_8485_10440 1 652;ID=orf_CP005987.1_8485_10440;Name=CP005987.1_94;md5=9bc8a729e63c4bae580b7620621384e3 ```

and after some time looking for the sequence I got the Target tag from previous line is hold the sequence "pep_CP005987.1_8485_10440"
```
>pep_CP005987.1_8485_10440
FVSEPSYDASSITVLHGLEAVRRRPGMYIGDTGQESSGQGGQGLHHMVFEVVDNSVDEAL
AGYCDQITVRLLADGGCEVSDNGRGIPVDTHAEEGRSAAEVIMTVLHAGGKFDESSYKVS
...
```
so why just not add the id from tsv to this sequence headers, that is the reason of why bedtools and others can link the annotation. (Like prokka), indeed, I had to annotate with prokka and just give the proteins to interproscan just to conserve the IDs.

hope this can help
regards

**Comment by gsn7** [comment]
the gff3 output has been improved in release 5.41-78.0
