### ISSUE TITLE
CONVERT mode doesn't support JSON format

### ISSUE THREAD

**Issue by mglubber** [ebi-pf-team/interproscan#94]
This is a relatively minor issue, but trying `-mode convert -f json ...` gives the error:
`[uk.ac.ebi.interpro.scan.jms.converter.Converter:258] ERROR - The specified output format - json - is not supported!`

I checked the converter source (`interproscan/core/jms-implementation/src/main/java/uk/ac/ebi/interpro/scan/jms/converter/Converter.java`) and it doesn't seem to have anything to handle conversion to JSON output. 

The command line usage instructions suggest that JSON format is supported in CONVERT mode, and [the wiki documents](https://github.com/ebi-pf-team/interproscan/wiki/ConvertMode) are vague (it says XML to any other output format, then lists TSV, GFF3, SVG and HTML). Parsing XML isn't significantly harder than JSON, so supporting converting it isn't really necessary, but it would be nice if the wiki/command line usage was updated to clarify.

**Comment by gsn7** [comment]
v 5.38-76 includes conversion from xml to json
