### ISSUE TITLE
Interest in conda packaging?

### ISSUE THREAD

**Issue by abretaud** [ebi-pf-team/interproscan#95]
Hi,
I'd love to be able to install interproscan using conda, but no package is currently available. Would you be interested if I work on it?

Currently it's not easy to package it because the release archive contains both the code, the dependencies, and the data. It's just not possible to make a 10Gb conda package.

If there could be a minimal release archive containing only the code and the dependencies, we could make a conda package of it and ship a small script to download data from an external archive. Do you think it could be possible?

Ideally, dependencies would not need to be shipped in the minimal tarball if they are available as independent conda packages (like blast).

**Comment by abretaud** [comment]
Ah cool, I didn't know this was available!
What are mgbin and mgdata files?
These files are free to redistribute?
I'll look into creating a recipe from this.

**Comment by ropolomx** [comment]
I would be interested as well! Are there any updates on the creation of a bioconda recipe?

**Comment by abretaud** [comment]
I've looked a little into it, but it's a lot of work. IIRC the core archive comes with precompiled binaries that would not be usable as is (ie would not run on older linux versions as they were compiled on a recent distribution). Each of them would need to be rebuilt in a conda package.
I don't have too much time to work on this atm, feel free to work on it if you want!

**Comment by Juke34** [comment]
Here the list of dependencies already in conda:
    - hmmer2
    - hmmer >=3
    - blast
    - emboss

Here what is missing:
    - [ ]  cath-resolve-hits (used by CATH-Gene3D)
    - [ ]  Pfscan/Pfsearch (used by ProSite Profiles, ProSite Patterns and HAMAP)
    - [ ]  ncoils (used by Coils)
    - [ ]  fingerPRINTScan (used by PRINTS)
    - [ ]  rpsblast/rpsbproc (used by CDD)
    - [ ] sfld_preprocess/sfld_postprocess (used by SFLD)

Once done we can package interproscan

**Comment by Juke34** [comment]
Now we have all dependencies I started a recipe you can find here #22802

**Comment by abretaud** [comment]
That's super cool, thanks a LOT @Juke34 !

**Comment by drelo** [comment]
> Now we have all dependencies I started a recipe you can find here #22802

@Juke34  Hi! Did you managed to make the recipe? Do you have a link?

**Comment by Juke34** [comment]
I think I have made something like 90% of the work but I had to drop the project because  I have changed job and do not have any time to finish... 
See discussion here (https://github.com/bioconda/bioconda-recipes/issues/21601)[https://github.com/bioconda/bioconda-recipes/issues/21601]

**Comment by drelo** [comment]
Thanks for the response! An great this seems like a great ongoing work
indeed.
