### ISSUE TITLE
local lookup service array index out of range

### ISSUE THREAD

**Issue by vdtoorn** [ebi-pf-team/interproscan#96]
I have installed the lookup service with all of the data files locally, and it starts up, but there are errors during the startup process saying "array index out of range".

I don't know if this is a problem, but all of my searches seem very slow, even ones with large numbers of "standard" human sequences, which I thought would be present in the existing data.

Please advice, thank you.

**Comment by gsn7** [comment]
the error  'array index out of range' should not have effect on performance. but we will work to get rid of this error. so far it seems harmless

how fast your searches will be using the lookup service depends on what proportion of them are in  Uniprot (https://www.uniprot.org/)

**Comment by gsn7** [comment]
this bug is fixed in the latest release
